In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_NotAnyNull.csv')
df.head()

    Humi   WindSp  WindBe     Visi     Pres      Temp
0   0.89  14.1197     251  15.8263  1015.13  9.472222
1   0.86  14.2646     259  15.8263  1015.63  9.355556
2   0.89   3.9284     204  14.9569  1015.94  9.377778
3   0.83  14.1036     269  15.8263  1016.41  8.288889
4   0.83  11.0446     259  15.8263  1016.51  8.755556

In [3]:
pd.melt(df)

       variable      value
0          Humi   0.890000
1          Humi   0.860000
2          Humi   0.890000
3          Humi   0.830000
4          Humi   0.830000
...         ...        ...
578713     Temp  26.016667
578714     Temp  24.583333
578715     Temp  22.038889
578716     Temp  21.522222
578717     Temp  20.438889

[578718 rows x 2 columns]

In [6]:
pd.melt(df, id_vars = 'WindBe', value_vars = ' Humi', var_name = 'Humidity', value_name = 'Resultant')

       WindBe Humidity  Resultant
0         251     Humi       0.89
1         259     Humi       0.86
2         204     Humi       0.89
3         269     Humi       0.83
4         259     Humi       0.83
...       ...      ...        ...
96448      31     Humi       0.43
96449      20     Humi       0.48
96450      30     Humi       0.56
96451      20     Humi       0.60
96452      39     Humi       0.61

[96453 rows x 3 columns]