In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_SomeNull.csv')
df.head()

    Humi   WindSp  WindBe     Visi     Pres      Temp
0   0.89      NaN   251.0  15.8263  1015.13  9.472222
1    NaN  14.2646   259.0      NaN  1015.63       NaN
2    NaN   3.9284   204.0  14.9569  1015.94       NaN
3   0.83  14.1036     NaN      NaN  1016.41  8.288889
4   0.83  11.0446   259.0  15.8263  1016.51  8.755556

In [3]:
df.interpolate(limit = 1, limit_direction = 'forward', method = 'nearest')

        Humi   WindSp  WindBe     Visi     Pres       Temp
0       0.89      NaN   251.0  15.8263  1015.13   9.472222
1       0.89  14.2646   259.0  15.8263  1015.63   9.472222
2        NaN   3.9284   204.0  14.9569  1015.94        NaN
3       0.83  14.1036   204.0  14.9569  1016.41   8.288889
4       0.83  11.0446   259.0  15.8263  1016.51   8.755556
...      ...      ...     ...      ...      ...        ...
96448   0.43  10.9963    31.0  16.1000  1014.36  26.016667
96449   0.48  10.0947    20.0  15.5526  1015.16  24.583333
96450   0.56   8.9838    30.0  16.1000  1015.66  22.038889
96451   0.60  10.5294    20.0  16.1000  1015.95  21.522222
96452   0.61   5.8765    39.0  15.5204  1016.16  20.438889

[96453 rows x 6 columns]

In [4]:
df.interpolate(limit_area = 'outside')

        Humi   WindSp  WindBe     Visi     Pres       Temp
0       0.89      NaN   251.0  15.8263  1015.13   9.472222
1        NaN  14.2646   259.0      NaN  1015.63        NaN
2        NaN   3.9284   204.0  14.9569  1015.94        NaN
3       0.83  14.1036     NaN      NaN  1016.41   8.288889
4       0.83  11.0446   259.0  15.8263  1016.51   8.755556
...      ...      ...     ...      ...      ...        ...
96448   0.43  10.9963    31.0  16.1000  1014.36  26.016667
96449   0.48  10.0947    20.0  15.5526  1015.16  24.583333
96450   0.56   8.9838    30.0  16.1000  1015.66  22.038889
96451   0.60  10.5294    20.0  16.1000  1015.95  21.522222
96452   0.61   5.8765    39.0  15.5204  1016.16  20.438889

[96453 rows x 6 columns]

In [5]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_NotAnyNull.csv')
df.head()

    Humi   WindSp  WindBe     Visi     Pres      Temp
0   0.89  14.1197     251  15.8263  1015.13  9.472222
1   0.86  14.2646     259  15.8263  1015.63  9.355556
2   0.89   3.9284     204  14.9569  1015.94  9.377778
3   0.83  14.1036     269  15.8263  1016.41  8.288889
4   0.83  11.0446     259  15.8263  1016.51  8.755556

In [6]:
df.loc[0 : 1]

    Humi   WindSp  WindBe     Visi     Pres      Temp
0   0.89  14.1197     251  15.8263  1015.13  9.472222
1   0.86  14.2646     259  15.8263  1015.63  9.355556

In [7]:
df.loc[[0, 3]]

    Humi   WindSp  WindBe     Visi     Pres      Temp
0   0.89  14.1197     251  15.8263  1015.13  9.472222
3   0.83  14.1036     269  15.8263  1016.41  8.288889

In [8]:
df.loc[df[' Humi'] < 0.8, [' Temp']]

            Temp
9      13.772222
10     16.016667
11     17.144444
12     17.800000
13     17.333333
...          ...
96448  26.016667
96449  24.583333
96450  22.038889
96451  21.522222
96452  20.438889

[50418 rows x 1 columns]

In [9]:
df.iloc[:, 2:5]

       WindBe     Visi     Pres
0         251  15.8263  1015.13
1         259  15.8263  1015.63
2         204  14.9569  1015.94
3         269  15.8263  1016.41
4         259  15.8263  1016.51
...       ...      ...      ...
96448      31  16.1000  1014.36
96449      20  15.5526  1015.16
96450      30  16.1000  1015.66
96451      20  16.1000  1015.95
96452      39  15.5204  1016.16

[96453 rows x 3 columns]

In [10]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_NotAnyNull.csv')
df.head()

    Humi   WindSp  WindBe     Visi     Pres      Temp
0   0.89  14.1197     251  15.8263  1015.13  9.472222
1   0.86  14.2646     259  15.8263  1015.63  9.355556
2   0.89   3.9284     204  14.9569  1015.94  9.377778
3   0.83  14.1036     269  15.8263  1016.41  8.288889
4   0.83  11.0446     259  15.8263  1016.51  8.755556

In [11]:
df.groupby(by = 'WindBe').head()

        Humi   WindSp  WindBe     Visi     Pres       Temp
0       0.89  14.1197     251  15.8263  1015.13   9.472222
1       0.86  14.2646     259  15.8263  1015.63   9.355556
2       0.89   3.9284     204  14.9569  1015.94   9.377778
3       0.83  14.1036     269  15.8263  1016.41   8.288889
4       0.83  11.0446     259  15.8263  1016.51   8.755556
...      ...      ...     ...      ...      ...        ...
10678   0.86   5.9570      92   4.5080  1031.46  -3.372222
10976   1.00   7.4060      92   0.3381  1008.28   3.816667
13786   0.63   9.2092      78  11.2056  1014.09  22.733333
14278   0.81  15.9390      78  14.0553  1015.17   6.905556
14280   0.78  17.0821      78  14.7637  1016.25   7.472222

[1800 rows x 6 columns]

In [12]:
df.groupby(by = 'WindBe').groups

{0: [76, 381, 390, 641, 657, 1014, 1541, 1638, 1640, 1695, 1724, 1752, 1826, 1853, 1856, 1900, 1914, 1992, 2681, 3260, 3297, 3483, 3609, 3651, 3655, 3657, 3662, 3667, 3724, 3750, 3757, 3760, 3832, 3921, 3933, 3966, 4014, 4015, 4083, 4132, 4135, 4198, 4230, 4248, 4249, 4251, 4272, 4536, 4590, 4765, 5208, 5210, 5261, 5262, 5474, 5729, 5794, 5797, 5800, 5894, 5988, 6101, 6261, 6383, 6510, 7049, 7053, 7054, 7055, 7056, 7078, 7079, 7081, 7082, 7084, 7085, 7087, 7319, 7337, 7343, 7344, 7410, 7411, 7412, 7413, 7418, 7435, 7436, 7448, 7505, 7506, 7508, 7511, 7773, 7925, 7966, 7968, 8033, 8037, 8038, ...], 1: [321, 640, 2981, 3264, 3407, 3717, 3733, 3753, 3828, 3857, 3903, 4410, 4427, 4635, 4636, 4667, 4761, 4767, 4921, 5053, 5070, 5207, 5366, 5367, 5761, 6486, 7469, 7767, 8095, 8389, 8779, 8786, 9023, 9740, 10314, 10376, 10887, 10965, 12849, 12858, 13995, 14228, 14851, 14960, 15508, 15571, 15581, 15583, 15585, 15973, 15975, 15987, 16445, 16448, 16697, 17187, 17937, 18156, 18159, 18587, 19439, 19446, 19462, 19527, 19937, 20474, 20822, 21206, 21325, 21623, 21648, 21685, 21688, 21691, 22241, 22259, 22550, 23351, 24903, 25267, 25863, 25917, 27686, 27829, 28885, 34397, 35295, 35581, 35587, 35592, 35775, 35871, 35887, 37363, 37695, 37907, 37909, 38124, 38324, 38753, ...], 2: [247, 352, 2578, 2784, 2795, 2797, 3244, 3245, 3259, 3730, 3752, 3831, 4474, 4503, 4504, 5007, 5293, 5295, 5297, 5442, 5451, 5984, 6491, 6516, 7433, 7501, 8003, 8382, 8388, 8537, 8557, 9527, 9552, 9923, 10023, 10065, 10154, 10389, 10425, 10694, 10966, 13960, 14057, 14226, 14605, 16081, 16799, 17162, 18061, 18585, 18710, 19517, 19781, 19936, 21708, 22201, 22371, 23148, 23345, 23446, 23537, 23539, 23830, 24026, 24057, 24059, 24069, 24081, 24293, 27677, 27779, 27782, 27907, 30416, 31200, 31364, 34259, 35075, 35148, 35291, 35501, 35586, 35749, 36733, 37359, 37701, 38750, 38752, 38755, 38772, 38797, 38985, 39262, 39634, 39658, 39948, 39951, 39978, 40018, 40028, ...], 3: [231, 2736, 2980, 3193, 3740, 3846, 4056, 4065, 4370, 4428, 5036, 5221, 5716, 5723, 7988, 8141, 8840, 9506, 10007, 10182, 10440, 11100, 14046, 14145, 14220, 14842, 15549, 15570, 16085, 16131, 17159, 17201, 17708, 18738, 18950, 20876, 21596, 22159, 24135, 24365, 25251, 25704, 25811, 25983, 27365, 27533, 27868, 30137, 30599, 31115, 33450, 34802, 35146, 35290, 35865, 35866, 37358, 37370, 38749, 38871, 38982, 39005, 39616, 40090, 41946, 42447, 42473, 42652, 42823, 43454, 43794, 43830, 44033, 44034, 44063, 44159, 44393, 44675, 44771, 45112, 45128, 46426, 47071, 47294, 49297, 49759, 49900, 50023, 50418, 50464, 50491, 50845, 51679, 52337, 52394, 53381, 54362, 56248, 57273, 58960, ...], 4: [61, 1663, 2579, 3755, 4046, 4073, 4367, 4499, 7910, 8015, 8384, 9035, 9065, 9884, 9893, 10354, 10666, 12702, 12854, 14209, 14923, 15033, 15513, 15552, 16087, 16674, 17939, 17994, 18062, 19516, 19921, 20401, 21710, 22069, 23641, 24030, 24034, 24109, 24898, 24975, 25000, 26087, 29638, 31204, 34129, 35147, 35363, 38775, 38798, 40091, 40095, 40546, 43175, 43177, 44846, 45049, 45365, 45598, 46093, 46774, 47185, 48302, 48498, 48781, 49205, 49737, 50485, 51299, 52153, 53345, 53564, 53822, 54418, 58582, 58654, 58672, 59232, 61265, 61694, 61702, 62074, 62312, 63925, 64198, 65672, 66925, 66928, 67852, 68142, 69946, 72276, 74189, 76558, 79716, 79814, 79955, 80875, 80950, 80974, 82177, ...], 5: [743, 1167, 1670, 2343, 2686, 3484, 4424, 4497, 4934, 5164, 5483, 6251, 7059, 7766, 8049, 9553, 10822, 10963, 11992, 12105, 13355, 13804, 13959, 13975, 14149, 14700, 14827, 14868, 14941, 16745, 17381, 17707, 18074, 18164, 18249, 19104, 19109, 19111, 19525, 21961, 22239, 22261, 23235, 24892, 26672, 28861, 29710, 30473, 32260, 33844, 34472, 35950, 36081, 37691, 37702, 37900, 38005, 38385, 38653, 38870, 39245, 39452, 39596, 40689, 41272, 42557, 43427, 43442, 43816, 43872, 44336, 44689, 44774, 44789, 45806, 47270, 47291, 47300, 50424, 50466, 50807, 52046, 52048, 52741, 53426, 53439, 53758, 54293, 56876, 57377, 58525, 58690, 60037, 62326, 63808, 64242, 64246, 67109, 67376, 67587, ...], 6: [349, 644, 1699, 2319, 2735, 2761, 3486, 3615, 4050, 4937, 5039, 5722, 6478, 8399, 8555, 8929, 9053, 9352, 9528, 10423, 10945, 11533, 12013, 12880, 12914, 13489, 13770, 13967, 13984, 15761, 16195, 16739, 17106, 17220, 18155, 18804, 18983, 19628, 19883, 20824, 20872, 21415, 21707, 22237, 23175, 23241, 23296, 23307, 23328, 23720, 23730, 24110, 27296, 28423, 29689, 29776, 29779, 32863, 34177, 35362, 35597, 35747, 35754, 37366, 38438, 38548, 39443, 39626, 40906, 41248, 41271, 43455, 43757, 44483, 45113, 45472, 47242, 47272, 47555, 48316, 48354, 49287, 49288, 49720, 50509, 50827, 52816, 53367, 53390, 53940, 54060, 54297, 55726, 56065, 56312, 56417, 56946, 58513, 59499, 60202, ...], 7: [320, 638, 767, 1723, 3241, 3262, 3795, 3839, 4168, 4388, 4460, 4781, 4786, 5037, 5799, 5875, 6452, 7044, 7504, 8036, 8407, 8561, 9102, 9108, 9396, 9950, 10004, 10351, 10363, 10387, 11534, 12777, 12993, 12998, 13399, 13546, 13630, 13747, 13909, 13918, 13923, 13937, 14629, 14821, 14944, 14946, 15582, 15968, 16083, 16387, 16396, 16760, 17168, 17555, 17946, 18250, 18752, 19453, 19524, 20464, 20943, 21328, 21745, 21761, 21888, 22238, 22256, 23253, 24076, 24088, 24130, 24982, 25116, 25249, 25255, 25283, 25576, 26714, 26753, 27440, 27725, 27817, 27820, 27871, 28765, 29197, 29629, 29650, 29743, 29969, 31025, 31037, 31549, 32269, 32470, 32644, 34204, 34613, 35060, 35582, ...], 8: [142, 323, 1525, 1692, 1702, 1708, 1710, 1711, 1726, 2788, 2861, 2976, 3485, 3556, 3558, 3618, 3744, 3774, 3783, 3808, 4054, 4457, 4637, 4640, 5048, 5079, 5176, 5179, 5216, 5425, 5450, 5702, 5730, 5796, 6155, 6477, 6517, 7064, 7327, 7417, 7493, 7723, 7877, 8390, 8408, 8923, 9946, 9947, 10075, 10077, 10112, 10117, 10187, 10316, 10417, 11940, 12857, 13114, 13117, 13628, 13629, 13748, 13928, 14023, 14699, 14843, 14844, 14937, 14945, 15573, 15969, 16379, 16382, 16447, 16669, 16675, 16751, 17146, 17200, 18038, 18140, 18143, 18144, 18145, 18244, 18597, 18605, 19956, 20410, 20808, 20873, 20939, 20940, 21150, 21414, 22028, 22383, 22611, 23294, 24053, ...], 9: [75, 232, 1673, 1691, 1694, 1701, 1706, 1709, 1714, 1725, 1727, 3217, 3363, 3607, 3775, 3776, 3786, 4122, 4194, 4238, 4391, 4481, 4505, 4632, 4639, 4641, 4642, 5045, 5049, 5173, 5175, 5177, 5178, 5197, 5203, 5217, 5299, 5313, 5368, 5447, 5452, 5458, 5461, 5475, 5768, 5793, 7065, 7067, 7860, 8023, 8355, 8393, 8394, 8406, 8769, 8777, 9134, 9522, 9543, 9660, 9818, 9963, 10006, 10013, 10027, 10053, 10095, 10129, 10181, 10186, 10317, 10340, 10818, 12967, 13920, 13926, 13931, 14943, 15363, 15369, 15372, 15509, 15575, 16192, 16213, 16395, 16397, 16753, 16758, 17192, 17231, 17985, 18123, 18124, 18141, 18142, 18157, 18245, 18596, 18754, ...], 10: [292, 319, 639, 643, 800, 1327, 1689, 1693, 1712, 1713, 1719, 1721, 1722, 2773, 2791, 2799, 2978, 3198, 3263, 3435, 3648, 3718, 3747, 3772, 3833, 3987, 4068, 4069, 4072, 4254, 4421, 4455, 4477, 4479, 4771, 4929, 5071, 5171, 5172, 5181, 5194, 5198, 5199, 5201, 5202, 5204, 5205, 5369, 5448, 5459, 5472, 5482, 5762, 5763, 5769, 5770, 5792, 6158, 6212, 6479, 6511, 7051, 7066, 7406, 7475, 7488, 7867, 8005, 8007, 8134, 8142, 8379, 8423, 8943, 9290, 9392, 9544, 10015, 10063, 10064, 10069, 10155, 10160, 10184, 10207, 10342, 10350, 10369, 10377, 10422, 10566, 10660, 10662, 10700, 10960, 10964, 11609, 11610, 11942, 12848, ...], 11: [95, 248, 249, 335, 642, 1681, 1720, 2783, 2796, 3242, 3243, 3246, 3401, 3449, 3712, 3797, 3895, 4239, 4244, 4429, 4471, 4762, 4768, 5073, 5074, 5180, 5294, 5449, 5457, 5460, 5724, 5726, 5874, 7045, 7470, 7477, 8409, 8412, 9310, 9379, 9394, 10072, 10137, 10159, 10349, 10386, 10402, 10406, 10427, 10460, 10461, 14628, 14850, 14853, 14991, 15362, 15364, 15365, 15368, 15374, 15556, 15568, 15852, 16196, 16446, 16673, 16759, 16768, 17548, 17703, 17711, 17940, 17988, 17992, 18086, 18136, 19430, 19507, 19614, 19934, 20421, 20469, 21327, 21572, 21616, 21642, 21660, 21672, 21687, 22027, 22384, 22612, 23654, 24068, 24083, 24103, 24105, 24275, 24995, 25250, ...], 12: [229, 245, 246, 545, 1199, 1690, 1815, 2979, 3228, 3236, 3237, 3238, 3240, 3252, 3405, 3489, 3518, 3519, 4067, 4785, 4873, 4907, 5052, 5469, 5471, 7050, 7484, 7485, 8097, 8161, 8387, 8415, 8430, 8525, 8529, 9132, 9135, 9136, 9341, 9342, 9377, 10151, 10358, 10454, 10669, 11287, 13169, 13810, 13936, 15005, 15584, 16137, 16347, 16676, 16743, 17123, 17207, 17702, 19448, 19449, 19620, 19788, 19958, 20435, 21202, 21683, 22207, 22267, 22452, 23216, 23249, 23250, 23690, 24017, 24049, 24063, 24131, 24976, 25248, 25631, 25995, 26321, 26633, 29194, 31013, 31531, 34994, 35126, 35297, 35299, 35305, 35474, 35499, 35756, 35846, 35931, 36134, 36135, 36146, 36543, ...], 13: [1195, 3491, 3731, 3902, 4237, 4250, 4492, 5057, 5480, 5717, 6387, 6571, 8519, 8522, 8882, 8931, 9133, 10324, 10341, 10754, 14307, 15006, 15528, 16740, 17235, 17563, 18005, 18331, 18749, 20354, 21948, 22154, 23226, 23248, 23295, 23531, 24971, 25260, 26075, 26339, 26948, 27353, 27383, 27976, 32266, 33072, 35149, 35514, 35515, 35570, 35900, 37827, 37833, 38151, 38372, 39657, 39768, 40548, 40578, 40909, 41566, 42457, 42562, 43259, 43819, 43897, 44029, 46193, 47053, 47197, 47690, 47837, 48674, 48699, 48797, 49474, 49741, 49888, 50781, 53695, 53704, 54294, 56933, 57417, 58455, 58894, 59514, 59586, 60436, 61553, 61590, 62448, 62513, 62970, 63937, 64498, 65556, 65746, 68050, 68065, ...], 14: [3005, 3256, 3611, 3737, 4502, 5003, 5288, 5871, 6166, 6386, 8802, 8961, 9129, 10409, 10989, 11019, 13717, 13823, 14004, 14050, 17927, 18162, 18961, 19487, 20345, 20953, 21650, 23217, 23245, 23334, 24273, 24274, 24361, 24896, 25246, 25934, 28957, 31193, 35051, 35345, 35879, 35932, 36110, 38732, 38852, 39764, 40540, 40571, 42464, 42604, 43477, 44465, 44660, 44800, 45174, 46390, 47026, 47839, 48482, 48759, 49305, 49402, 49522, 50123, 50438, 51325, 52451, 52731, 52835, 53363, 54670, 54862, 56224, 58498, 62717, 62732, 62856, 62973, 64281, 64480, 65744, 67858, 67861, 69487, 70065, 70757, 73407, 74741, 76718, 77085, 77281, 77843, 79641, 81217, 81300, 83279, 83867, 83875, 84227, 84367, ...], 15: [63, 353, 3517, 3674, 4486, 5302, 7495, 7858, 7861, 8013, 8378, 8530, 8841, 8939, 9106, 9949, 10130, 10468, 11333, 13714, 13831, 14029, 15027, 15099, 15220, 17213, 17546, 17942, 18161, 18507, 20431, 20727, 22355, 25820, 26042, 26312, 26669, 26945, 29884, 32380, 32449, 34195, 35066, 35378, 35513, 35849, 36721, 36864, 36881, 36968, 38375, 38542, 39677, 40907, 42585, 43732, 46089, 47125, 49177, 49903, 50810, 50819, 50829, 51760, 52058, 52071, 52366, 52750, 53420, 53846, 54262, 56347, 56419, 56606, 57365, 57716, 58501, 58519, 59947, 62198, 62477, 62678, 63240, 63742, 63815, 65268, 65904, 66913, 67218, 67234, 68170, 71180, 71248, 72426, 73480, 73820, 74200, 74249, 75331, 77845, ...], 16: [225, 2716, 3037, 3487, 4247, 5038, 5072, 6433, 7141, 8977, 9311, 9464, 10116, 10456, 12067, 12900, 13118, 13911, 13956, 14992, 16105, 16211, 16393, 16399, 17966, 18134, 18803, 18933, 20944, 22184, 25607, 26086, 26324, 26642, 26876, 26921, 27047, 27428, 29344, 29987, 30122, 30560, 34430, 37345, 38128, 38374, 38541, 39128, 39306, 39419, 39659, 40022, 40797, 42587, 43176, 44018, 44105, 44786, 48225, 49524, 50106, 50344, 50980, 52072, 52403, 52743, 53360, 53384, 55366, 56357, 56831, 58930, 59008, 59526, 61382, 62168, 62271, 63394, 65354, 65363, 65726, 67107, 68415, 68564, 68815, 70538, 71224, 72177, 74604, 76710, 78895, 79930, 79958, 80557, 80839, 81004, 81670, 82111, 85062, 85123, ...], 17: [742, 835, 1678, 2800, 3441, 3551, 3574, 3796, 3848, 3860, 4064, 4243, 4322, 5877, 6480, 6487, 7500, 8420, 8432, 8807, 10179, 10339, 10378, 10459, 10693, 13603, 13624, 13731, 14006, 14021, 14861, 15366, 15561, 15988, 16082, 16702, 17097, 17237, 17962, 17975, 18088, 18131, 18137, 18645, 18734, 19102, 19549, 19939, 20945, 21326, 22032, 22380, 22381, 22552, 23335, 24100, 24899, 25628, 26063, 27734, 27761, 28513, 29764, 29770, 29773, 34198, 34400, 34415, 34418, 34697, 34832, 35033, 35755, 36035, 36143, 37386, 38304, 39363, 39366, 39595, 39711, 39750, 40542, 40570, 41241, 42031, 42667, 42869, 43163, 43316, 43373, 43894, 44127, 44657, 44697, 45196, 45372, 46183, 46457, 47080, ...], 18: [251, 536, 1700, 1703, 1717, 1718, 2619, 2782, 3437, 3528, 3893, 4133, 4408, 4456, 4772, 4787, 5026, 5047, 5170, 5182, 5191, 5200, 5206, 5300, 5301, 5455, 5464, 5869, 5987, 6216, 6462, 7405, 7471, 8400, 8894, 8909, 8921, 8945, 8954, 9051, 9189, 9860, 10111, 10139, 10348, 10362, 10381, 10390, 10393, 10426, 10462, 10469, 11191, 13703, 13728, 13930, 14022, 14822, 16119, 17125, 17127, 17351, 17710, 17928, 17990, 18590, 18592, 18607, 18745, 19450, 19454, 19523, 20429, 20455, 20823, 20875, 21621, 21656, 21659, 21705, 23303, 23306, 23423, 23425, 23538, 23939, 24475, 25709, 25759, 26021, 26072, 26663, 26735, 27053, 27338, 27874, 27883, 28876, 29269, 32704, ...], 19: [73, 250, 256, 1664, 1704, 1707, 1715, 1793, 1810, 2726, 2776, 2777, 2779, 3247, 3253, 3266, 3647, 3721, 3723, 3726, 3727, 3736, 3754, 3777, 3779, 3847, 3849, 3852, 3894, 4032, 4048, 4200, 4458, 4459, 4472, 4638, 4763, 4776, 4850, 4877, 5027, 5043, 5044, 5051, 5055, 5188, 5298, 5365, 5453, 5470, 5864, 5873, 5986, 6461, 7069, 7072, 7143, 7476, 7478, 7494, 7855, 7859, 8326, 8413, 8431, 8435, 8451, 8805, 8806, 8877, 8920, 8983, 9048, 9378, 9390, 9391, 10029, 10054, 10068, 10140, 10156, 10338, 10401, 10403, 10429, 10696, 10817, 11049, 12473, 12480, 13119, 13813, 13900, 13919, 13929, 13932, 14003, 14018, 14026, 14217, ...], 20: [93, 252, 727, 765, 1665, 1680, 1903, 2544, 2775, 2778, 2790, 2794, 2798, 3248, 3258, 3261, 3400, 3406, 3432, 3446, 3492, 3500, 3501, 3575, 3664, 3698, 3778, 3780, 3837, 3850, 3851, 3889, 4071, 4075, 4086, 4099, 4111, 4334, 4462, 4473, 4476, 4483, 4748, 5054, 5058, 5161, 5183, 5184, 5186, 5189, 5190, 5192, 5193, 5195, 5196, 5454, 5462, 5463, 5465, 5467, 6159, 6168, 6489, 7048, 7075, 7328, 7346, 7408, 7473, 7487, 8052, 8323, 8391, 8392, 8401, 8419, 8421, 8427, 8521, 8910, 8936, 8941, 8973, 9199, 9336, 9340, 9343, 9387, 10066, 10070, 10128, 10157, 10158, 10239, 10319, 10323, 10394, 10395, 10400, 10418, ...], 21: [330, 1536, 1687, 2727, 2772, 2780, 2789, 2792, 3230, 3239, 3359, 3390, 3499, 3555, 3589, 3663, 3719, 3758, 3835, 4074, 4240, 4245, 4484, 4507, 5056, 5168, 5174, 5456, 5466, 5795, 5798, 5985, 6488, 7480, 7481, 7857, 8031, 8380, 8386, 8417, 8433, 8434, 8558, 8908, 8911, 8916, 8932, 8938, 8949, 8950, 9057, 9393, 9466, 9750, 9817, 10167, 10322, 10343, 10346, 10347, 10359, 10382, 10419, 10644, 10729, 10967, 11187, 11192, 12024, 12417, 13977, 14225, 14306, 14847, 15558, 16097, 16121, 16135, 16157, 16428, 16430, 16431, 16738, 16764, 16878, 17388, 18015, 18016, 18138, 18818, 19428, 19451, 19499, 19782, 20034, 20342, 20420, 20423, 20433, 21211, ...], 22: [2590, 2620, 2781, 3006, 3039, 3383, 3495, 3516, 4070, 4407, 4498, 4876, 4906, 5468, 5481, 5867, 5966, 6460, 6466, 7497, 8116, 8397, 8803, 8885, 8915, 9204, 9211, 9375, 9757, 9836, 10018, 10416, 11161, 11183, 13227, 14042, 14285, 15007, 15977, 16088, 16386, 16449, 16761, 17196, 17554, 18727, 18854, 19490, 19779, 20413, 20422, 21154, 21666, 22554, 23223, 23336, 23535, 23989, 24136, 24472, 25225, 25707, 25720, 26030, 26076, 26077, 26097, 26489, 27347, 29950, 32584, 32701, 34586, 34817, 35072, 35505, 35506, 35512, 35601, 37356, 37360, 37832, 38084, 38314, 38995, 39453, 39473, 39775, 40070, 40573, 40579, 42491, 42495, 42600, 43762, 43994, 44402, 44658, 45170, 46187, ...], 23: [331, 354, 455, 1388, 2589, 2621, 3029, 3255, 3269, 3341, 3385, 3443, 3512, 3514, 3725, 3910, 4423, 4500, 4874, 5031, 5718, 5751, 6458, 6463, 6465, 6468, 8896, 8904, 8942, 9370, 9705, 10204, 10408, 10415, 10453, 10807, 11028, 13604, 13839, 15982, 16132, 16687, 16744, 18852, 18946, 18953, 19101, 21619, 21686, 23221, 23463, 23920, 24019, 24137, 24251, 24897, 24901, 25700, 28024, 28939, 29728, 33582, 34018, 34532, 35349, 37350, 37355, 38343, 38997, 39837, 39950, 40068, 40538, 40541, 40553, 40883, 40912, 41443, 42493, 43191, 43449, 43463, 44150, 44830, 45841, 45855, 46177, 46189, 48323, 48766, 49403, 49648, 49768, 50760, 50778, 50814, 52016, 52349, 53505, 53697, ...], 24: [234, 355, 1321, 1984, 2584, 3355, 3626, 4685, 6493, 7336, 7915, 8905, 8975, 9362, 9367, 9758, 10396, 10813, 13985, 16136, 17120, 17170, 18044, 18218, 19465, 19618, 19959, 21053, 23330, 23835, 23948, 24020, 24070, 26618, 27302, 27767, 30218, 31194, 32617, 33618, 34823, 35394, 35864, 37953, 38083, 38339, 38990, 39307, 41068, 42496, 43598, 43607, 44147, 44672, 47843, 48799, 50329, 50578, 50691, 50796, 50808, 52734, 52817, 53389, 53537, 54781, 56875, 58522, 59355, 59525, 60019, 61598, 62108, 62129, 62303, 63803, 63947, 64672, 65708, 66050, 66871, 67864, 67895, 68013, 69301, 69945, 71239, 73695, 74009, 75508, 75760, 78680, 79718, 79767, 81294, 81589, 82142, 82540, 82804, 82917, ...], 25: [236, 1466, 2320, 2622, 3043, 3836, 3890, 4196, 4788, 7047, 7074, 7990, 8849, 9067, 9252, 10198, 10793, 10825, 13000, 13440, 13682, 14034, 14892, 16080, 16228, 16405, 17397, 18089, 18725, 18833, 19954, 21671, 22264, 23443, 23483, 23831, 23840, 24007, 24091, 27362, 29716, 29854, 30140, 31702, 32200, 32476, 36727, 37351, 37896, 38876, 41217, 41290, 41471, 42853, 43478, 43826, 43847, 44304, 44335, 44888, 46372, 46465, 47223, 47238, 47276, 47532, 49289, 49453, 49526, 49735, 50775, 51469, 51472, 53592, 54035, 54124, 54731, 56665, 56885, 58177, 58395, 58951, 59453, 61195, 61697, 61712, 62176, 62319, 65351, 66845, 66880, 67876, 70028, 70144, 71247, 74600, 74929, 76099, 76717, 77113, ...], 26: [1633, 2618, 3063, 3286, 3728, 4049, 4643, 6490, 7461, 7483, 8024, 8780, 9137, 9380, 13607, 14964, 16273, 17129, 17156, 18320, 19103, 21199, 21461, 21574, 21668, 21670, 22395, 22651, 23232, 23292, 23310, 23337, 23428, 23729, 24031, 25760, 25871, 26069, 26729, 28870, 29398, 29713, 29875, 30467, 30512, 31040, 31082, 31192, 31750, 32161, 34778, 36355, 39368, 39440, 39597, 39786, 40543, 40908, 41066, 41901, 43173, 44663, 46195, 46273, 47320, 48369, 48685, 49206, 49436, 49479, 49928, 51355, 51475, 53561, 53694, 56104, 58687, 59197, 59352, 61721, 62245, 62247, 62453, 63322, 64241, 64771, 65255, 67098, 68319, 68436, 69227, 69771, 70516, 70529, 71210, 71532, 72679, 74549, 74723, 74981, ...], 27: [1387, 1675, 1688, 3358, 3436, 3490, 3610, 4267, 4475, 5011, 5050, 5167, 5989, 6172, 6459, 6512, 7856, 7862, 8414, 8429, 8524, 9219, 9383, 9535, 10163, 10227, 10321, 10364, 10654, 10819, 11535, 13736, 13802, 13899, 13902, 14131, 14454, 14848, 14863, 14884, 15261, 15915, 16133, 16432, 16564, 16763, 17078, 17564, 18032, 18598, 18737, 18892, 21209, 21576, 21713, 22205, 22330, 22508, 22640, 23293, 23327, 23440, 23727, 24039, 24102, 24364, 25271, 25272, 26711, 31697, 31993, 32173, 34424, 35143, 39436, 40027, 42418, 43170, 43199, 43724, 44375, 44679, 46986, 47017, 47557, 47834, 48237, 49531, 50502, 50588, 50830, 50950, 51328, 52038, 52067, 52326, 52398, 52829, 53365, 53514, ...], 28: [94, 452, 1716, 2094, 2569, 3439, 3481, 3581, 3722, 3784, 3888, 4633, 4735, 4764, 4920, 5046, 6519, 7419, 8090, 8843, 8893, 8906, 9054, 9376, 10062, 10361, 10458, 10645, 10814, 12875, 12997, 13447, 13785, 14020, 14184, 14222, 14621, 15978, 16138, 16429, 17098, 17154, 17155, 17862, 18003, 18040, 18604, 19612, 20874, 21662, 22352, 22633, 23181, 23421, 23453, 23680, 24044, 24064, 24079, 24089, 26016, 26029, 26082, 26573, 26741, 26759, 27770, 27826, 27892, 27940, 28786, 31606, 32305, 34075, 34163, 34796, 35042, 35493, 36104, 37954, 38317, 38371, 38887, 38905, 39635, 42194, 42229, 43157, 43159, 43164, 43257, 43597, 43604, 43675, 43895, 43907, 44024, 44048, 44079, 44132, ...], 29: [255, 766, 987, 1686, 2698, 2862, 3232, 3235, 3365, 3403, 3404, 3438, 3498, 3597, 3710, 3785, 3834, 3891, 4066, 4176, 4467, 4480, 5029, 5153, 5187, 5443, 5868, 6167, 6464, 6570, 7460, 7472, 7474, 7482, 7486, 7491, 7863, 8117, 8422, 8974, 9055, 9104, 9339, 9384, 9388, 9389, 9504, 9521, 9555, 9894, 9974, 10030, 10031, 10074, 10138, 10337, 10380, 10384, 10385, 10388, 10391, 10392, 10397, 10399, 10404, 10407, 10466, 10668, 13605, 13606, 13729, 13803, 13898, 13976, 14024, 1402

In [13]:
df_grouped = df.groupby([' Humi', 'WindBe'])

In [14]:
idx = 0
for group, data in df_grouped:
    print(group)
    print(data)
    if idx == 100:
        break
    idx += 1

(0.0, 0)
        Humi   WindSp  WindBe   Visi    Pres       Temp
54858    0.0      0.0       0  2.576  1034.4 -15.000000
55473    0.0      0.0       0  1.771  1035.7 -16.111111
55511    0.0      0.0       0  1.449  1030.6 -17.777778
(0.0, 12)
        Humi   WindSp  WindBe   Visi     Pres      Temp
19958    0.0   4.4275      12  9.982  1043.04 -1.111111
(0.0, 20)
        Humi   WindSp  WindBe    Visi    Pres       Temp
54870    0.0    11.27      20   7.084  1029.9 -16.111111
55086    0.0    11.27      20   9.982  1027.6 -12.777778
55088    0.0    11.27      20   9.982  1028.1 -12.777778
55352    0.0    22.54      20  11.270  1029.7 -12.222222
(0.0, 30)
        Humi   WindSp  WindBe   Visi    Pres       Temp
54872    0.0    14.49      30  9.982  1029.8 -15.000000
55349    0.0    17.71      30  9.982  1030.0 -12.222222
55350    0.0    20.93      30  9.982  1029.4 -12.222222
(0.0, 40)
        Humi   WindSp  WindBe   Visi    Pres       Temp
54873    0.0    11.27      40  9.982  1029.9 -13.888889
(0.0, 160)
        Humi   WindSp  WindBe   Visi    Pres       Temp
28103    0.0     6.44     160  9.982  1015.9 -15.555556
28110    0.0    22.54     160  9.982  1016.8 -13.888889
(0.0, 180)
        Humi   WindSp  WindBe   Visi    Pres       Temp
55481    0.0     4.83     180  9.982  1036.0 -12.777778
55508    0.0     8.05     180  4.025  1029.4 -16.111111
(0.0, 190)
        Humi   WindSp  WindBe   Visi    Pres       Temp
55472    0.0     3.22     190  0.805  1035.0 -17.777778
(0.0, 200)
        Humi   WindSp  WindBe   Visi    Pres       Temp
55469    0.0     4.83     200  1.932  1033.9 -17.777778
(0.0, 220)
        Humi   WindSp  WindBe   Visi    Pres       Temp
54840    0.0     3.22     220  3.059  1030.8 -15.555556
(0.0, 250)
        Humi   WindSp  WindBe   Visi    Pres   Temp
28101    0.0     3.22     250  9.982  1015.1  -15.0
(0.0, 320)
        Humi   WindSp  WindBe   Visi    Pres       Temp
55412    0.0     8.05     320  2.576  1032.2 -17.777778
(0.0, 350)
        Humi   WindSp  WindBe   Visi    Pres      Temp
29627    0.0    20.93     350  0.161  1000.1  1.111111
(0.12, 10)
        Humi   WindSp  WindBe   Visi    Pres       Temp
58164   0.12    28.98      10  9.982  1028.0  13.888889
(0.13, 250)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12759   0.13  23.5865     250  9.982  1007.55  39.905556
(0.14, 0)
        Humi   WindSp  WindBe   Visi    Pres   Temp
58166   0.14    20.93       0  9.982  1027.7   15.0
(0.14, 153)
        Humi   WindSp  WindBe     Visi     Pres       Temp
12713   0.14  10.5938     153  10.3523  1011.77  38.788889
(0.14, 167)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12711   0.14   12.719     167  9.982  1012.34  38.983333
(0.14, 210)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12615   0.14  17.4202     210  9.982  1015.04  37.777778
(0.15, 0)
        Humi   WindSp  WindBe     Visi     Pres      Temp
68411   0.15  30.6705       0  10.2557  1019.73  2.733333
(0.15, 20)
        Humi   WindSp  WindBe  Visi     Pres      Temp
68422   0.15   34.293      20  16.1  1021.51  1.133333
(0.15, 128)
       Humi   WindSp  WindBe   Visi     Pres       Temp
9160   0.15   5.2969     128  9.982  1022.73  21.205556
(0.15, 133)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12712   0.15  15.4077     133  9.982  1011.93  38.983333
(0.15, 198)
       Humi   WindSp  WindBe     Visi     Pres       Temp
9161   0.15   2.5921     198  10.3523  1022.38  21.244444
(0.15, 221)
        Humi   WindSp  WindBe     Visi     Pres       Temp
12616   0.15  17.2592     221  15.8263  1014.83  37.822222
(0.15, 230)
        Humi   WindSp  WindBe   Visi     Pres   Temp
12757   0.15  21.8799     230  9.982  1008.74  38.75
(0.15, 249)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12760   0.15  23.7475     249  9.982  1007.26  38.838889
(0.15, 283)
        Humi   WindSp  WindBe     Visi     Pres       Temp
12737   0.15  12.2038     283  10.3523  1010.24  39.588889
(0.15, 351)
        Humi   WindSp  WindBe     Visi     Pres       Temp
58165   0.15  25.4541     351  10.3684  1027.89  14.844444
(0.16, 20)
        Humi   WindSp  WindBe   Visi    Pres       Temp
58163   0.16    28.98      20  9.982  1027.8  12.777778
(0.16, 179)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12714   0.16   9.6922     179  9.982  1011.52  37.894444
(0.16, 219)
        Humi   WindSp  WindBe     Visi     Pres       Temp
12758   0.16  24.5042     219  10.3523  1008.38  38.472222
(0.16, 220)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12756   0.16  25.1643     220  9.982  1008.96  37.711111
(0.16, 232)
        Humi   WindSp  WindBe     Visi     Pres       Temp
12761   0.16  17.4202     232  10.3523  1006.93  38.633333
(0.16, 243)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12762   0.16  13.3952     243  9.982  1006.38  37.727778
(0.16, 280)
        Humi   WindSp  WindBe   Visi    Pres       Temp
58190   0.16    24.15     280  9.982  1023.2  16.111111
(0.16, 297)
        Humi   WindSp  WindBe   Visi     Pres   Temp
12738   0.16   9.3863     297  9.982  1009.89   37.8
(0.17, 20)
        Humi   WindSp  WindBe   Visi    Pres   Temp
58167   0.17    17.71      20  9.982  1027.4   15.0
(0.17, 141)
        Humi   WindSp  WindBe   Visi     Pres       Temp
53920   0.17  21.6706     141  9.982  1010.68  33.905556
(0.17, 149)
        Humi   WindSp  WindBe     Visi     Pres       Temp
53918   0.17  19.8352     149  10.3523  1011.83  33.672222
(0.17, 173)
        Humi   WindSp  WindBe     Visi     Pres       Temp
12665   0.17   9.1126     173  10.3523  1013.18  38.716667
(0.17, 202)
        Humi   WindSp  WindBe     Visi     Pres       Temp
12617   0.17  15.0535     202  10.3523  1014.69  37.522222
(0.17, 203)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12618   0.17  14.1358     203  9.982  1014.52  37.266667
(0.17, 207)
        Humi   WindSp  WindBe     Visi     Pres       Temp
12614   0.17  19.4327     207  10.3523  1015.87  36.972222
(0.17, 210)
        Humi   WindSp  WindBe   Visi    Pres       Temp
52888   0.17    24.15     210  9.982  1011.8  16.111111
(0.17, 213)
        Humi   WindSp  WindBe     Visi     Pres       Temp
53680   0.17   9.5151     213  11.2056  1013.02  37.727778
(0.17, 230)
        Humi   WindSp  WindBe   Visi    Pres       Temp
52887   0.17    24.15     230  9.982  1012.6  16.111111
(0.17, 242)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12806   0.17  32.3771     242  9.982  1003.18  38.438889
(0.17, 251)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12807   0.17  27.7242     251  9.982  1002.81  38.700000
53679   0.17  11.1895     251  9.982  1013.70  37.727778
(0.17, 270)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12739   0.17   9.4185     270  9.982  1009.89  37.194444
(0.17, 310)
       Humi   WindSp  WindBe   Visi     Pres       Temp
9157   0.17   2.8014     310  9.982  1025.13  20.072222
(0.18, 0)
        Humi   WindSp  WindBe   Visi    Pres       Temp
57807   0.18    25.76       0  9.982  1018.7  11.111111
(0.18, 6)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12880   0.18   5.0554       6  9.982  1014.18  32.244444
(0.18, 8)
        Humi   WindSp  WindBe     Visi     Pres       Temp
58168   0.18  22.4434       8  10.3684  1027.01  15.016667
(0.18, 29)
        Humi   WindSp  WindBe  Visi     Pres       Temp
75300   0.18  17.2753      29  16.1  1024.41  15.022222
(0.18, 56)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12879   0.18  10.5455      56  9.982  1014.77  32.222222
(0.18, 121)
        Humi   WindSp  WindBe  Visi    Pres       Temp
62802   0.18   5.2164     121  16.1  1013.2  36.083333
(0.18, 131)
        Humi   WindSp  WindBe     Visi     Pres       Temp
53919   0.18  21.5257     131   9.9820  1011.17  33.883333
53921   0.18  19.3683     131  10.3523  1010.72  32.733333
(0.18, 160)
        Humi   WindSp  WindBe   Visi     Pres       Temp
53917   0.18  21.5418     160  9.982  1012.27  32.777778
(0.18, 172)
       Humi   WindSp  WindBe   Visi    Pres       Temp
9162   0.18   3.6708     172  9.982  1021.7  20.161111
(0.18, 175)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12664   0.18   8.9355     175  9.982  1013.34  38.983333
(0.18, 189)
        Humi   WindSp  WindBe     Visi     Pres       Temp
12710   0.18  12.8478     189  10.3523  1012.77  38.766667
(0.18, 200)
        Humi   WindSp  WindBe   Visi    Pres       Temp
57927   0.18    17.71     200  9.982  1022.0  22.777778
(0.18, 222)
        Humi   WindSp  WindBe   Visi    Pres       Temp
12804   0.18  21.8477     222  9.982  1004.2  37.566667
(0.18, 231)
        Humi   WindSp  WindBe   Visi    Pres       Temp
12805   0.18  29.0122     231  9.982  1003.9  37.588889
(0.18, 232)
        Humi   WindSp  WindBe   Visi     Pres       Temp
53727   0.18   17.388     232  9.982  1009.89  38.861111
(0.18, 241)
        Humi   WindSp  WindBe     Visi     Pres       Temp
53753   0.18  12.5419     241  10.3523  1009.36  37.027778
(0.18, 245)
        Humi   WindSp  WindBe     Visi     Pres       Temp
53729   0.18  12.6707     245  10.3523  1009.15  38.633333
(0.18, 250)
        Humi   WindSp  WindBe   Visi     Pres       Temp
53728   0.18  12.9444     250  9.982  1009.38  38.838889
(0.18, 260)
        Humi   WindSp  WindBe   Visi     Pres       Temp
53703   0.18   9.3219     260  9.982  1012.08  37.611111
(0.18, 286)
        Humi   WindSp  WindBe     Visi     Pres       Temp
58189   0.18  23.3933     286  10.3684  1024.85  15.905556
(0.18, 288)
        Humi   WindSp  WindBe   Visi    Pres       Temp
12733   0.18  10.9641     288  9.982  1011.8  37.688889
(0.18, 301)
        Humi   WindSp  WindBe  Visi     Pres       Temp
79693   0.18   2.6887     301  16.1  1012.21  34.927778
(0.18, 320)
        Humi   WindSp  WindBe   Visi    Pres       Temp
31242   0.18    28.98     320  9.982  1005.6  22.777778
58145   0.18    22.54     320  9.982  1019.5  20.000000
(0.18, 326)
        Humi   WindSp  WindBe     Visi     Pres       Temp
58144   0.18  22.3307     326  10.3684  1019.83  21.111111
(0.19, 0)
        Humi   WindSp  WindBe   Visi    Pres       Temp
58095   0.19    11.27       0  9.982  1023.9  22.222222
(0.19, 4)
        Humi   WindSp  WindBe  Visi     Pres       Temp
79716   0.19   9.3058       4  16.1  1014.02  37.105556
(0.19, 13)
        Humi   WindSp  WindBe   Visi     Pres       Temp
53704   0.19   3.1556      13  9.982  1011.59  37.566667
(0.19, 24)
        Humi   WindSp  WindBe     Visi     Pres       Temp
79718   0.19   8.7906      24  15.5526  1013.46  36.955556
(0.19, 51)
        Humi   WindSp  WindBe  Visi     Pres       Temp
79717   0.19   9.4507      51  16.1  1013.61  37.194444
(0.19, 78)
        Humi   WindSp  WindBe  Visi     Pres       Temp
79669   0.19   4.5724      78  16.1  1012.98  33.861111
(0.19, 81)
        Humi   WindSp  WindBe   Visi     Pres       Temp
14895   0.19   8.5974      81  9.982  1019.01  16.177778
(0.19, 105)
        Humi   WindSp  WindBe     Visi     Pres       Temp
62801   0.19   7.6958     105  15.5526  1013.46  36.066667
(0.19, 120)
       Humi   WindSp  WindBe   Visi     Pres       Temp
9156   0.19    12.88     120  9.982  1025.73  18.961111
(0.19, 159)
        Humi   WindSp  WindBe  Visi     Pres       Temp
78949   0.19   9.9176     159  16.1  1026.36  18.933333
(0.19, 172)
        Humi   WindSp  WindBe     Visi     Pres       Temp
78950   0.19  12.1877     172  15.5526  1025.88  18.927778
(0.19, 173)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12663   0.19   8.7906     173  9.982  1013.76  37.894444
(0.19, 183)
        Humi   WindSp  WindBe   Visi     Pres       Temp
12666   0.19  10.4972     183  9.982  1012.66  37.894444
(0.19, 187)
        Humi   WindSp  WindBe     Visi     Pres       Temp
12662   0.19   8.9355     187  10.3523  1014.38  38.705556
(0.19, 207)
        Humi   WindSp  WindBe  Visi     Pres       Temp
78948   0.19  13.8299     207  16.1  1027.16  18.911111
(0.19, 209)
        Humi   WindSp  WindBe     Visi     Pres       Temp
57928   0.19  15.9229     209  10.3684  1021.39  21.961111
(0.19, 211)
        Humi   WindSp  WindBe   Visi     Pres       Temp
53730   0.19  12.4936     211  9.982  1008.78  37.244444
(0.19, 218)
        Humi   WindSp  WindBe     Visi     Pres       Temp
52886   0.19  24.3593     218  10.9319  1013.52  14.844444
(0.19, 220)
        Humi   WindSp  WindBe     Visi     Pres       Temp
26247   0.19  25.2931     220  11.2056  1011.69  36.016667
26248   0.19  23.7153     220   9.9820  1011.10  36.016667
(0.19, 221)
        Humi   WindSp  WindBe   Visi    Pres       Temp
12613   0.19  12.9283     221  9.982  1016.2  37.222222
(0.19, 230)
        Humi   WindSp  WindBe   Visi     Pres   Temp
26272   0.19  15.7136     230  9.982  1010.42  37.15
(0.19, 249)
        Humi   WindSp  WindBe   Visi     Pres   Temp
26271   0.19  20.2699     249  9.982  1010.55  37.15
(0.19, 260)
        Humi   WindSp  WindBe   Visi    Pres       Temp
53658   0.19   0.6118     260  9.982  1014.8  36.083333
(0.19, 262)
        Humi   WindSp  WindBe     Visi     Pres       Temp
53681   0.19   9.8371     262  10.3523  1012.81  37.155556
(0.19, 270)
        Humi   WindSp  WindBe   Visi    Pres       Temp
58044   0.19     16.1     270  9.982  1034.2  17.777778
(0.19, 272)
        Humi   WindSp  WindBe   Visi     Pres   Temp
12734   0.19  11.4149     272  9.982  1011.43   38.5

In [19]:
df_grouped.sum()

                WindSp     Visi      Pres       Temp
 Humi WindBe
0.0   0         0.0000   5.7960   3100.70 -48.888889
      12        4.4275   9.9820   1043.04  -1.111111
      20       56.3500  38.3180   4115.30 -53.888889
      30       53.1300  29.9460   3089.20 -39.444444
      40       11.2700   9.9820   1029.90 -13.888889
...                ...      ...       ...        ...
1.0   355       3.1717   3.9284   1019.31   1.738889
      356      20.0123   5.9248   4087.58  10.588889
      357      19.9479  13.0732   3068.66   7.933333
      358      11.0285   7.9534   3049.44   0.022222
      359     145.2381  59.1031  15256.63  95.700000

[22001 rows x 4 columns]

In [20]:
df_grouped.agg(['mean', 'sum', 'std'])

                 WindSp                          Visi                     \
                   mean       sum       std      mean      sum       std
 Humi WindBe
0.0   0        0.000000    0.0000  0.000000  1.932000   5.7960  0.580494
      12       4.427500    4.4275       NaN  9.982000   9.9820       NaN
      20      14.087500   56.3500  5.635000  9.579500  38.3180  1.771000
      30      17.710000   53.1300  3.220000  9.982000  29.9460  0.000000
      40      11.270000   11.2700       NaN  9.982000   9.9820       NaN
...                 ...       ...       ...       ...      ...       ...
1.0   355      3.171700    3.1717       NaN  3.928400   3.9284       NaN
      356      5.003075   20.0123  4.331975  1.481200   5.9248  1.830403
      357      6.649300   19.9479  6.373425  4.357733  13.0732  1.699014
      358      3.676167   11.0285  1.970678  2.651133   7.9534  1.553073
      359      9.682540  145.2381  3.282115  3.940207  59.1031  4.188492

                     Pres                            Temp
                     mean       sum        std       mean        sum       std
 Humi WindBe
0.0   0       1033.566667   3100.70   2.650157 -16.296296 -48.888889  1.398117
      12      1043.040000   1043.04        NaN  -1.111111  -1.111111       NaN
      20      1028.825000   4115.30   1.147098 -13.472222 -53.888889  1.778646
      30      1029.733333   3089.20   0.305505 -13.148148 -39.444444  1.603751
      40      1029.900000   1029.90        NaN -13.888889 -13.888889       NaN
...                   ...       ...        ...        ...        ...       ...
1.0   355     1019.310000   1019.31        NaN   1.738889   1.738889       NaN
      356     1021.895000   4087.58  11.392455   2.647222  10.588889  1.271065
      357     1022.886667   3068.66  11.180493   2.644444   7.933333  5.553702
      358     1016.480000   3049.44  16.862215   0.007407   0.022222  2.211120
      359     1017.108667  15256.63   9.179232   6.380000  95.700000  7.713492

[22001 rows x 12 columns]

In [48]:
df_sn = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_SomeNull.csv')
df_sn = df_sn.iloc[0 : 5]
df_sn.interpolate('polynomial', order = 2, inplace = True)
df_sn['WindBe'] = df_sn['WindBe'].astype(int)
df_sn.bfill(inplace = True)
df_sn.head()

    Humi   WindSp  WindBe      Visi     Pres      Temp
0   0.89  14.2646     251  15.82630  1015.13  9.472222
1   0.86  14.2646     259  15.17425  1015.63  8.647222
2   0.84   3.9284     204  14.95690  1015.94  8.252778
3   0.83  14.1036     197  15.17425  1016.41  8.288889
4   0.83  11.0446     259  15.82630  1016.51  8.755556

In [49]:
df_nn = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_NotAnyNull.csv')
df_nn = df_nn.iloc[0 : 5]
df_nn.head()

    Humi   WindSp  WindBe     Visi     Pres      Temp
0   0.89  14.1197     251  15.8263  1015.13  9.472222
1   0.86  14.2646     259  15.8263  1015.63  9.355556
2   0.89   3.9284     204  14.9569  1015.94  9.377778
3   0.83  14.1036     269  15.8263  1016.41  8.288889
4   0.83  11.0446     259  15.8263  1016.51  8.755556

In [50]:
pd.merge(df_sn, df_nn, on = 'WindBe')

,Humi_x,WindSp_x,WindBe,Visi_x,Pres_x,Temp_x,Humi_y,WindSp_y,Visi_y,Pres_y,Temp_y
0,0.89,14.2646,251,15.82630,1015.13,9.472222,0.89,14.1197,15.8263,1015.13,9.472222
1,0.86,14.2646,259,15.17425,1015.63,8.647222,0.86,14.2646,15.8263,1015.63,9.355556
2,0.86,14.2646,259,15.17425,1015.63,8.647222,0.83,11.0446,15.8263,1016.51,8.755556
3,0.84,3.9284,204,14.95690,1015.94,8.252778,0.89,3.9284,14.9569,1015.94,9.377778
4,0.83,11.0446,259,15.82630,1016.51,8.755556,0.86,14.2646,15.8263,1015.63,9.355556
5,0.83,11.0446,259,15.82630,1016.51,8.755556,0.83,11.0446,15.8263,1016.51,8.755556

In [52]:
pd.merge(df_sn, df_nn, on = 'WindBe', how = 'right')

,Humi_x,WindSp_x,WindBe,Visi_x,Pres_x,Temp_x,Humi_y,WindSp_y,Visi_y,Pres_y,Temp_y
0,0.89,14.2646,251,15.82630,1015.13,9.472222,0.89,14.1197,15.8263,1015.13,9.472222
1,0.86,14.2646,259,15.17425,1015.63,8.647222,0.86,14.2646,15.8263,1015.63,9.355556
2,0.83,11.0446,259,15.82630,1016.51,8.755556,0.86,14.2646,15.8263,1015.63,9.355556
3,0.84,3.9284,204,14.95690,1015.94,8.252778,0.89,3.9284,14.9569,1015.94,9.377778
4,NaN,NaN,269,NaN,NaN,NaN,0.83,14.1036,15.8263,1016.41,8.288889
5,0.86,14.2646,259,15.17425,1015.63,8.647222,0.83,11.0446,15.8263,1016.51,8.755556
6,0.83,11.0446,259,15.82630,1016.51,8.755556,0.83,11.0446,15.8263,1016.51,8.755556

In [55]:
pd.merge(df_sn, df_nn, on = 'WindBe', how = 'right', indicator = True)

,Humi_x,WindSp_x,WindBe,Visi_x,Pres_x,Temp_x,Humi_y,WindSp_y,Visi_y,Pres_y,Temp_y,_merge
0,0.89,14.2646,251,15.82630,1015.13,9.472222,0.89,14.1197,15.8263,1015.13,9.472222,both
1,0.86,14.2646,259,15.17425,1015.63,8.647222,0.86,14.2646,15.8263,1015.63,9.355556,both
2,0.83,11.0446,259,15.82630,1016.51,8.755556,0.86,14.2646,15.8263,1015.63,9.355556,both
3,0.84,3.9284,204,14.95690,1015.94,8.252778,0.89,3.9284,14.9569,1015.94,9.377778,both
4,NaN,NaN,269,NaN,NaN,NaN,0.83,14.1036,15.8263,1016.41,8.288889,right_only
5,0.86,14.2646,259,15.17425,1015.63,8.647222,0.83,11.0446,15.8263,1016.51,8.755556,both
6,0.83,11.0446,259,15.82630,1016.51,8.755556,0.83,11.0446,15.8263,1016.51,8.755556,both

In [57]:
pd.merge(df_sn, df_nn, on = 'WindBe', how = 'right', indicator = True, suffixes = ['_First', '_Second'])

,Humi_First,WindSp_First,WindBe,Visi_First,Pres_First,Temp_First,Humi_Second,WindSp_Second,Visi_Second,Pres_Second,Temp_Second,_merge
0,0.89,14.2646,251,15.82630,1015.13,9.472222,0.89,14.1197,15.8263,1015.13,9.472222,both
1,0.86,14.2646,259,15.17425,1015.63,8.647222,0.86,14.2646,15.8263,1015.63,9.355556,both
2,0.83,11.0446,259,15.82630,1016.51,8.755556,0.86,14.2646,15.8263,1015.63,9.355556,both
3,0.84,3.9284,204,14.95690,1015.94,8.252778,0.89,3.9284,14.9569,1015.94,9.377778,both
4,NaN,NaN,269,NaN,NaN,NaN,0.83,14.1036,15.8263,1016.41,8.288889,right_only
5,0.86,14.2646,259,15.17425,1015.63,8.647222,0.83,11.0446,15.8263,1016.51,8.755556,both
6,0.83,11.0446,259,15.82630,1016.51,8.755556,0.83,11.0446,15.8263,1016.51,8.755556,both

In [58]:
pd.concat([df_sn, df_nn])

    Humi   WindSp  WindBe      Visi     Pres      Temp
0   0.89  14.2646     251  15.82630  1015.13  9.472222
1   0.86  14.2646     259  15.17425  1015.63  8.647222
2   0.84   3.9284     204  14.95690  1015.94  8.252778
3   0.83  14.1036     197  15.17425  1016.41  8.288889
4   0.83  11.0446     259  15.82630  1016.51  8.755556
0   0.89  14.1197     251  15.82630  1015.13  9.472222
1   0.86  14.2646     259  15.82630  1015.63  9.355556
2   0.89   3.9284     204  14.95690  1015.94  9.377778
3   0.83  14.1036     269  15.82630  1016.41  8.288889
4   0.83  11.0446     259  15.82630  1016.51  8.755556

In [59]:
pd.concat([df_sn, df_nn], axis = 1)

,Humi,WindSp,WindBe,Visi,Pres,Temp,Humi,WindSp,WindBe,Visi,Pres,Temp
0,0.89,14.2646,251,15.82630,1015.13,9.472222,0.89,14.1197,251,15.8263,1015.13,9.472222
1,0.86,14.2646,259,15.17425,1015.63,8.647222,0.86,14.2646,259,15.8263,1015.63,9.355556
2,0.84,3.9284,204,14.95690,1015.94,8.252778,0.89,3.9284,204,14.9569,1015.94,9.377778
3,0.83,14.1036,197,15.17425,1016.41,8.288889,0.83,14.1036,269,15.8263,1016.41,8.288889
4,0.83,11.0446,259,15.82630,1016.51,8.755556,0.83,11.0446,259,15.8263,1016.51,8.755556

In [60]:
pd.concat([df_sn, df_nn], join = 'inner')

    Humi   WindSp  WindBe      Visi     Pres      Temp
0   0.89  14.2646     251  15.82630  1015.13  9.472222
1   0.86  14.2646     259  15.17425  1015.63  8.647222
2   0.84   3.9284     204  14.95690  1015.94  8.252778
3   0.83  14.1036     197  15.17425  1016.41  8.288889
4   0.83  11.0446     259  15.82630  1016.51  8.755556
0   0.89  14.1197     251  15.82630  1015.13  9.472222
1   0.86  14.2646     259  15.82630  1015.63  9.355556
2   0.89   3.9284     204  14.95690  1015.94  9.377778
3   0.83  14.1036     269  15.82630  1016.41  8.288889
4   0.83  11.0446     259  15.82630  1016.51  8.755556

In [61]:
pd.concat([df_sn, df_nn], ignore_index = True)

    Humi   WindSp  WindBe      Visi     Pres      Temp
0   0.89  14.2646     251  15.82630  1015.13  9.472222
1   0.86  14.2646     259  15.17425  1015.63  8.647222
2   0.84   3.9284     204  14.95690  1015.94  8.252778
3   0.83  14.1036     197  15.17425  1016.41  8.288889
4   0.83  11.0446     259  15.82630  1016.51  8.755556
5   0.89  14.1197     251  15.82630  1015.13  9.472222
6   0.86  14.2646     259  15.82630  1015.63  9.355556
7   0.89   3.9284     204  14.95690  1015.94  9.377778
8   0.83  14.1036     269  15.82630  1016.41  8.288889
9   0.83  11.0446     259  15.82630  1016.51  8.755556

In [63]:
pd.concat([df_sn, df_nn], keys = ['First', 'Second'], axis = 1)

  First                                              Second                  \
   Humi   WindSp WindBe      Visi     Pres      Temp   Humi   WindSp WindBe
0  0.89  14.2646    251  15.82630  1015.13  9.472222   0.89  14.1197    251
1  0.86  14.2646    259  15.17425  1015.63  8.647222   0.86  14.2646    259
2  0.84   3.9284    204  14.95690  1015.94  8.252778   0.89   3.9284    204
3  0.83  14.1036    197  15.17425  1016.41  8.288889   0.83  14.1036    269
4  0.83  11.0446    259  15.82630  1016.51  8.755556   0.83  11.0446    259


      Visi     Pres      Temp
0  15.8263  1015.13  9.472222
1  15.8263  1015.63  9.355556
2  14.9569  1015.94  9.377778
3  15.8263  1016.41  8.288889
4  15.8263  1016.51  8.755556

In [79]:
df_sn.join(df_nn, lsuffix = '_First', rsuffix = '_Second')

,Humi_First,WindSp_First,WindBe_First,Visi_First,Pres_First,Temp_First,Humi_Second,WindSp_Second,WindBe_Second,Visi_Second,Pres_Second,Temp_Second
0,0.89,14.2646,251,15.82630,1015.13,9.472222,0.89,14.1197,251,15.8263,1015.13,9.472222
1,0.86,14.2646,259,15.17425,1015.63,8.647222,0.86,14.2646,259,15.8263,1015.63,9.355556
2,0.84,3.9284,204,14.95690,1015.94,8.252778,0.89,3.9284,204,14.9569,1015.94,9.377778
3,0.83,14.1036,197,15.17425,1016.41,8.288889,0.83,14.1036,269,15.8263,1016.41,8.288889
4,0.83,11.0446,259,15.82630,1016.51,8.755556,0.83,11.0446,259,15.8263,1016.51,8.755556

In [81]:
df_sn.join(df_nn, lsuffix = '_First', rsuffix = '_Second', how = 'right')

TypeError: DataFrame.join() got an unexpected keyword argument 'axis'

In [83]:
df.pivot_table(index = 'WindBe')

            Humi       Temp     WindSp         Pres       Visi
WindBe
0       0.798693  10.797747   4.911616   992.475623   9.934070
1       0.694872  13.539679  12.861310  1015.880256  10.854590
2       0.701661  13.627942  10.294316  1011.317085  10.532786
3       0.739309  12.598582   7.723376  1013.239574  10.132895
4       0.702797  13.775047   7.385670  1010.242288   9.607197
...          ...        ...        ...          ...        ...
355     0.718537  14.067389   7.407440  1019.150813  10.590789
356     0.706212  13.807365   7.869851  1002.049848  10.219109
357     0.707831  13.257831   9.823037  1000.165000  10.292652
358     0.697804  13.907376  10.615122  1007.575304  10.675442
359     0.719789  12.971137  12.073768  1004.658496  10.596349

[360 rows x 5 columns]

In [88]:
df.pivot_table(index = 'WindBe', columns = 'Visi', aggfunc = 'sum', fill_value = 0.5, margins = True)

          Humi                                                                 \
Visi       0.0 0.0161 0.0322 0.0483 0.0644 0.0805 0.0966 0.1127 0.1288 0.1449
WindBe
0        24.10   2.88   0.50    0.5   0.50   0.50   0.50   0.50   0.50   0.50
1         2.23   0.50   0.50    0.5   0.50   0.50   0.50   0.50   0.50   0.50
2         0.50   0.50   0.50    0.5   0.50   0.50   0.50   0.50   0.50   0.50
3         4.08   0.50   0.50    0.5   0.50   0.50   0.50   0.50   0.50   0.50
4         0.50   0.50   0.50    0.5   0.50   0.50   0.50   1.00   0.50   0.50
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
356       1.00   0.50   0.50    0.5   0.50   0.50   0.50   0.50   0.50   0.50
357       0.50   0.50   0.50    0.5   0.50   0.50   0.50   0.50   0.50   0.50
358       0.50   0.50   0.50    0.5   0.50   0.50   0.50   0.50   0.50   0.50
359       0.50   0.50   0.50    0.5   0.50   0.50   0.50   0.50   0.50   0.50
All     359.99  18.40  19.51    8.6   9.69   2.79   1.93   1.92   4.87  33.99

        ...     Pres                                                           \
Visi    ...  15.9068   15.9229   15.939  15.9551  15.9873  16.0195    16.0517
WindBe  ...
0       ...     0.50   2040.89     0.50     0.50     0.50     0.50   19376.69
1       ...     0.50      0.50     0.50     0.50     0.50     0.50       0.50
2       ...     0.50      0.50     0.50     0.50     0.50     0.50       0.50
3       ...     0.50      0.50     0.50     0.50     0.50     0.50    1016.64
4       ...     0.50      0.50     0.50     0.50     0.50     0.50       0.50
...     ...      ...       ...      ...      ...      ...      ...        ...
356     ...     0.50      0.50     0.50     0.50     0.50     0.50       0.50
357     ...     0.50      0.50     0.50     0.50     0.50     0.50    1029.45
358     ...     0.50   1029.56     0.50     0.50     0.50     0.50    2044.61
359     ...     0.50      0.50     0.50     0.50     0.50     0.50    1018.36
All     ...  2032.13  58109.96  1018.31  2040.79  1018.44  2035.11  457049.58


Visi    16.0839        16.1          All
WindBe
0          0.50   342149.75   2246964.81
1          0.50    60168.88    435812.63
2          0.50    15239.39    274066.93
3          0.50     8164.97    190489.04
4          0.50     1014.02    119208.59
...         ...         ...          ...
356        0.50     1017.82    132270.58
357        0.50     4074.74    166027.39
358        0.50    24433.28    298242.29
359        0.50    39714.05    380765.57
All     1018.76  7210360.53  96765117.65

[361 rows x 3800 columns]