In [20]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [36]:
X_Tr = pd.read_csv('train.csv')
X_Te = pd.read_csv('test.csv')

In [ ]:
#PRE_PROCESSING

In [37]:
X_Tr.fillna(X_Tr.mean(),inplace = True)
X_Tr.isnull().sum()
X_Te.fillna(X_Te.mean(),inplace = True)
X_Te.isnull().sum()

C:\Users\MUHAMM~1\AppData\Local\Temp/ipykernel_13568/705902647.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  X_Tr.fillna(X_Tr.mean(),inplace = True)
C:\Users\MUHAMM~1\AppData\Local\Temp/ipykernel_13568/705902647.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  X_Te.fillna(X_Te.mean(),inplace = True)

MSSubClass       0
MSZoning         4
LotFrontage      0
LotArea          0
Street           0
                ..
MiscVal          0
MoSold           0
YrSold           0
SaleType         1
SaleCondition    0
Length: 79, dtype: int64

In [38]:
LabelEnc = LabelEncoder()
for column in X_Tr.select_dtypes(include = 'object').columns:
    X_Tr[column] = LabelEnc.fit_transform(X_Tr[column])
    
for column in X_Te.select_dtypes(include = 'object').columns:
    X_Te[column] = LabelEnc.fit_transform(X_Te[column])

In [39]:
X_Tr.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,3,65.0,8450,1,2,3,3,0,4,...,0,3,4,4,0,2,2008,8,4,208500
1,20,3,80.0,9600,1,2,3,3,0,2,...,0,3,4,4,0,5,2007,8,4,181500
2,60,3,68.0,11250,1,2,0,3,0,4,...,0,3,4,4,0,9,2008,8,4,223500
3,70,3,60.0,9550,1,2,0,3,0,0,...,0,3,4,4,0,2,2006,8,0,140000
4,60,3,84.0,14260,1,2,0,3,0,2,...,0,3,4,4,0,12,2008,8,4,250000

In [40]:
X_Te.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,20,2,80.0,11622,1,2,3,3,0,4,...,120,0,2,2,3,0,6,2010,8,4
1,20,3,81.0,14267,1,2,0,3,0,0,...,0,0,2,4,0,12500,6,2010,8,4
2,60,3,74.0,13830,1,2,0,3,0,4,...,0,0,2,2,3,0,3,2010,8,4
3,60,3,78.0,9978,1,2,0,3,0,4,...,0,0,2,4,3,0,6,2010,8,4
4,120,3,43.0,5005,1,2,0,1,0,4,...,144,0,2,4,3,0,1,2010,8,4

In [81]:
X_Train = X_Tr.drop('SalePrice', axis = 1)
Y_Train = X_Tr.SalePrice

In [82]:
X_Train = X_Train.to_numpy()
Y_Train = Y_Train.to_numpy()
X_Test = X_Te.to_numpy()

In [83]:
Y_Train = Y_Train / 1000
X_Train = X_Train / 1000
X_Test = X_Test / 1000

In [84]:
print(X_Train.shape, Y_Train.shape, X_Test.shape)
print(X_Train, Y_Train, X_Test)

(1460, 79) (1460,) (1459, 79)
[[0.06  0.003 0.065 ... 2.008 0.008 0.004]
 [0.02  0.003 0.08  ... 2.007 0.008 0.004]
 [0.06  0.003 0.068 ... 2.008 0.008 0.004]
 ...
 [0.07  0.003 0.066 ... 2.01  0.008 0.004]
 [0.02  0.003 0.068 ... 2.01  0.008 0.004]
 [0.02  0.003 0.075 ... 2.008 0.008 0.004]] [208.5   181.5   223.5   ... 266.5   142.125 147.5  ] [[2.000e-02 2.000e-03 8.000e-02 ... 2.010e+00 8.000e-03 4.000e-03]
 [2.000e-02 3.000e-03 8.100e-02 ... 2.010e+00 8.000e-03 4.000e-03]
 [6.000e-02 3.000e-03 7.400e-02 ... 2.010e+00 8.000e-03 4.000e-03]
 ...
 [2.000e-02 3.000e-03 1.600e-01 ... 2.006e+00 8.000e-03 0.000e+00]
 [8.500e-02 3.000e-03 6.200e-02 ... 2.006e+00 8.000e-03 4.000e-03]
 [6.000e-02 3.000e-03 7.400e-02 ... 2.006e+00 8.000e-03 4.000e-03]]

In [85]:
def costFunc(W, b, X, Y, lambda_):
    m, n = X.shape
    cost = 0
    regu = 0
    J_pred = []
    for i in range(len(W)):
        regu += (W[i]) ** 2
    regu = (lambda_ / (2 * m)) * regu
    for i in range(m):
        f_x = np.dot(W, X[i]) + b
        cost += (f_x - Y[i]) ** 2
    cost = ((1 / (2 * m)) * cost) + regu
    return cost

In [86]:
W_in = np.random.randn(X_Train.shape[1], ) #np.array([-1, -2, 1, 1.5, 0.5, -2, 1, -1, 2, -2, 1, 1])

In [87]:
print(W_in)

[ 1.70798215 -0.3953666   0.96656664  1.21266313  1.69070149  0.52882302
  0.6459753   0.00631522 -1.32827494 -0.20674457  0.35332193  0.90356292
  0.52883637  1.29581284 -1.86742976 -0.22565763  0.28089978  0.08999366
 -0.7458004  -1.43245558  0.10876834  0.51400101  0.70435019  0.38523874
  0.38747925 -0.20466633 -0.20830649 -0.03386654 -0.09695089 -0.43872956
  0.72927339 -0.44975867 -1.68686903 -0.11252674  0.15410379  0.56637206
  0.1568371   0.54705956 -0.30489291  0.85748953 -0.42631376  0.13531941
  1.90149716 -0.13452214 -0.63522836 -1.54935621 -0.78187469  0.12507124
 -1.84129474  0.97017683 -1.36805476 -0.31978589  0.35020471  1.23801192
 -0.99940791  1.06915799  0.55968932  0.87467719  1.59975216  0.58853651
 -0.06793325  1.25269611 -0.90745617  0.70475952 -0.74112171 -0.03667467
  2.49299608 -0.26980689  1.76368048  0.49801617 -0.45908102 -1.2668422
 -0.83670929 -0.50756804  0.62147312 -2.46149567 -0.62101367  0.46317999
  1.82201961]

In [62]:
def calcGradients(W, b, X, Y, lambda_):
    m, n = X.shape
    dJ_dw = 0
    dJ_db = 0
    regu = 0
    for i in range(len(W)):
        regu += (W[i])
    regu = (lambda_ / (m)) * regu
    for i in range(m):
        f_x = np.dot(W, X[i]) + b
        dJ_dw += (f_x - Y[i]) * X[i]
        dJ_db += (f_x - Y[i])
    dJ_dw = ((1 / m) * dJ_dw) + regu
    dJ_db = (1 / m) * dJ_db
    return dJ_dw, dJ_db

In [63]:
def gradientDescent(iterations, W, b, X, Y, lambda_, alpha):
    for i in range(iterations):
        dJ_dw, dJ_db = calcGradients(W, b, X, Y, lambda_)
        W = W - alpha * dJ_dw
        b = b - alpha * dJ_db
        if (i % 50 == 0):
            J = costFunc(W, b, X, Y, lambda_)
            print("The cost at", i, "iteration is", J)
    return W, b

In [93]:
def predict(W, b, X):
    m, n = X.shape
    pred = []
    for i in range(m):
        f_x = np.dot(W, X[i]) + b
        pred.append(f_x)
    return pred

In [110]:
W, b = gradientDescent(215000, W_in, 0.548, X_Train, Y_Train, 0.03, 0.008)
print("Optimum parameters are", W, b)

The cost at 0 iteration is 12840.059440269628
The cost at 50 iteration is 1954.4686210186753
The cost at 100 iteration is 1732.199163389142
The cost at 150 iteration is 1568.8277009808712
The cost at 200 iteration is 1447.6220996844993
The cost at 250 iteration is 1357.4763461192385
The cost at 300 iteration is 1290.2187513136892
The cost at 350 iteration is 1239.8355061316827
The cost at 400 iteration is 1201.9001573823518
The cost at 450 iteration is 1173.1540424094878
The cost at 500 iteration is 1151.1977153694925
The cost at 550 iteration is 1134.2639851836705
The cost at 600 iteration is 1121.0509659027603
The cost at 650 iteration is 1110.5992596138465
The cost at 700 iteration is 1102.201596337718
The cost at 750 iteration is 1095.336346077696
The cost at 800 iteration is 1089.6185903493672
The cost at 850 iteration is 1084.7641110062461
The cost at 900 iteration is 1080.56288236999
The cost at 950 iteration is 1076.859555729588
The cost at 1000 iteration is 1073.5390893045183
The cost at 1050 iteration is 1070.5161650695375
The cost at 1100 iteration is 1067.7273929427085
The cost at 1150 iteration is 1065.1255669474772
The cost at 1200 iteration is 1062.6754322189279
The cost at 1250 iteration is 1060.3505646198364
The cost at 1300 iteration is 1058.1310698543434
The cost at 1350 iteration is 1056.0018863095295
The cost at 1400 iteration is 1053.9515327646932
The cost at 1450 iteration is 1051.9711839881727
The cost at 1500 iteration is 1050.053988065306
The cost at 1550 iteration is 1048.194561990327
The cost at 1600 iteration is 1046.3886187592295
The cost at 1650 iteration is 1044.6326915004474
The cost at 1700 iteration is 1042.9239292384711
The cost at 1750 iteration is 1041.2599455580569
The cost at 1800 iteration is 1039.6387063524558
The cost at 1850 iteration is 1038.058446461798
The cost at 1900 iteration is 1036.5176076780165
The cost at 1950 iteration is 1035.0147925613473
The cost at 2000 iteration is 1033.5487299654014
The cost at 2050 iteration is 1032.1182492389464
The cost at 2100 iteration is 1030.7222608628797
The cost at 2150 iteration is 1029.359741864499
The cost at 2200 iteration is 1028.029724782027
The cost at 2250 iteration is 1026.73128927075
The cost at 2300 iteration is 1025.4635556774456
The cost at 2350 iteration is 1024.2256800837933
The cost at 2400 iteration is 1023.0168504482209
The cost at 2450 iteration is 1021.8362835709445
The cost at 2500 iteration is 1020.6832226775238
The cost at 2550 iteration is 1019.5569354686859
The cost at 2600 iteration is 1018.456712522872
The cost at 2650 iteration is 1017.3818659668384
The cost at 2700 iteration is 1016.3317283510478
The cost at 2750 iteration is 1015.3056516824494
The cost at 2800 iteration is 1014.3030065791928
The cost at 2850 iteration is 1013.3231815205231
The cost at 2900 iteration is 1012.3655821717912
The cost at 2950 iteration is 1011.429630769354
The cost at 3000 iteration is 1010.5147655538985
The cost at 3050 iteration is 1009.6204402433434
The cost at 3100 iteration is 1008.7461235387407
The cost at 3150 iteration is 1007.891298657889
The cost at 3200 iteration is 1007.0554628928206
The cost at 3250 iteration is 1006.2381271879439
The cost at 3300 iteration is 1005.4388157365024
The cost at 3350 iteration is 1004.6570655933796
The cost at 3400 iteration is 1003.8924263027121
The cost at 3450 iteration is 1003.1444595390918
The cost at 3500 iteration is 1002.4127387612959
The cost at 3550 iteration is 1001.6968488777425
The cost at 3600 iteration is 1000.9963859229098
The cost at 3650 iteration is 1000.3109567441522
The cost at 3700 iteration is 999.6401786983631
The cost at 3750 iteration is 998.9836793580096
The cost at 3800 iteration is 998.3410962261738
The cost at 3850 iteration is 997.7120764601591
The cost at 3900 iteration is 997.0962766033942
The cost at 3950 iteration is 996.4933623252816
The cost at 4000 iteration is 995.9030081687082
The cost at 4050 iteration is 995.3248973049688
The cost at 4100 iteration is 994.7587212958359
The cost at 4150 iteration is 994.2041798625306
The cost at 4200 iteration is 993.6609806613952
The cost at 4250 iteration is 993.1288390660236
The cost at 4300 iteration is 992.6074779556685
The cost at 4350 iteration is 992.0966275096995
The cost at 4400 iteration is 991.5960250079709
The cost at 4450 iteration is 991.1054146368606
The cost at 4500 iteration is 990.6245473008595
The cost at 4550 iteration is 990.1531804395024
The cost at 4600 iteration is 989.6910778494998
The cost at 4650 iteration is 989.2380095119148
The cost at 4700 iteration is 988.7937514242284
The cost at 4750 iteration is 988.3580854371421
The cost at 4800 iteration is 987.930799095984
The cost at 4850 iteration is 987.5116854865859
The cost at 4900 iteration is 987.1005430854985
The cost at 4950 iteration is 986.6971756143931
The cost at 5000 iteration is 986.3013918985656
The cost at 5050 iteration is 985.913005729398
The cost at 5100 iteration is 985.5318357306563
The cost at 5150 iteration is 985.1577052285372
The cost at 5200 iteration is 984.7904421253259
The cost at 5250 iteration is 984.429878776587
The cost at 5300 iteration is 984.0758518717588
The cost at 5350 iteration is 983.7282023180733
The cost at 5400 iteration is 983.3867751276954
The cost at 5450 iteration is 983.0514193079977
The cost at 5500 iteration is 982.7219877548541
The cost at 5550 iteration is 982.3983371489152
The cost at 5600 iteration is 982.0803278547112
The cost at 5650 iteration is 981.7678238225645
The cost at 5700 iteration is 981.4606924932101
The cost at 5750 iteration is 981.1588047050102
The cost at 5800 iteration is 980.8620346037553
The cost at 5850 iteration is 980.5702595549113
The cost at 5900 iteration is 980.2833600583003
The cost at 5950 iteration is 980.0012196651087
The cost at 6000 iteration is 979.7237248971543
The cost at 6050 iteration is 979.4507651683862
The cost at 6100 iteration is 979.1822327085022
The cost at 6150 iteration is 978.918022488673
The cost at 6200 iteration is 978.6580321492785
The cost at 6250 iteration is 978.4021619296022
The cost at 6300 iteration is 978.1503145994709
The cost at 6350 iteration is 977.9023953927084
The cost at 6400 iteration is 977.658311942429
The cost at 6450 iteration is 977.417974218068
The cost at 6500 iteration is 977.1812944641287
The cost at 6550 iteration is 976.9481871405725
The cost at 6600 iteration is 976.7185688648335
The cost at 6650 iteration is 976.4923583553909
The cost at 6700 iteration is 976.2694763768706
The cost at 6750 iteration is 976.0498456866242
The cost at 6800 iteration is 975.833390982736
The cost at 6850 iteration is 975.620038853447
The cost at 6900 iteration is 975.4097177279182
The cost at 6950 iteration is 975.2023578283458
The cost at 7000 iteration is 974.9978911233059
The cost at 7050 iteration is 974.7962512824238
The cost at 7100 iteration is 974.5973736321913
The cost at 7150 iteration is 974.4011951130044
The cost at 7200 iteration is 974.2076542373294
The cost at 7250 iteration is 974.0166910490015
The cost at 7300 iteration is 973.828247083591
The cost at 7350 iteration is 973.6422653298513
The cost at 7400 iteration is 973.4586901921615
The cost at 7450 iteration is 973.2774674539919
The cost at 7500 iteration is 973.0985442423442
The cost at 7550 iteration is 972.921868993106
The cost at 7600 iteration is 972.7473914173595
The cost at 7650 iteration is 972.5750624685652
The cost at 7700 iteration is 972.4048343106075
The cost at 7750 iteration is 972.2366602867196
The cost at 7800 iteration is 972.0704948891838
The cost at 7850 iteration is 971.9062937298688
The cost at 7900 iteration is 971.7440135115319
The cost at 7950 iteration is 971.5836119998742
The cost at 8000 iteration is 971.4250479963434
The cost at 8050 iteration is 971.2682813116384
The cost at 8100 iteration is 971.1132727399278
The cost at 8150 iteration is 970.9599840337322
The cost at 8200 iteration is 970.8083778794769
The cost at 8250 iteration is 970.6584178736773
The cost at 8300 iteration is 970.5100684997611
The cost at 8350 iteration is 970.3632951054809
The cost at 8400 iteration is 970.2180638809402
The cost at 8450 iteration is 970.0743418371726
The cost at 8500 iteration is 969.9320967852966

The cost at 8550 iteration is 969.7912973162131
The cost at 8600 iteration is 969.6519127808258
The cost at 8650 iteration is 969.5139132707819
The cost at 8700 iteration is 969.3772695997249
The cost at 8750 iteration is 969.2419532850116
The cost at 8800 iteration is 969.1079365299315
The cost at 8850 iteration is 968.9751922063741
The cost at 8900 iteration is 968.8436938379566
The cost at 8950 iteration is 968.7134155835719
The cost at 9000 iteration is 968.5843322213888
The cost at 9050 iteration is 968.4564191332422
The cost at 9100 iteration is 968.329652289449
The cost at 9150 iteration is 968.2040082340078
The cost at 9200 iteration is 968.0794640701804
The cost at 9250 iteration is 967.9559974464566
The cost at 9300 iteration is 967.8335865428534
The cost at 9350 iteration is 967.7122100576155
The cost at 9400 iteration is 967.59184719422
The cost at 9450 iteration is 967.4724776487249
The cost at 9500 iteration is 967.3540815974555
The cost at 9550 iteration is 967.236639685001
The cost at 9600 iteration is 967.1201330125157
The cost at 9650 iteration is 967.0045431263264
The cost at 9700 iteration is 966.8898520068419
The cost at 9750 iteration is 966.7760420577188
The cost at 9800 iteration is 966.6630960953383
The cost at 9850 iteration is 966.5509973385432
The cost at 9900 iteration is 966.4397293986228
The cost at 9950 iteration is 966.329276269566
The cost at 10000 iteration is 966.2196223185806
The cost at 10050 iteration is 966.110752276819
The cost at 10100 iteration is 966.0026512303723
The cost at 10150 iteration is 965.8953046114798
The cost at 10200 iteration is 965.788698189972
The cost at 10250 iteration is 965.6828180649181
The cost at 10300 iteration is 965.577650656507
The cost at 10350 iteration is 965.4731826981099
The cost at 10400 iteration is 965.3694012285689
The cost at 10450 iteration is 965.2662935846737
The cost at 10500 iteration is 965.1638473938231
The cost at 10550 iteration is 965.0620505668782
The cost at 10600 iteration is 964.9608912912062
The cost at 10650 iteration is 964.8603580238779
The cost at 10700 iteration is 964.7604394850648
The cost at 10750 iteration is 964.6611246515882
The cost at 10800 iteration is 964.562402750631
The cost at 10850 iteration is 964.464263253621
The cost at 10900 iteration is 964.3666958702514
The cost at 10950 iteration is 964.2696905426684
The cost at 11000 iteration is 964.1732374397986
The cost at 11050 iteration is 964.0773269518211
The cost at 11100 iteration is 963.9819496847773
The cost at 11150 iteration is 963.8870964553253
The cost at 11200 iteration is 963.7927582856065
The cost at 11250 iteration is 963.6989263982699
The cost at 11300 iteration is 963.6055922116005
The cost at 11350 iteration is 963.5127473347708
The cost at 11400 iteration is 963.4203835632369
The cost at 11450 iteration is 963.3284928742007
The cost at 11500 iteration is 963.237067422253
The cost at 11550 iteration is 963.1460995350628
The cost at 11600 iteration is 963.055581709211
The cost at 11650 iteration is 962.9655066061204
The cost at 11700 iteration is 962.8758670480919
The cost at 11750 iteration is 962.7866560144249
The cost at 11800 iteration is 962.6978666376514
The cost at 11850 iteration is 962.6094921998547
The cost at 11900 iteration is 962.52152612909
The cost at 11950 iteration is 962.4339619958789
The cost at 12000 iteration is 962.3467935098079
The cost at 12050 iteration is 962.2600145162066
The cost at 12100 iteration is 962.1736189928865
The cost at 12150 iteration is 962.0876010470197
The cost at 12200 iteration is 962.0019549120093
The cost at 12250 iteration is 961.9166749445286
The cost at 12300 iteration is 961.8317556215635
The cost at 12350 iteration is 961.7471915375639
The cost at 12400 iteration is 961.6629774016675
The cost at 12450 iteration is 961.5791080349568
The cost at 12500 iteration is 961.4955783678383
The cost at 12550 iteration is 961.4123834374448
The cost at 12600 iteration is 961.329518385114
The cost at 12650 iteration is 961.2469784539385
The cost at 12700 iteration is 961.1647589863609
The cost at 12750 iteration is 961.0828554218477
The cost at 12800 iteration is 961.0012632945964
The cost at 12850 iteration is 960.9199782313246
The cost at 12900 iteration is 960.8389959490908
The cost at 12950 iteration is 960.7583122531912
The cost at 13000 iteration is 960.6779230350859
The cost at 13050 iteration is 960.5978242703964
The cost at 13100 iteration is 960.5180120169348
The cost at 13150 iteration is 960.4384824127927
The cost at 13200 iteration is 960.3592316744813
The cost at 13250 iteration is 960.2802560950984
The cost at 13300 iteration is 960.2015520425623
The cost at 13350 iteration is 960.1231159578629
The cost at 13400 iteration is 960.0449443534004
The cost at 13450 iteration is 959.9670338113046
The cost at 13500 iteration is 959.8893809818408
The cost at 13550 iteration is 959.8119825818422
The cost at 13600 iteration is 959.7348353931762
The cost at 13650 iteration is 959.6579362612492
The cost at 13700 iteration is 959.5812820935495
The cost at 13750 iteration is 959.5048698582278
The cost at 13800 iteration is 959.4286965827096
The cost at 13850 iteration is 959.3527593523362
The cost at 13900 iteration is 959.2770553090561
The cost at 13950 iteration is 959.2015816501251
The cost at 14000 iteration is 959.1263356268547
The cost at 14050 iteration is 959.0513145433847
The cost at 14100 iteration is 958.9765157554846
The cost at 14150 iteration is 958.9019366693881
The cost at 14200 iteration is 958.8275747406586
The cost at 14250 iteration is 958.7534274730582
The cost at 14300 iteration is 958.6794924174868
The cost at 14350 iteration is 958.6057671709075
The cost at 14400 iteration is 958.5322493753149
The cost at 14450 iteration is 958.4589367167376
The cost at 14500 iteration is 958.3858269242327
The cost at 14550 iteration is 958.3129177689486
The cost at 14600 iteration is 958.2402070631703
The cost at 14650 iteration is 958.1676926594139
The cost at 14700 iteration is 958.0953724495307
The cost at 14750 iteration is 958.0232443638289
The cost at 14800 iteration is 957.9513063702412
The cost at 14850 iteration is 957.8795564734662
The cost at 14900 iteration is 957.8079927141895
The cost at 14950 iteration is 957.7366131682668
The cost at 15000 iteration is 957.6654159459682
The cost at 15050 iteration is 957.5943991912084
The cost at 15100 iteration is 957.523561080826
The cost at 15150 iteration is 957.4528998238594
The cost at 15200 iteration is 957.3824136608421
The cost at 15250 iteration is 957.3121008631271
The cost at 15300 iteration is 957.2419597321948
The cost at 15350 iteration is 957.1719885990404
The cost at 15400 iteration is 957.1021858234963
The cost at 15450 iteration is 957.0325497936308
The cost at 15500 iteration is 956.9630789251408
The cost at 15550 iteration is 956.8937716607517
The cost at 15600 iteration is 956.8246264696428
The cost at 15650 iteration is 956.7556418468781
The cost at 15700 iteration is 956.6868163128596
The cost at 15750 iteration is 956.618148412773
The cost at 15800 iteration is 956.5496367160879
The cost at 15850 iteration is 956.481279816019
The cost at 15900 iteration is 956.4130763290337
The cost at 15950 iteration is 956.3450248943632
The cost at 16000 iteration is 956.277124173516
The cost at 16050 iteration is 956.2093728498196
The cost at 16100 iteration is 956.1417696279581
The cost at 16150 iteration is 956.0743132335215
The cost at 16200 iteration is 956.0070024125793
The cost at 16250 iteration is 955.9398359312532
The cost at 16300 iteration is 955.8728125752875
The cost at 16350 iteration is 955.805931149661
The cost at 16400 iteration is 955.7391904781796
The cost at 16450 iteration is 955.6725894030928
The cost at 16500 iteration is 955.6061267847066
The cost at 16550 iteration is 955.5398015010315
The cost at 16600 iteration is 955.4736124473945
The cost at 16650 iteration is 955.4075585361105
The cost at 16700 iteration is 955.341638696126
The cost at 16750 iteration is 955.2758518726793
The cost at 16800 iteration is 955.2101970269739
The cost at 16850 iteration is 955.1446731358624
The cost at 16900 iteration is 955.0792791915239
The cost at 16950 iteration is 955.014014201151

The cost at 17000 iteration is 954.9488771866695
The cost at 17050 iteration is 954.883867184425
The cost at 17100 iteration is 954.8189832449049
The cost at 17150 iteration is 954.7542244324562
The cost at 17200 iteration is 954.6895898250091
The cost at 17250 iteration is 954.6250785138166
The cost at 17300 iteration is 954.5606896031836
The cost at 17350 iteration is 954.496422210211
The cost at 17400 iteration is 954.4322754645547
The cost at 17450 iteration is 954.368248508173
The cost at 17500 iteration is 954.3043404950848
The cost at 17550 iteration is 954.2405505911477
The cost at 17600 iteration is 954.1768779738202
The cost at 17650 iteration is 954.1133218319361
The cost at 17700 iteration is 954.0498813654937
The cost at 17750 iteration is 953.9865557854324
The cost at 17800 iteration is 953.9233443134416
The cost at 17850 iteration is 953.8602461817295
The cost at 17900 iteration is 953.797260632853
The cost at 17950 iteration is 953.734386919495
The cost at 18000 iteration is 953.6716243042933
The cost at 18050 iteration is 953.6089720596444
The cost at 18100 iteration is 953.546429467524
The cost at 18150 iteration is 953.4839958193063
The cost at 18200 iteration is 953.4216704155851
The cost at 18250 iteration is 953.3594525660178
The cost at 18300 iteration is 953.2973415891406
The cost at 18350 iteration is 953.2353368122107
The cost at 18400 iteration is 953.1734375710544
The cost at 18450 iteration is 953.1116432098952
The cost at 18500 iteration is 953.0499530812214
The cost at 18550 iteration is 952.9883665456093
The cost at 18600 iteration is 952.9268829716046
The cost at 18650 iteration is 952.8655017355559
The cost at 18700 iteration is 952.8042222214893
The cost at 18750 iteration is 952.7430438209605
The cost at 18800 iteration is 952.6819659329327
The cost at 18850 iteration is 952.6209879636324
The cost at 18900 iteration is 952.5601093264244
The cost at 18950 iteration is 952.499329441695
The cost at 19000 iteration is 952.4386477367123
The cost at 19050 iteration is 952.3780636455137
The cost at 19100 iteration is 952.3175766087993
The cost at 19150 iteration is 952.2571860737926
The cost at 19200 iteration is 952.1968914941453
The cost at 19250 iteration is 952.1366923298186
The cost at 19300 iteration is 952.0765880469731
The cost at 19350 iteration is 952.0165781178799
The cost at 19400 iteration is 951.9566620207856
The cost at 19450 iteration is 951.8968392398339
The cost at 19500 iteration is 951.8371092649628
The cost at 19550 iteration is 951.777471591799
The cost at 19600 iteration is 951.7179257215652
The cost at 19650 iteration is 951.6584711609906
The cost at 19700 iteration is 951.5991074222196
The cost at 19750 iteration is 951.5398340227091
The cost at 19800 iteration is 951.480650485157
The cost at 19850 iteration is 951.4215563374033
The cost at 19900 iteration is 951.3625511123588
The cost at 19950 iteration is 951.3036343479066
The cost at 20000 iteration is 951.244805586831
The cost at 20050 iteration is 951.1860643767341
The cost at 20100 iteration is 951.1274102699649
The cost at 20150 iteration is 951.0688428235337
The cost at 20200 iteration is 951.0103615990404
The cost at 20250 iteration is 950.9519661626033
The cost at 20300 iteration is 950.8936560847836
The cost at 20350 iteration is 950.8354309405279
The cost at 20400 iteration is 950.7772903090723
The cost at 20450 iteration is 950.7192337739025
The cost at 20500 iteration is 950.6612609226754
The cost at 20550 iteration is 950.6033713471503
The cost at 20600 iteration is 950.5455646431333
The cost at 20650 iteration is 950.4878404104129
The cost at 20700 iteration is 950.4301982526905
The cost at 20750 iteration is 950.372637777534
The cost at 20800 iteration is 950.3151585963118
The cost at 20850 iteration is 950.25776032413
The cost at 20900 iteration is 950.2004425797878
The cost at 20950 iteration is 950.1432049857116
The cost at 21000 iteration is 950.0860471679007
The cost at 21050 iteration is 950.0289687558877
The cost at 21100 iteration is 949.9719693826695
The cost at 21150 iteration is 949.9150486846606
The cost at 21200 iteration is 949.8582063016476
The cost at 21250 iteration is 949.801441876736
The cost at 21300 iteration is 949.7447550563053
The cost at 21350 iteration is 949.6881454899523
The cost at 21400 iteration is 949.6316128304562
The cost at 21450 iteration is 949.5751567337246
The cost at 21500 iteration is 949.5187768587527
The cost at 21550 iteration is 949.4624728675723
The cost at 21600 iteration is 949.4062444252239
The cost at 21650 iteration is 949.3500911996927
The cost at 21700 iteration is 949.2940128618883
The cost at 21750 iteration is 949.23800908559
The cost at 21800 iteration is 949.1820795474077
The cost at 21850 iteration is 949.1262239267456
The cost at 21900 iteration is 949.0704419057686
The cost at 21950 iteration is 949.0147331693524
The cost at 22000 iteration is 948.9590974050542
The cost at 22050 iteration is 948.9035343030764
The cost at 22100 iteration is 948.8480435562253
The cost at 22150 iteration is 948.7926248598835
The cost at 22200 iteration is 948.7372779119637
The cost at 22250 iteration is 948.6820024128887
The cost at 22300 iteration is 948.6267980655448
The cost at 22350 iteration is 948.5716645752602
The cost at 22400 iteration is 948.5166016497623
The cost at 22450 iteration is 948.4616089991522
The cost at 22500 iteration is 948.406686335876
The cost at 22550 iteration is 948.351833374687
The cost at 22600 iteration is 948.2970498326163
The cost at 22650 iteration is 948.2423354289507
The cost at 22700 iteration is 948.1876898852015
The cost at 22750 iteration is 948.1331129250586
The cost at 22800 iteration is 948.078604274397
The cost at 22850 iteration is 948.024163661217
The cost at 22900 iteration is 947.9697908156273
The cost at 22950 iteration is 947.9154854698335
The cost at 23000 iteration is 947.8612473580821
The cost at 23050 iteration is 947.8070762166631
The cost at 23100 iteration is 947.7529717838686
The cost at 23150 iteration is 947.6989337999732
The cost at 23200 iteration is 947.6449620072091
The cost at 23250 iteration is 947.5910561497409
The cost at 23300 iteration is 947.5372159736434
The cost at 23350 iteration is 947.4834412268716
The cost at 23400 iteration is 947.4297316592551
The cost at 23450 iteration is 947.3760870224521
The cost at 23500 iteration is 947.3225070699475
The cost at 23550 iteration is 947.2689915570211
The cost at 23600 iteration is 947.2155402407227
The cost at 23650 iteration is 947.1621528798663
The cost at 23700 iteration is 947.1088292349892
The cost at 23750 iteration is 947.0555690683485
The cost at 23800 iteration is 947.0023721438872
The cost at 23850 iteration is 946.949238227231
The cost at 23900 iteration is 946.8961670856525
The cost at 23950 iteration is 946.8431584880633
The cost at 24000 iteration is 946.7902122049848
The cost at 24050 iteration is 946.737328008537
The cost at 24100 iteration is 946.6845056724271
The cost at 24150 iteration is 946.6317449719135
The cost at 24200 iteration is 946.5790456838034
The cost at 24250 iteration is 946.5264075864243
The cost at 24300 iteration is 946.4738304596185
The cost at 24350 iteration is 946.4213140847213
The cost at 24400 iteration is 946.3688582445343
The cost at 24450 iteration is 946.3164627233296
The cost at 24500 iteration is 946.2641273068136
The cost at 24550 iteration is 946.2118517821216
The cost at 24600 iteration is 946.1596359378045
The cost at 24650 iteration is 946.1074795638062
The cost at 24700 iteration is 946.0553824514512
The cost at 24750 iteration is 946.0033443934286
The cost at 24800 iteration is 945.951365183782
The cost at 24850 iteration is 945.8994446178899
The cost at 24900 iteration is 945.847582492453
The cost at 24950 iteration is 945.7957786054844
The cost at 25000 iteration is 945.7440327562865
The cost at 25050 iteration is 945.6923447454474
The cost at 25100 iteration is 945.6407143748181
The cost at 25150 iteration is 945.5891414475063
The cost at 25200 iteration is 945.5376257678666
The cost at 25250 iteration is 945.4861671414686
The cost at 25300 iteration is 945.4347653751107
The cost at 25350 iteration is 945.3834202767891

The cost at 25400 iteration is 945.3321316556908
The cost at 25450 iteration is 945.2808993221842
The cost at 25500 iteration is 945.2297230878014
The cost at 25550 iteration is 945.1786027652327
The cost at 25600 iteration is 945.1275381683045
The cost at 25650 iteration is 945.0765291119895
The cost at 25700 iteration is 945.0255754123644
The cost at 25750 iteration is 944.9746768866307
The cost at 25800 iteration is 944.9238333530772
The cost at 25850 iteration is 944.8730446310859
The cost at 25900 iteration is 944.8223105411116
The cost at 25950 iteration is 944.7716309046817
The cost at 26000 iteration is 944.7210055443774
The cost at 26050 iteration is 944.670434283822
The cost at 26100 iteration is 944.6199169476794
The cost at 26150 iteration is 944.5694533616337
The cost at 26200 iteration is 944.5190433523959
The cost at 26250 iteration is 944.4686867476694
The cost at 26300 iteration is 944.4183833761635
The cost at 26350 iteration is 944.3681330675735
The cost at 26400 iteration is 944.3179356525659
The cost at 26450 iteration is 944.2677909627839
The cost at 26500 iteration is 944.2176988308304
The cost at 26550 iteration is 944.1676590902537
The cost at 26600 iteration is 944.1176715755445
The cost at 26650 iteration is 944.0677361221298
The cost at 26700 iteration is 944.017852566359
The cost at 26750 iteration is 943.968020745502
The cost at 26800 iteration is 943.9182404977286
The cost at 26850 iteration is 943.8685116621115
The cost at 26900 iteration is 943.8188340786144
The cost at 26950 iteration is 943.76920758809
The cost at 27000 iteration is 943.7196320322564
The cost at 27050 iteration is 943.6701072537016
The cost at 27100 iteration is 943.6206330958788
The cost at 27150 iteration is 943.5712094030865
The cost at 27200 iteration is 943.5218360204719
The cost at 27250 iteration is 943.4725127940172
The cost at 27300 iteration is 943.4232395705302
The cost at 27350 iteration is 943.3740161976509
The cost at 27400 iteration is 943.3248425238218
The cost at 27450 iteration is 943.275718398304
The cost at 27500 iteration is 943.2266436711554
The cost at 27550 iteration is 943.1776181932223
The cost at 27600 iteration is 943.1286418161507
The cost at 27650 iteration is 943.079714392353
The cost at 27700 iteration is 943.0308357750234
The cost at 27750 iteration is 942.982005818125
The cost at 27800 iteration is 942.9332243763733
The cost at 27850 iteration is 942.8844913052448
The cost at 27900 iteration is 942.8358064609617
The cost at 27950 iteration is 942.7871697004857
The cost at 28000 iteration is 942.7385808815176
The cost at 28050 iteration is 942.6900398624823
The cost at 28100 iteration is 942.6415465025318
The cost at 28150 iteration is 942.5931006615367
The cost at 28200 iteration is 942.5447022000722
The cost at 28250 iteration is 942.4963509794272
The cost at 28300 iteration is 942.4480468615791
The cost at 28350 iteration is 942.3997897092103
The cost at 28400 iteration is 942.3515793856855
The cost at 28450 iteration is 942.3034157550537
The cost at 28500 iteration is 942.2552986820378
The cost at 28550 iteration is 942.2072280320366
The cost at 28600 iteration is 942.1592036711163
The cost at 28650 iteration is 942.1112254659972
The cost at 28700 iteration is 942.063293284061
The cost at 28750 iteration is 942.015406993337
The cost at 28800 iteration is 941.9675664625024
The cost at 28850 iteration is 941.9197715608698
The cost at 28900 iteration is 941.872022158397
The cost at 28950 iteration is 941.8243181256564
The cost at 29000 iteration is 941.7766593338604
The cost at 29050 iteration is 941.729045654832
The cost at 29100 iteration is 941.6814769610187
The cost at 29150 iteration is 941.6339531254689
The cost at 29200 iteration is 941.586474021846
The cost at 29250 iteration is 941.5390395244086
The cost at 29300 iteration is 941.4916495080153
The cost at 29350 iteration is 941.4443038481163
The cost at 29400 iteration is 941.3970024207507
The cost at 29450 iteration is 941.3497451025383
The cost at 29500 iteration is 941.3025317706806
The cost at 29550 iteration is 941.2553623029532
The cost at 29600 iteration is 941.208236577703
The cost at 29650 iteration is 941.1611544738383
The cost at 29700 iteration is 941.114115870835
The cost at 29750 iteration is 941.0671206487232
The cost at 29800 iteration is 941.0201686880904
The cost at 29850 iteration is 940.9732598700687
The cost at 29900 iteration is 940.9263940763374
The cost at 29950 iteration is 940.8795711891203
The cost at 30000 iteration is 940.8327910911756
The cost at 30050 iteration is 940.7860536657953
The cost at 30100 iteration is 940.7393587967994
The cost at 30150 iteration is 940.6927063685412
The cost at 30200 iteration is 940.6460962658887
The cost at 30250 iteration is 940.5995283742296
The cost at 30300 iteration is 940.5530025794689
The cost at 30350 iteration is 940.5065187680211
The cost at 30400 iteration is 940.4600768268081
The cost at 30450 iteration is 940.4136766432554
The cost at 30500 iteration is 940.3673181052877
The cost at 30550 iteration is 940.3210011013325
The cost at 30600 iteration is 940.2747255202963
The cost at 30650 iteration is 940.2284912515952
The cost at 30700 iteration is 940.1822981851155
The cost at 30750 iteration is 940.136146211232
The cost at 30800 iteration is 940.0900352208035
The cost at 30850 iteration is 940.043965105159
The cost at 30900 iteration is 939.9979357561015
The cost at 30950 iteration is 939.9519470659051
The cost at 31000 iteration is 939.9059989273117
The cost at 31050 iteration is 939.8600912335255
The cost at 31100 iteration is 939.814223878209
The cost at 31150 iteration is 939.7683967554835
The cost at 31200 iteration is 939.7226097599262
The cost at 31250 iteration is 939.6768627865653
The cost at 31300 iteration is 939.6311557308701
The cost at 31350 iteration is 939.5854884887619
The cost at 31400 iteration is 939.5398609566049
The cost at 31450 iteration is 939.4942730311972
The cost at 31500 iteration is 939.4487246097755
The cost at 31550 iteration is 939.4032155900107
The cost at 31600 iteration is 939.3577458700028
The cost at 31650 iteration is 939.3123153482786
The cost at 31700 iteration is 939.2669239237906
The cost at 31750 iteration is 939.2215714959159
The cost at 31800 iteration is 939.1762579644501
The cost at 31850 iteration is 939.1309832295998
The cost at 31900 iteration is 939.0857471919905
The cost at 31950 iteration is 939.0405497526606
The cost at 32000 iteration is 938.9953908130502
The cost at 32050 iteration is 938.9502702750136
The cost at 32100 iteration is 938.9051880408014
The cost at 32150 iteration is 938.8601440130701
The cost at 32200 iteration is 938.8151380948732
The cost at 32250 iteration is 938.7701701896536
The cost at 32300 iteration is 938.7252402012577
The cost at 32350 iteration is 938.6803480339179
The cost at 32400 iteration is 938.6354935922539
The cost at 32450 iteration is 938.5906767812688
The cost at 32500 iteration is 938.5458975063575
The cost at 32550 iteration is 938.5011556732908
The cost at 32600 iteration is 938.4564511882127
The cost at 32650 iteration is 938.4117839576553
The cost at 32700 iteration is 938.3671538885179
The cost at 32750 iteration is 938.3225608880666
The cost at 32800 iteration is 938.2780048639522
The cost at 32850 iteration is 938.2334857241773
The cost at 32900 iteration is 938.1890033771159
The cost at 32950 iteration is 938.1445577315018
The cost at 33000 iteration is 938.1001486964391
The cost at 33050 iteration is 938.0557761813737
The cost at 33100 iteration is 938.0114400961257
The cost at 33150 iteration is 937.9671403508586
The cost at 33200 iteration is 937.9228768560871
The cost at 33250 iteration is 937.8786495226802
The cost at 33300 iteration is 937.8344582618519
The cost at 33350 iteration is 937.7903029851667
The cost at 33400 iteration is 937.746183604526
The cost at 33450 iteration is 937.7021000321789
The cost at 33500 iteration is 937.6580521807053
The cost at 33550 iteration is 937.6140399630391
The cost at 33600 iteration is 937.5700632924294
The cost at 33650 iteration is 937.5261220824743
The cost at 33700 iteration is 937.4822162470991
The cost at 33750 iteration is 937.4383457005596

The cost at 33800 iteration is 937.3945103574354
The cost at 33850 iteration is 937.3507101326334
The cost at 33900 iteration is 937.3069449413931
The cost at 33950 iteration is 937.263214699267
The cost at 34000 iteration is 937.2195193221269
The cost at 34050 iteration is 937.1758587261738
The cost at 34100 iteration is 937.132232827917
The cost at 34150 iteration is 937.0886415441782
The cost at 34200 iteration is 937.045084792104
The cost at 34250 iteration is 937.0015624891422
The cost at 34300 iteration is 936.9580745530535
The cost at 34350 iteration is 936.9146209019083
The cost at 34400 iteration is 936.8712014540807
The cost at 34450 iteration is 936.8278161282511
The cost at 34500 iteration is 936.7844648434032
The cost at 34550 iteration is 936.7411475188204
The cost at 34600 iteration is 936.6978640740872
The cost at 34650 iteration is 936.6546144290844
The cost at 34700 iteration is 936.6113985039897
The cost at 34750 iteration is 936.5682162192755
The cost at 34800 iteration is 936.5250674957093
The cost at 34850 iteration is 936.4819522543427
The cost at 34900 iteration is 936.4388704165318
The cost at 34950 iteration is 936.3958219039048
The cost at 35000 iteration is 936.3528066383832
The cost at 35050 iteration is 936.3098245421791
The cost at 35100 iteration is 936.2668755377819
The cost at 35150 iteration is 936.22395954796
The cost at 35200 iteration is 936.1810764957696
The cost at 35250 iteration is 936.1382263045463
The cost at 35300 iteration is 936.0954088978978
The cost at 35350 iteration is 936.052624199711
The cost at 35400 iteration is 936.009872134146
The cost at 35450 iteration is 935.9671526256385
The cost at 35500 iteration is 935.9244655988927
The cost at 35550 iteration is 935.8818109788925
The cost at 35600 iteration is 935.8391886908742
The cost at 35650 iteration is 935.7965986603518
The cost at 35700 iteration is 935.7540408131132
The cost at 35750 iteration is 935.7115150751947
The cost at 35800 iteration is 935.6690213729073
The cost at 35850 iteration is 935.6265596328182
The cost at 35900 iteration is 935.58412978176
The cost at 35950 iteration is 935.5417317468233
The cost at 36000 iteration is 935.4993654553513
The cost at 36050 iteration is 935.4570308349552
The cost at 36100 iteration is 935.4147278134888
The cost at 36150 iteration is 935.3724563190691
The cost at 36200 iteration is 935.3302162800643
The cost at 36250 iteration is 935.2880076250881
The cost at 36300 iteration is 935.2458302830165
The cost at 36350 iteration is 935.2036841829599
The cost at 36400 iteration is 935.1615692542873
The cost at 36450 iteration is 935.1194854266107
The cost at 36500 iteration is 935.0774326297845
The cost at 36550 iteration is 935.0354107939141
The cost at 36600 iteration is 934.993419849342
The cost at 36650 iteration is 934.9514597266539
The cost at 36700 iteration is 934.9095303566785
The cost at 36750 iteration is 934.867631670477
The cost at 36800 iteration is 934.8257635993542
The cost at 36850 iteration is 934.7839260748534
The cost at 36900 iteration is 934.7421190287481
The cost at 36950 iteration is 934.700342393051
The cost at 37000 iteration is 934.658596100003
The cost at 37050 iteration is 934.6168800820868
The cost at 37100 iteration is 934.5751942720055
The cost at 37150 iteration is 934.5335386026977
The cost at 37200 iteration is 934.491913007334
The cost at 37250 iteration is 934.4503174193035
The cost at 37300 iteration is 934.4087517722328
The cost at 37350 iteration is 934.3672159999643
The cost at 37400 iteration is 934.3257100365767
The cost at 37450 iteration is 934.2842338163587
The cost at 37500 iteration is 934.2427872738308
The cost at 37550 iteration is 934.2013703437328
The cost at 37600 iteration is 934.1599829610225
The cost at 37650 iteration is 934.118625060882
The cost at 37700 iteration is 934.0772965787063
The cost at 37750 iteration is 934.0359974501087
The cost at 37800 iteration is 933.9947276109236
The cost at 37850 iteration is 933.9534869971928
The cost at 37900 iteration is 933.9122755451817
The cost at 37950 iteration is 933.8710931913581
The cost at 38000 iteration is 933.8299398724138
The cost at 38050 iteration is 933.788815525237
The cost at 38100 iteration is 933.7477200869441
The cost at 38150 iteration is 933.706653494846
The cost at 38200 iteration is 933.6656156864702
The cost at 38250 iteration is 933.6246065995473
The cost at 38300 iteration is 933.5836261720184
The cost at 38350 iteration is 933.5426743420215
The cost at 38400 iteration is 933.5017510479132
The cost at 38450 iteration is 933.4608562282394
The cost at 38500 iteration is 933.4199898217604
The cost at 38550 iteration is 933.3791517674296
The cost at 38600 iteration is 933.3383420044069
The cost at 38650 iteration is 933.2975604720472
The cost at 38700 iteration is 933.256807109908
The cost at 38750 iteration is 933.2160818577463
The cost at 38800 iteration is 933.1753846555108
The cost at 38850 iteration is 933.1347154433528
The cost at 38900 iteration is 933.0940741616142
The cost at 38950 iteration is 933.0534607508347
The cost at 39000 iteration is 933.0128751517475
The cost at 39050 iteration is 932.9723173052749
The cost at 39100 iteration is 932.9317871525374
The cost at 39150 iteration is 932.8912846348433
The cost at 39200 iteration is 932.8508096936907
The cost at 39250 iteration is 932.8103622707666
The cost at 39300 iteration is 932.7699423079524
The cost at 39350 iteration is 932.7295497473091
The cost at 39400 iteration is 932.6891845310884
The cost at 39450 iteration is 932.6488466017342
The cost at 39500 iteration is 932.6085359018643
The cost at 39550 iteration is 932.5682523742911
The cost at 39600 iteration is 932.5279959620037
The cost at 39650 iteration is 932.4877666081787
The cost at 39700 iteration is 932.4475642561761
The cost at 39750 iteration is 932.4073888495308
The cost at 39800 iteration is 932.3672403319645
The cost at 39850 iteration is 932.3271186473773
The cost at 39900 iteration is 932.2870237398491
The cost at 39950 iteration is 932.2469555536311
The cost at 40000 iteration is 932.206914033162
The cost at 40050 iteration is 932.1668991230573
The cost at 40100 iteration is 932.1269107680957
The cost at 40150 iteration is 932.0869489132469
The cost at 40200 iteration is 932.047013503648
The cost at 40250 iteration is 932.0071044846079
The cost at 40300 iteration is 931.967221801611
The cost at 40350 iteration is 931.9273654003166
The cost at 40400 iteration is 931.887535226554
The cost at 40450 iteration is 931.8477312263186
The cost at 40500 iteration is 931.8079533457836
The cost at 40550 iteration is 931.7682015312884
The cost at 40600 iteration is 931.7284757293415
The cost at 40650 iteration is 931.6887758866188
The cost at 40700 iteration is 931.649101949964
The cost at 40750 iteration is 931.6094538663858
The cost at 40800 iteration is 931.569831583065
The cost at 40850 iteration is 931.5302350473418
The cost at 40900 iteration is 931.4906642067227
The cost at 40950 iteration is 931.4511190088793
The cost at 41000 iteration is 931.4115994016444
The cost at 41050 iteration is 931.3721053330139
The cost at 41100 iteration is 931.3326367511506
The cost at 41150 iteration is 931.2931936043725
The cost at 41200 iteration is 931.2537758411579
The cost at 41250 iteration is 931.2143834101512
The cost at 41300 iteration is 931.175016260154
The cost at 41350 iteration is 931.1356743401216
The cost at 41400 iteration is 931.0963575991724
The cost at 41450 iteration is 931.0570659865842
The cost at 41500 iteration is 931.0177994517826
The cost at 41550 iteration is 930.9785579443585
The cost at 41600 iteration is 930.9393414140542
The cost at 41650 iteration is 930.9001498107732
The cost at 41700 iteration is 930.8609830845621
The cost at 41750 iteration is 930.8218411856268
The cost at 41800 iteration is 930.7827240643269
The cost at 41850 iteration is 930.7436316711803
The cost at 41900 iteration is 930.7045639568472
The cost at 41950 iteration is 930.6655208721396
The cost at 42000 iteration is 930.6265023680259
The cost at 42050 iteration is 930.5875083956226
The cost at 42100 iteration is 930.5485389061939
The cost at 42150 iteration is 930.5095938511548

The cost at 42200 iteration is 930.4706731820678
The cost at 42250 iteration is 930.431776850643
The cost at 42300 iteration is 930.3929048087382
The cost at 42350 iteration is 930.3540570083557
The cost at 42400 iteration is 930.3152334016484
The cost at 42450 iteration is 930.2764339409107
The cost at 42500 iteration is 930.2376585785848
The cost at 42550 iteration is 930.198907267253
The cost at 42600 iteration is 930.1601799596459
The cost at 42650 iteration is 930.1214766086325
The cost at 42700 iteration is 930.0827971672293
The cost at 42750 iteration is 930.0441415885929
The cost at 42800 iteration is 930.0055098260209
The cost at 42850 iteration is 929.9669018329545
The cost at 42900 iteration is 929.9283175629713
The cost at 42950 iteration is 929.8897569697906
The cost at 43000 iteration is 929.8512200072709
The cost at 43050 iteration is 929.8127066294101
The cost at 43100 iteration is 929.7742167903452
The cost at 43150 iteration is 929.7357504443517
The cost at 43200 iteration is 929.6973075458403
The cost at 43250 iteration is 929.6588880493531
The cost at 43300 iteration is 929.6204919095829
The cost at 43350 iteration is 929.582119081344
The cost at 43400 iteration is 929.543769519595
The cost at 43450 iteration is 929.5054431794214
The cost at 43500 iteration is 929.4671400160552
The cost at 43550 iteration is 929.4288599848413
The cost at 43600 iteration is 929.3906030412842
The cost at 43650 iteration is 929.3523691409986
The cost at 43700 iteration is 929.3141582397425
The cost at 43750 iteration is 929.2759702934048
The cost at 43800 iteration is 929.2378052580018
The cost at 43850 iteration is 929.1996630896863
The cost at 43900 iteration is 929.1615437447366
The cost at 43950 iteration is 929.1234471795616
The cost at 44000 iteration is 929.0853733506971
The cost at 44050 iteration is 929.0473222148147
The cost at 44100 iteration is 929.009293728708
The cost at 44150 iteration is 928.9712878492996
The cost at 44200 iteration is 928.9333045336439
The cost at 44250 iteration is 928.8953437389177
The cost at 44300 iteration is 928.8574054224182
The cost at 44350 iteration is 928.819489541585
The cost at 44400 iteration is 928.781596053967
The cost at 44450 iteration is 928.7437249172509
The cost at 44500 iteration is 928.7058760892362
The cost at 44550 iteration is 928.6680495278545
The cost at 44600 iteration is 928.6302451911581
The cost at 44650 iteration is 928.5924630373235
The cost at 44700 iteration is 928.5547030246515
The cost at 44750 iteration is 928.5169651115604
The cost at 44800 iteration is 928.4792492565929
The cost at 44850 iteration is 928.441555418416
The cost at 44900 iteration is 928.4038835558125
The cost at 44950 iteration is 928.3662336276899
The cost at 45000 iteration is 928.3286055930737
The cost at 45050 iteration is 928.2909994111136
The cost at 45100 iteration is 928.2534150410665
The cost at 45150 iteration is 928.2158524423216
The cost at 45200 iteration is 928.1783115743814
The cost at 45250 iteration is 928.1407923968628
The cost at 45300 iteration is 928.1032948695073
The cost at 45350 iteration is 928.0658189521664
The cost at 45400 iteration is 928.0283646048142
The cost at 45450 iteration is 927.9909317875378
The cost at 45500 iteration is 927.9535204605369
The cost at 45550 iteration is 927.9161305841357
The cost at 45600 iteration is 927.8787621187663
The cost at 45650 iteration is 927.8414150249779
The cost at 45700 iteration is 927.8040892634314
The cost at 45750 iteration is 927.7667847949049
The cost at 45800 iteration is 927.7295015802873
The cost at 45850 iteration is 927.6922395805846
The cost at 45900 iteration is 927.6549987569123
The cost at 45950 iteration is 927.6177790704941
The cost at 46000 iteration is 927.5805804826763
The cost at 46050 iteration is 927.543402954901
The cost at 46100 iteration is 927.5062464487401
The cost at 46150 iteration is 927.4691109258598
The cost at 46200 iteration is 927.4319963480443
The cost at 46250 iteration is 927.3949026771902
The cost at 46300 iteration is 927.3578298752929
The cost at 46350 iteration is 927.3207779044712
The cost at 46400 iteration is 927.2837467269408
The cost at 46450 iteration is 927.2467363050303
The cost at 46500 iteration is 927.20974660118
The cost at 46550 iteration is 927.1727775779294
The cost at 46600 iteration is 927.1358291979311
The cost at 46650 iteration is 927.0989014239451
The cost at 46700 iteration is 927.0619942188324
The cost at 46750 iteration is 927.0251075455656
The cost at 46800 iteration is 926.9882413672194
The cost at 46850 iteration is 926.951395646979
The cost at 46900 iteration is 926.9145703481271
The cost at 46950 iteration is 926.8777654340565
The cost at 47000 iteration is 926.8409808682622
The cost at 47050 iteration is 926.8042166143468
The cost at 47100 iteration is 926.7674726360046
The cost at 47150 iteration is 926.7307488970514
The cost at 47200 iteration is 926.6940453613895
The cost at 47250 iteration is 926.6573619930363
The cost at 47300 iteration is 926.620698756098
The cost at 47350 iteration is 926.5840556147948
The cost at 47400 iteration is 926.5474325334402
The cost at 47450 iteration is 926.5108294764564
The cost at 47500 iteration is 926.4742464083596
The cost at 47550 iteration is 926.4376832937676
The cost at 47600 iteration is 926.4011400973977
The cost at 47650 iteration is 926.3646167840745
The cost at 47700 iteration is 926.3281133187106
The cost at 47750 iteration is 926.2916296663253
The cost at 47800 iteration is 926.2551657920314
The cost at 47850 iteration is 926.2187216610481
The cost at 47900 iteration is 926.1822972386828
The cost at 47950 iteration is 926.1458924903463
The cost at 48000 iteration is 926.1095073815483
The cost at 48050 iteration is 926.0731418778907
The cost at 48100 iteration is 926.0367959450717
The cost at 48150 iteration is 926.0004695488946
The cost at 48200 iteration is 925.9641626552491
The cost at 48250 iteration is 925.927875230123
The cost at 48300 iteration is 925.8916072396005
The cost at 48350 iteration is 925.855358649863
The cost at 48400 iteration is 925.8191294271866
The cost at 48450 iteration is 925.7829195379363
The cost at 48500 iteration is 925.7467289485746
The cost at 48550 iteration is 925.7105576256611
The cost at 48600 iteration is 925.6744055358425
The cost at 48650 iteration is 925.6382726458633
The cost at 48700 iteration is 925.602158922563
The cost at 48750 iteration is 925.5660643328629
The cost at 48800 iteration is 925.5299888437903
The cost at 48850 iteration is 925.4939324224533
The cost at 48900 iteration is 925.4578950360602
The cost at 48950 iteration is 925.4218766519073
The cost at 49000 iteration is 925.3858772373768
The cost at 49050 iteration is 925.3498967599481
The cost at 49100 iteration is 925.3139351871885
The cost at 49150 iteration is 925.2779924867623
The cost at 49200 iteration is 925.2420686264086
The cost at 49250 iteration is 925.20616357397
The cost at 49300 iteration is 925.1702772973689
The cost at 49350 iteration is 925.1344097646265
The cost at 49400 iteration is 925.0985609438444
The cost at 49450 iteration is 925.0627308032097
The cost at 49500 iteration is 925.0269193110109
The cost at 49550 iteration is 924.9911264356143
The cost at 49600 iteration is 924.9553521454716
The cost at 49650 iteration is 924.9195964091333
The cost at 49700 iteration is 924.8838591952212
The cost at 49750 iteration is 924.8481404724533
The cost at 49800 iteration is 924.81244020964
The cost at 49850 iteration is 924.7767583756613
The cost at 49900 iteration is 924.7410949394961
The cost at 49950 iteration is 924.7054498702043
The cost at 50000 iteration is 924.6698231369293
The cost at 50050 iteration is 924.6342147089018
The cost at 50100 iteration is 924.5986245554401
The cost at 50150 iteration is 924.5630526459349
The cost at 50200 iteration is 924.5274989498804
The cost at 50250 iteration is 924.491963436836
The cost at 50300 iteration is 924.4564460764537
The cost at 50350 iteration is 924.4209468384687
The cost at 50400 iteration is 924.3854656926982
The cost at 50450 iteration is 924.3500026090414
The cost at 50500 iteration is 924.314557557483
The cost at 50550 iteration is 924.2791305080784

The cost at 50600 iteration is 924.2437214309842
The cost at 50650 iteration is 924.2083302964227
The cost at 50700 iteration is 924.1729570747041
The cost at 50750 iteration is 924.1376017362196
The cost at 50800 iteration is 924.1022642514395
The cost at 50850 iteration is 924.0669445909152
The cost at 50900 iteration is 924.031642725281
The cost at 50950 iteration is 923.9963586252472
The cost at 51000 iteration is 923.9610922616065
The cost at 51050 iteration is 923.9258436052327
The cost at 51100 iteration is 923.8906126270747
The cost at 51150 iteration is 923.8553992981596
The cost at 51200 iteration is 923.8202035895997
The cost at 51250 iteration is 923.7850254725844
The cost at 51300 iteration is 923.7498649183759
The cost at 51350 iteration is 923.7147218983187
The cost at 51400 iteration is 923.6795963838342
The cost at 51450 iteration is 923.644488346424
The cost at 51500 iteration is 923.6093977576586
The cost at 51550 iteration is 923.5743245891945
The cost at 51600 iteration is 923.5392688127654
The cost at 51650 iteration is 923.5042304001734
The cost at 51700 iteration is 923.4692093233045
The cost at 51750 iteration is 923.4342055541138
The cost at 51800 iteration is 923.3992190646397
The cost at 51850 iteration is 923.3642498269899
The cost at 51900 iteration is 923.3292978133569
The cost at 51950 iteration is 923.294362995995
The cost at 52000 iteration is 923.2594453472391
The cost at 52050 iteration is 923.2245448395036
The cost at 52100 iteration is 923.189661445273
The cost at 52150 iteration is 923.1547951371059
The cost at 52200 iteration is 923.1199458876331
The cost at 52250 iteration is 923.0851136695593
The cost at 52300 iteration is 923.0502984556713
The cost at 52350 iteration is 923.0155002188143
The cost at 52400 iteration is 922.9807189319218
The cost at 52450 iteration is 922.9459545679879
The cost at 52500 iteration is 922.911207100087
The cost at 52550 iteration is 922.8764765013608
The cost at 52600 iteration is 922.8417627450219
The cost at 52650 iteration is 922.8070658043631
The cost at 52700 iteration is 922.772385652741
The cost at 52750 iteration is 922.737722263585
The cost at 52800 iteration is 922.7030756104018
The cost at 52850 iteration is 922.6684456667582
The cost at 52900 iteration is 922.6338324062993
The cost at 52950 iteration is 922.5992358027406
The cost at 53000 iteration is 922.5646558298614
The cost at 53050 iteration is 922.5300924615193
The cost at 53100 iteration is 922.4955456716388
The cost at 53150 iteration is 922.4610154342116
The cost at 53200 iteration is 922.4265017233001
The cost at 53250 iteration is 922.3920045130367
The cost at 53300 iteration is 922.3575237776204
The cost at 53350 iteration is 922.323059491325
The cost at 53400 iteration is 922.2886116284857
The cost at 53450 iteration is 922.2541801635087
The cost at 53500 iteration is 922.219765070868
The cost at 53550 iteration is 922.1853663251061
The cost at 53600 iteration is 922.1509839008363
The cost at 53650 iteration is 922.1166177727283
The cost at 53700 iteration is 922.0822679155341
The cost at 53750 iteration is 922.0479343040612
The cost at 53800 iteration is 922.0136169131918
The cost at 53850 iteration is 921.9793157178652
The cost at 53900 iteration is 921.945030693098
The cost at 53950 iteration is 921.9107618139635
The cost at 54000 iteration is 921.8765090556061
The cost at 54050 iteration is 921.8422723932382
The cost at 54100 iteration is 921.8080518021311
The cost at 54150 iteration is 921.7738472576259
The cost at 54200 iteration is 921.7396587351283
The cost at 54250 iteration is 921.7054862101105
The cost at 54300 iteration is 921.6713296581052
The cost at 54350 iteration is 921.637189054709
The cost at 54400 iteration is 921.6030643755903
The cost at 54450 iteration is 921.5689555964769
The cost at 54500 iteration is 921.5348626931581
The cost at 54550 iteration is 921.5007856414925
The cost at 54600 iteration is 921.4667244173978
The cost at 54650 iteration is 921.4326789968568
The cost at 54700 iteration is 921.3986493559154
The cost at 54750 iteration is 921.3646354706824
The cost at 54800 iteration is 921.3306373173285
The cost at 54850 iteration is 921.296654872089
The cost at 54900 iteration is 921.2626881112592
The cost at 54950 iteration is 921.2287370112006
The cost at 55000 iteration is 921.1948015483309
The cost at 55050 iteration is 921.1608816991318
The cost at 55100 iteration is 921.1269774401494
The cost at 55150 iteration is 921.0930887479894
The cost at 55200 iteration is 921.0592155993166
The cost at 55250 iteration is 921.0253579708618
The cost at 55300 iteration is 920.9915158394092
The cost at 55350 iteration is 920.9576891818141
The cost at 55400 iteration is 920.9238779749809
The cost at 55450 iteration is 920.8900821958806
The cost at 55500 iteration is 920.8563018215456
The cost at 55550 iteration is 920.8225368290628
The cost at 55600 iteration is 920.7887871955851
The cost at 55650 iteration is 920.7550528983211
The cost at 55700 iteration is 920.7213339145372
The cost at 55750 iteration is 920.6876302215653
The cost at 55800 iteration is 920.6539417967889
The cost at 55850 iteration is 920.6202686176568
The cost at 55900 iteration is 920.5866106616695
The cost at 55950 iteration is 920.5529679063925
The cost at 56000 iteration is 920.5193403294454
The cost at 56050 iteration is 920.485727908511
The cost at 56100 iteration is 920.452130621323
The cost at 56150 iteration is 920.4185484456773
The cost at 56200 iteration is 920.3849813594245
The cost at 56250 iteration is 920.3514293404783
The cost at 56300 iteration is 920.317892366805
The cost at 56350 iteration is 920.284370416425
The cost at 56400 iteration is 920.2508634674241
The cost at 56450 iteration is 920.2173714979394
The cost at 56500 iteration is 920.1838944861621
The cost at 56550 iteration is 920.1504324103474
The cost at 56600 iteration is 920.116985248797
The cost at 56650 iteration is 920.0835529798761
The cost at 56700 iteration is 920.0501355820022
The cost at 56750 iteration is 920.016733033654
The cost at 56800 iteration is 919.9833453133575
The cost at 56850 iteration is 919.9499723996995
The cost at 56900 iteration is 919.9166142713177
The cost at 56950 iteration is 919.8832709069121
The cost at 57000 iteration is 919.8499422852294
The cost at 57050 iteration is 919.8166283850738
The cost at 57100 iteration is 919.783329185307
The cost at 57150 iteration is 919.7500446648426
The cost at 57200 iteration is 919.7167748026477
The cost at 57250 iteration is 919.6835195777428
The cost at 57300 iteration is 919.6502789692074
The cost at 57350 iteration is 919.6170529561657
The cost at 57400 iteration is 919.5838415178065
The cost at 57450 iteration is 919.55064463336
The cost at 57500 iteration is 919.5174622821207
The cost at 57550 iteration is 919.4842944434272
The cost at 57600 iteration is 919.451141096679
The cost at 57650 iteration is 919.4180022213193
The cost at 57700 iteration is 919.3848777968515
The cost at 57750 iteration is 919.3517678028297
The cost at 57800 iteration is 919.3186722188555
The cost at 57850 iteration is 919.2855910245879
The cost at 57900 iteration is 919.2525241997386
The cost at 57950 iteration is 919.2194717240629
The cost at 58000 iteration is 919.1864335773805
The cost at 58050 iteration is 919.1534097395504
The cost at 58100 iteration is 919.1204001904886
The cost at 58150 iteration is 919.0874049101625
The cost at 58200 iteration is 919.0544238785913
The cost at 58250 iteration is 919.0214570758353
The cost at 58300 iteration is 918.988504482024
The cost at 58350 iteration is 918.9555660773216
The cost at 58400 iteration is 918.9226418419453
The cost at 58450 iteration is 918.8897317561704
The cost at 58500 iteration is 918.8568358003145
The cost at 58550 iteration is 918.8239539547466
The cost at 58600 iteration is 918.7910861998879
The cost at 58650 iteration is 918.7582325162089
The cost at 58700 iteration is 918.7253928842283
The cost at 58750 iteration is 918.6925672845111
The cost at 58800 iteration is 918.6597556976755
The cost at 58850 iteration is 918.6269581043905
The cost at 58900 iteration is 918.5941744853694
The cost at 58950 iteration is 918.5614048213793

The cost at 59000 iteration is 918.5286490932259
The cost at 59050 iteration is 918.4959072817788
The cost at 59100 iteration is 918.4631793679403
The cost at 59150 iteration is 918.4304653326711
The cost at 59200 iteration is 918.3977651569755
The cost at 59250 iteration is 918.3650788219111
The cost at 59300 iteration is 918.3324063085707
The cost at 59350 iteration is 918.2997475981106
The cost at 59400 iteration is 918.2671026717225
The cost at 59450 iteration is 918.2344715106519
The cost at 59500 iteration is 918.2018540961883
The cost at 59550 iteration is 918.1692504096686
The cost at 59600 iteration is 918.1366604324777
The cost at 59650 iteration is 918.1040841460485
The cost at 59700 iteration is 918.0715215318573
The cost at 59750 iteration is 918.038972571426
The cost at 59800 iteration is 918.00643724633
The cost at 59850 iteration is 917.9739155381825
The cost at 59900 iteration is 917.9414074286464
The cost at 59950 iteration is 917.908912899431
The cost at 60000 iteration is 917.8764319322908
The cost at 60050 iteration is 917.843964509024
The cost at 60100 iteration is 917.8115106114784
The cost at 60150 iteration is 917.7790702215425
The cost at 60200 iteration is 917.7466433211539
The cost at 60250 iteration is 917.7142298922948
The cost at 60300 iteration is 917.6818299169903
The cost at 60350 iteration is 917.6494433773113
The cost at 60400 iteration is 917.6170702553713
The cost at 60450 iteration is 917.5847105333324
The cost at 60500 iteration is 917.5523641933988
The cost at 60550 iteration is 917.5200312178193
The cost at 60600 iteration is 917.4877115888893
The cost at 60650 iteration is 917.45540528894
The cost at 60700 iteration is 917.4231123003591
The cost at 60750 iteration is 917.3908326055666
The cost at 60800 iteration is 917.3585661870324
The cost at 60850 iteration is 917.326313027267
The cost at 60900 iteration is 917.2940731088282
The cost at 60950 iteration is 917.2618464143135
The cost at 61000 iteration is 917.2296329263614
The cost at 61050 iteration is 917.1974326276617
The cost at 61100 iteration is 917.1652455009391
The cost at 61150 iteration is 917.133071528962
The cost at 61200 iteration is 917.1009106945456
The cost at 61250 iteration is 917.0687629805473
The cost at 61300 iteration is 917.0366283698581
The cost at 61350 iteration is 917.0045068454226
The cost at 61400 iteration is 916.9723983902236
The cost at 61450 iteration is 916.9403029872818
The cost at 61500 iteration is 916.9082206196658
The cost at 61550 iteration is 916.8761512704804
The cost at 61600 iteration is 916.844094922879
The cost at 61650 iteration is 916.8120515600448
The cost at 61700 iteration is 916.7800211652186
The cost at 61750 iteration is 916.7480037216686
The cost at 61800 iteration is 916.7159992127112
The cost at 61850 iteration is 916.6840076217005
The cost at 61900 iteration is 916.6520289320342
The cost at 61950 iteration is 916.6200631271444
The cost at 62000 iteration is 916.5881101905165
The cost at 62050 iteration is 916.5561701056648
The cost at 62100 iteration is 916.5242428561482
The cost at 62150 iteration is 916.4923284255655
The cost at 62200 iteration is 916.4604267975545
The cost at 62250 iteration is 916.4285379557961
The cost at 62300 iteration is 916.3966618840103
The cost at 62350 iteration is 916.3647985659547
The cost at 62400 iteration is 916.3329479854266
The cost at 62450 iteration is 916.3011101262668
The cost at 62500 iteration is 916.2692849723514
The cost at 62550 iteration is 916.2374725075965
The cost at 62600 iteration is 916.2056727159631
The cost at 62650 iteration is 916.1738855814403
The cost at 62700 iteration is 916.1421110880665
The cost at 62750 iteration is 916.1103492199106
The cost at 62800 iteration is 916.0785999610905
The cost at 62850 iteration is 916.0468632957549
The cost at 62900 iteration is 916.0151392080891
The cost at 62950 iteration is 915.9834276823254
The cost at 63000 iteration is 915.9517287027285
The cost at 63050 iteration is 915.9200422536021
The cost at 63100 iteration is 915.8883683192885
The cost at 63150 iteration is 915.8567068841681
The cost at 63200 iteration is 915.82505793266
The cost at 63250 iteration is 915.7934214492178
The cost at 63300 iteration is 915.7617974183374
The cost at 63350 iteration is 915.7301858245486
The cost at 63400 iteration is 915.6985866524226
The cost at 63450 iteration is 915.6669998865606
The cost at 63500 iteration is 915.6354255116121
The cost at 63550 iteration is 915.60386351225
The cost at 63600 iteration is 915.5723138731961
The cost at 63650 iteration is 915.540776579206
The cost at 63700 iteration is 915.5092516150663
The cost at 63750 iteration is 915.4777389656044
The cost at 63800 iteration is 915.4462386156913
The cost at 63850 iteration is 915.4147505502185
The cost at 63900 iteration is 915.383274754129
The cost at 63950 iteration is 915.3518112123962
The cost at 64000 iteration is 915.3203599100278
The cost at 64050 iteration is 915.2889208320684
The cost at 64100 iteration is 915.2574939636007
The cost at 64150 iteration is 915.2260792897395
The cost at 64200 iteration is 915.1946767956409
The cost at 64250 iteration is 915.1632864664929
The cost at 64300 iteration is 915.1319082875182
The cost at 64350 iteration is 915.1005422439761
The cost at 64400 iteration is 915.0691883211647
The cost at 64450 iteration is 915.0378465044115
The cost at 64500 iteration is 915.0065167790788
The cost at 64550 iteration is 914.975199130572
The cost at 64600 iteration is 914.9438935443245
The cost at 64650 iteration is 914.9126000058031
The cost at 64700 iteration is 914.8813185005187
The cost at 64750 iteration is 914.8500490140046
The cost at 64800 iteration is 914.8187915318351
The cost at 64850 iteration is 914.787546039622
The cost at 64900 iteration is 914.7563125230037
The cost at 64950 iteration is 914.725090967661
The cost at 65000 iteration is 914.6938813593011
The cost at 65050 iteration is 914.6626836836674
The cost at 65100 iteration is 914.6314979265424
The cost at 65150 iteration is 914.6003240737375
The cost at 65200 iteration is 914.5691621110982
The cost at 65250 iteration is 914.5380120245038
The cost at 65300 iteration is 914.5068737998672
The cost at 65350 iteration is 914.4757474231343
The cost at 65400 iteration is 914.444632880291
The cost at 65450 iteration is 914.4135301573449
The cost at 65500 iteration is 914.3824392403417
The cost at 65550 iteration is 914.3513601153649
The cost at 65600 iteration is 914.3202927685255
The cost at 65650 iteration is 914.289237185965
The cost at 65700 iteration is 914.2581933538661
The cost at 65750 iteration is 914.2271612584369
The cost at 65800 iteration is 914.196140885922
The cost at 65850 iteration is 914.1651322225952
The cost at 65900 iteration is 914.1341352547679
The cost at 65950 iteration is 914.103149968776
The cost at 66000 iteration is 914.0721763509952
The cost at 66050 iteration is 914.0412143878286
The cost at 66100 iteration is 914.0102640657107
The cost at 66150 iteration is 913.9793253711158
The cost at 66200 iteration is 913.9483982905405
The cost at 66250 iteration is 913.9174828105145
The cost at 66300 iteration is 913.8865789176053
The cost at 66350 iteration is 913.8556865984067
The cost at 66400 iteration is 913.8248058395473
The cost at 66450 iteration is 913.7939366276801
The cost at 66500 iteration is 913.7630789494995
The cost at 66550 iteration is 913.732232791723
The cost at 66600 iteration is 913.701398141104
The cost at 66650 iteration is 913.6705749844261
The cost at 66700 iteration is 913.6397633084972
The cost at 66750 iteration is 913.6089631001677
The cost at 66800 iteration is 913.578174346312
The cost at 66850 iteration is 913.547397033831
The cost at 66900 iteration is 913.5166311496677
The cost at 66950 iteration is 913.4858766807816
The cost at 67000 iteration is 913.4551336141747
The cost at 67050 iteration is 913.4244019368766
The cost at 67100 iteration is 913.3936816359384
The cost at 67150 iteration is 913.3629726984524
The cost at 67200 iteration is 913.332275111535
The cost at 67250 iteration is 913.3015888623346
The cost at 67300 iteration is 913.2709139380277
The cost at 67350 iteration is 913.2402503258224

The cost at 67400 iteration is 913.2095980129559
The cost at 67450 iteration is 913.178956986696
The cost at 67500 iteration is 913.1483272343356
The cost at 67550 iteration is 913.1177087432052
The cost at 67600 iteration is 913.0871015006574
The cost at 67650 iteration is 913.0565054940757
The cost at 67700 iteration is 913.0259207108755
The cost at 67750 iteration is 912.995347138497
The cost at 67800 iteration is 912.9647847644125
The cost at 67850 iteration is 912.9342335761237
The cost at 67900 iteration is 912.9036935611634
The cost at 67950 iteration is 912.8731647070847
The cost at 68000 iteration is 912.8426470014746
The cost at 68050 iteration is 912.8121404319502
The cost at 68100 iteration is 912.7816449861551
The cost at 68150 iteration is 912.7511606517655
The cost at 68200 iteration is 912.7206874164774
The cost at 68250 iteration is 912.6902252680221
The cost at 68300 iteration is 912.6597741941588
The cost at 68350 iteration is 912.6293341826662
The cost at 68400 iteration is 912.5989052213667
The cost at 68450 iteration is 912.568487298097
The cost at 68500 iteration is 912.5380804007267
The cost at 68550 iteration is 912.5076845171551
The cost at 68600 iteration is 912.4772996353042
The cost at 68650 iteration is 912.4469257431305
The cost at 68700 iteration is 912.4165628286108
The cost at 68750 iteration is 912.3862108797531
The cost at 68800 iteration is 912.355869884596
The cost at 68850 iteration is 912.3255398311977
The cost at 68900 iteration is 912.2952207076515
The cost at 68950 iteration is 912.2649125020713
The cost at 69000 iteration is 912.2346152026029
The cost at 69050 iteration is 912.2043287974177
The cost at 69100 iteration is 912.1740532747114
The cost at 69150 iteration is 912.1437886227126
The cost at 69200 iteration is 912.1135348296684
The cost at 69250 iteration is 912.0832918838621
The cost at 69300 iteration is 912.0530597735954
The cost at 69350 iteration is 912.0228384872025
The cost at 69400 iteration is 911.9926280130344
The cost at 69450 iteration is 911.9624283394859
The cost at 69500 iteration is 911.9322394549629
The cost at 69550 iteration is 911.9020613479032
The cost at 69600 iteration is 911.8718940067669
The cost at 69650 iteration is 911.8417374200488
The cost at 69700 iteration is 911.8115915762625
The cost at 69750 iteration is 911.7814564639486
The cost at 69800 iteration is 911.7513320716729
The cost at 69850 iteration is 911.7212183880335
The cost at 69900 iteration is 911.6911154016453
The cost at 69950 iteration is 911.6610231011559
The cost at 70000 iteration is 911.6309414752344
The cost at 70050 iteration is 911.6008705125747
The cost at 70100 iteration is 911.5708102019013
The cost at 70150 iteration is 911.54076053196
The cost at 70200 iteration is 911.5107214915217
The cost at 70250 iteration is 911.480693069384
The cost at 70300 iteration is 911.4506752543704
The cost at 70350 iteration is 911.4206680353282
The cost at 70400 iteration is 911.3906714011296
The cost at 70450 iteration is 911.3606853406724
The cost at 70500 iteration is 911.3307098428778
The cost at 70550 iteration is 911.3007448966953
The cost at 70600 iteration is 911.2707904910972
The cost at 70650 iteration is 911.2408466150795
The cost at 70700 iteration is 911.2109132576634
The cost at 70750 iteration is 911.1809904078932
The cost at 70800 iteration is 911.1510780548402
The cost at 70850 iteration is 911.1211761876034
The cost at 70900 iteration is 911.0912847952955
The cost at 70950 iteration is 911.0614038670649
The cost at 71000 iteration is 911.0315333920769
The cost at 71050 iteration is 911.0016733595243
The cost at 71100 iteration is 910.9718237586219
The cost at 71150 iteration is 910.9419845786126
The cost at 71200 iteration is 910.9121558087538
The cost at 71250 iteration is 910.8823374383422
The cost at 71300 iteration is 910.852529456683
The cost at 71350 iteration is 910.8227318531108
The cost at 71400 iteration is 910.7929446169884
The cost at 71450 iteration is 910.7631677376958
The cost at 71500 iteration is 910.7334012046415
The cost at 71550 iteration is 910.703645007254
The cost at 71600 iteration is 910.6738991349828
The cost at 71650 iteration is 910.644163577307
The cost at 71700 iteration is 910.6144383237274
The cost at 71750 iteration is 910.5847233637671
The cost at 71800 iteration is 910.5550186869702
The cost at 71850 iteration is 910.5253242829049
The cost at 71900 iteration is 910.4956401411648
The cost at 71950 iteration is 910.4659662513641
The cost at 72000 iteration is 910.4363026031401
The cost at 72050 iteration is 910.406649186155
The cost at 72100 iteration is 910.3770059900902
The cost at 72150 iteration is 910.3473730046559
The cost at 72200 iteration is 910.3177502195762
The cost at 72250 iteration is 910.288137624604
The cost at 72300 iteration is 910.2585352095128
The cost at 72350 iteration is 910.2289429641022
The cost at 72400 iteration is 910.1993608781868
The cost at 72450 iteration is 910.1697889416081
The cost at 72500 iteration is 910.1402271442286
The cost at 72550 iteration is 910.1106754759368
The cost at 72600 iteration is 910.0811339266397
The cost at 72650 iteration is 910.0516024862645
The cost at 72700 iteration is 910.0220811447662
The cost at 72750 iteration is 909.9925698921135
The cost at 72800 iteration is 909.9630687183083
The cost at 72850 iteration is 909.9335776133607
The cost at 72900 iteration is 909.9040965673148
The cost at 72950 iteration is 909.8746255702303
The cost at 73000 iteration is 909.845164612188
The cost at 73050 iteration is 909.8157136832953
The cost at 73100 iteration is 909.7862727736715
The cost at 73150 iteration is 909.7568418734694
The cost at 73200 iteration is 909.7274209728583
The cost at 73250 iteration is 909.6980100620217
The cost at 73300 iteration is 909.6686091311764
The cost at 73350 iteration is 909.6392181705514
The cost at 73400 iteration is 909.6098371704029
The cost at 73450 iteration is 909.5804661210016
The cost at 73500 iteration is 909.5511050126429
The cost at 73550 iteration is 909.5217538356487
The cost at 73600 iteration is 909.4924125803515
The cost at 73650 iteration is 909.4630812371141
The cost at 73700 iteration is 909.433759796309
The cost at 73750 iteration is 909.4044482483417
The cost at 73800 iteration is 909.3751465836326
The cost at 73850 iteration is 909.3458547926226
The cost at 73900 iteration is 909.3165728657707
The cost at 73950 iteration is 909.2873007935578
The cost at 74000 iteration is 909.2580385664946
The cost at 74050 iteration is 909.2287861750989
The cost at 74100 iteration is 909.1995436099166
The cost at 74150 iteration is 909.1703108615094
The cost at 74200 iteration is 909.1410879204611
The cost at 74250 iteration is 909.1118747773816
The cost at 74300 iteration is 909.0826714228898
The cost at 74350 iteration is 909.0534778476273
The cost at 74400 iteration is 909.0242940422686
The cost at 74450 iteration is 908.9951199974914
The cost at 74500 iteration is 908.9659557040035
The cost at 74550 iteration is 908.9368011525262
The cost at 74600 iteration is 908.9076563338051
The cost at 74650 iteration is 908.8785212386042
The cost at 74700 iteration is 908.8493958577101
The cost at 74750 iteration is 908.8202801819199
The cost at 74800 iteration is 908.7911742020626
The cost at 74850 iteration is 908.7620779089757
The cost at 74900 iteration is 908.7329912935239
The cost at 74950 iteration is 908.7039143465889
The cost at 75000 iteration is 908.6748470590702
The cost at 75050 iteration is 908.6457894218877
The cost at 75100 iteration is 908.6167414259826
The cost at 75150 iteration is 908.5877030623077
The cost at 75200 iteration is 908.5586743218457
The cost at 75250 iteration is 908.5296551955952
The cost at 75300 iteration is 908.5006456745667
The cost at 75350 iteration is 908.4716457498014
The cost at 75400 iteration is 908.442655412345
The cost at 75450 iteration is 908.4136746532788
The cost at 75500 iteration is 908.3847034636872
The cost at 75550 iteration is 908.3557418346833
The cost at 75600 iteration is 908.3267897573953
The cost at 75650 iteration is 908.2978472229746
The cost at 75700 iteration is 908.2689142225837
The cost at 75750 iteration is 908.2399907474099

The cost at 75800 iteration is 908.2110767886531
The cost at 75850 iteration is 908.1821723375391
The cost at 75900 iteration is 908.1532773853062
The cost at 75950 iteration is 908.1243919232164
The cost at 76000 iteration is 908.0955159425438
The cost at 76050 iteration is 908.0666494345827
The cost at 76100 iteration is 908.037792390652
The cost at 76150 iteration is 908.0089448020792
The cost at 76200 iteration is 907.9801066602164
The cost at 76250 iteration is 907.9512779564292
The cost at 76300 iteration is 907.9224586821061
The cost at 76350 iteration is 907.893648828651
The cost at 76400 iteration is 907.8648483874856
The cost at 76450 iteration is 907.8360573500515
The cost at 76500 iteration is 907.807275707803
The cost at 76550 iteration is 907.7785034522176
The cost at 76600 iteration is 907.7497405747889
The cost at 76650 iteration is 907.7209870670296
The cost at 76700 iteration is 907.6922429204665
The cost at 76750 iteration is 907.6635081266451
The cost at 76800 iteration is 907.6347826771303
The cost at 76850 iteration is 907.606066563503
The cost at 76900 iteration is 907.5773597773621
The cost at 76950 iteration is 907.5486623103259
The cost at 77000 iteration is 907.5199741540266
The cost at 77050 iteration is 907.4912953001128
The cost at 77100 iteration is 907.4626257402576
The cost at 77150 iteration is 907.4339654661421
The cost at 77200 iteration is 907.4053144694692
The cost at 77250 iteration is 907.3766727419619
The cost at 77300 iteration is 907.348040275353
The cost at 77350 iteration is 907.3194170613987
The cost at 77400 iteration is 907.29080309187
The cost at 77450 iteration is 907.2621983585523
The cost at 77500 iteration is 907.2336028532546
The cost at 77550 iteration is 907.2050165677921
The cost at 77600 iteration is 907.1764394940093
The cost at 77650 iteration is 907.1478716237584
The cost at 77700 iteration is 907.1193129489111
The cost at 77750 iteration is 907.0907634613562
The cost at 77800 iteration is 907.0622231530001
The cost at 77850 iteration is 907.0336920157608
The cost at 77900 iteration is 907.0051700415817
The cost at 77950 iteration is 906.9766572224112
The cost at 78000 iteration is 906.9481535502243
The cost at 78050 iteration is 906.9196590170093
The cost at 78100 iteration is 906.8911736147688
The cost at 78150 iteration is 906.8626973355227
The cost at 78200 iteration is 906.8342301713071
The cost at 78250 iteration is 906.8057721141772
The cost at 78300 iteration is 906.777323156197
The cost at 78350 iteration is 906.748883289456
The cost at 78400 iteration is 906.720452506054
The cost at 78450 iteration is 906.6920307981082
The cost at 78500 iteration is 906.663618157751
The cost at 78550 iteration is 906.6352145771298
The cost at 78600 iteration is 906.6068200484135
The cost at 78650 iteration is 906.5784345637795
The cost at 78700 iteration is 906.5500581154281
The cost at 78750 iteration is 906.5216906955696
The cost at 78800 iteration is 906.4933322964303
The cost at 78850 iteration is 906.4649829102563
The cost at 78900 iteration is 906.4366425293078
The cost at 78950 iteration is 906.4083111458613
The cost at 79000 iteration is 906.3799887522047
The cost at 79050 iteration is 906.3516753406453
The cost at 79100 iteration is 906.3233709035027
The cost at 79150 iteration is 906.2950754331183
The cost at 79200 iteration is 906.2667889218457
The cost at 79250 iteration is 906.2385113620464
The cost at 79300 iteration is 906.2102427461105
The cost at 79350 iteration is 906.181983066432
The cost at 79400 iteration is 906.153732315427
The cost at 79450 iteration is 906.1254904855259
The cost at 79500 iteration is 906.0972575691669
The cost at 79550 iteration is 906.0690335588187
The cost at 79600 iteration is 906.0408184469499
The cost at 79650 iteration is 906.0126122260526
The cost at 79700 iteration is 905.9844148886281
The cost at 79750 iteration is 905.9562264271973
The cost at 79800 iteration is 905.928046834298
The cost at 79850 iteration is 905.8998761024758
The cost at 79900 iteration is 905.8717142242933
The cost at 79950 iteration is 905.843561192334
The cost at 80000 iteration is 905.8154169991901
The cost at 80050 iteration is 905.7872816374692
The cost at 80100 iteration is 905.7591550997957
The cost at 80150 iteration is 905.7310373788052
The cost at 80200 iteration is 905.7029284671526
The cost at 80250 iteration is 905.6748283575029
The cost at 80300 iteration is 905.6467370425362
The cost at 80350 iteration is 905.6186545149552
The cost at 80400 iteration is 905.5905807674636
The cost at 80450 iteration is 905.5625157927874
The cost at 80500 iteration is 905.5344595836693
The cost at 80550 iteration is 905.5064121328592
The cost at 80600 iteration is 905.4783734331256
The cost at 80650 iteration is 905.4503434772522
The cost at 80700 iteration is 905.4223222580343
The cost at 80750 iteration is 905.3943097682816
The cost at 80800 iteration is 905.366306000821
The cost at 80850 iteration is 905.3383109484882
The cost at 80900 iteration is 905.3103246041401
The cost at 80950 iteration is 905.2823469606399
The cost at 81000 iteration is 905.2543780108668
The cost at 81050 iteration is 905.2264177477233
The cost at 81100 iteration is 905.1984661641097
The cost at 81150 iteration is 905.1705232529538
The cost at 81200 iteration is 905.142589007194
The cost at 81250 iteration is 905.1146634197714
The cost at 81300 iteration is 905.0867464836596
The cost at 81350 iteration is 905.0588381918305
The cost at 81400 iteration is 905.0309385372764
The cost at 81450 iteration is 905.0030475130053
The cost at 81500 iteration is 904.9751651120356
The cost at 81550 iteration is 904.9472913273995
The cost at 81600 iteration is 904.9194261521399
The cost at 81650 iteration is 904.8915695793178
The cost at 81700 iteration is 904.8637216020065
The cost at 81750 iteration is 904.8358822132942
The cost at 81800 iteration is 904.8080514062781
The cost at 81850 iteration is 904.7802291740724
The cost at 81900 iteration is 904.7524155098048
The cost at 81950 iteration is 904.7246104066116
The cost at 82000 iteration is 904.6968138576494
The cost at 82050 iteration is 904.6690258560831
The cost at 82100 iteration is 904.6412463950913
The cost at 82150 iteration is 904.6134754678695
The cost at 82200 iteration is 904.5857130676193
The cost at 82250 iteration is 904.5579591875621
The cost at 82300 iteration is 904.5302138209322
The cost at 82350 iteration is 904.5024769609702
The cost at 82400 iteration is 904.4747486009381
The cost at 82450 iteration is 904.4470287341051
The cost at 82500 iteration is 904.4193173537502
The cost at 82550 iteration is 904.3916144531812
The cost at 82600 iteration is 904.363920025699
The cost at 82650 iteration is 904.3362340646271
The cost at 82700 iteration is 904.3085565633045
The cost at 82750 iteration is 904.280887515075
The cost at 82800 iteration is 904.2532269133009
The cost at 82850 iteration is 904.2255747513585
The cost at 82900 iteration is 904.197931022631
The cost at 82950 iteration is 904.1702957205144
The cost at 83000 iteration is 904.1426688384233
The cost at 83050 iteration is 904.1150503697838
The cost at 83100 iteration is 904.0874403080277
The cost at 83150 iteration is 904.0598386466072
The cost at 83200 iteration is 904.0322453789792
The cost at 83250 iteration is 904.0046604986234
The cost at 83300 iteration is 903.9770839990231
The cost at 83350 iteration is 903.9495158736739
The cost at 83400 iteration is 903.9219561160924
The cost at 83450 iteration is 903.894404719797
The cost at 83500 iteration is 903.866861678325
The cost at 83550 iteration is 903.8393269852235
The cost at 83600 iteration is 903.8118006340522
The cost at 83650 iteration is 903.7842826183842
The cost at 83700 iteration is 903.7567729318032
The cost at 83750 iteration is 903.7292715679014
The cost at 83800 iteration is 903.7017785202953
The cost at 83850 iteration is 903.6742937825976
The cost at 83900 iteration is 903.6468173484456
The cost at 83950 iteration is 903.6193492114786
The cost at 84000 iteration is 903.59188936536
The cost at 84050 iteration is 903.5644378037492
The cost at 84100 iteration is 903.5369945203335
The cost at 84150 iteration is 903.509559508801

The cost at 84200 iteration is 903.4821327628562
The cost at 84250 iteration is 903.4547142762149
The cost at 84300 iteration is 903.4273040426058
The cost at 84350 iteration is 903.399902055766
The cost at 84400 iteration is 903.3725083094437
The cost at 84450 iteration is 903.3451227974084
The cost at 84500 iteration is 903.3177455134272
The cost at 84550 iteration is 903.2903764512885
The cost at 84600 iteration is 903.2630156047907
The cost at 84650 iteration is 903.2356629677399
The cost at 84700 iteration is 903.208318533958
The cost at 84750 iteration is 903.1809822972749
The cost at 84800 iteration is 903.1536542515366
The cost at 84850 iteration is 903.1263343905969
The cost at 84900 iteration is 903.0990227083187
The cost at 84950 iteration is 903.0717191985849
The cost at 85000 iteration is 903.0444238552776
The cost at 85050 iteration is 903.0171366723042
The cost at 85100 iteration is 902.9898576435697
The cost at 85150 iteration is 902.9625867629984
The cost at 85200 iteration is 902.9353240245268
The cost at 85250 iteration is 902.908069422097
The cost at 85300 iteration is 902.8808229496685
The cost at 85350 iteration is 902.8535846012045
The cost at 85400 iteration is 902.8263543706826
The cost at 85450 iteration is 902.7991322520973
The cost at 85500 iteration is 902.7719182394457
The cost at 85550 iteration is 902.7447123267389
The cost at 85600 iteration is 902.7175145080015
The cost at 85650 iteration is 902.6903247772691
The cost at 85700 iteration is 902.6631431285797
The cost at 85750 iteration is 902.6359695559929
The cost at 85800 iteration is 902.6088040535736
The cost at 85850 iteration is 902.5816466153987
The cost at 85900 iteration is 902.5544972355573
The cost at 85950 iteration is 902.5273559081468
The cost at 86000 iteration is 902.5002226272785
The cost at 86050 iteration is 902.4730973870684
The cost at 86100 iteration is 902.4459801816528
The cost at 86150 iteration is 902.4188710051699
The cost at 86200 iteration is 902.3917698517728
The cost at 86250 iteration is 902.3646767156232
The cost at 86300 iteration is 902.3375915908966
The cost at 86350 iteration is 902.3105144717761
The cost at 86400 iteration is 902.283445352455
The cost at 86450 iteration is 902.2563842271398
The cost at 86500 iteration is 902.2293310900478
The cost at 86550 iteration is 902.2022859354015
The cost at 86600 iteration is 902.1752487574404
The cost at 86650 iteration is 902.1482195504079
The cost at 86700 iteration is 902.1211983085619
The cost at 86750 iteration is 902.0941850261759
The cost at 86800 iteration is 902.0671796975188
The cost at 86850 iteration is 902.0401823168869
The cost at 86900 iteration is 902.013192878573
The cost at 86950 iteration is 901.98621137689
The cost at 87000 iteration is 901.9592378061546
The cost at 87050 iteration is 901.932272160697
The cost at 87100 iteration is 901.9053144348569
The cost at 87150 iteration is 901.8783646229824
The cost at 87200 iteration is 901.8514227194332
The cost at 87250 iteration is 901.8244887185801
The cost at 87300 iteration is 901.7975626148013
The cost at 87350 iteration is 901.7706444024913
The cost at 87400 iteration is 901.7437340760451
The cost at 87450 iteration is 901.7168316298751
The cost at 87500 iteration is 901.6899370583983
The cost at 87550 iteration is 901.663050356048
The cost at 87600 iteration is 901.6361715172644
The cost at 87650 iteration is 901.6093005364926
The cost at 87700 iteration is 901.5824374081946
The cost at 87750 iteration is 901.5555821268414
The cost at 87800 iteration is 901.5287346869089
The cost at 87850 iteration is 901.5018950828918
The cost at 87900 iteration is 901.4750633092816
The cost at 87950 iteration is 901.4482393605899
The cost at 88000 iteration is 901.4214232313348
The cost at 88050 iteration is 901.3946149160449
The cost at 88100 iteration is 901.3678144092578
The cost at 88150 iteration is 901.3410217055185
The cost at 88200 iteration is 901.3142367993845
The cost at 88250 iteration is 901.287459685425
The cost at 88300 iteration is 901.2606903582138
The cost at 88350 iteration is 901.2339288123362
The cost at 88400 iteration is 901.2071750423872
The cost at 88450 iteration is 901.1804290429723
The cost at 88500 iteration is 901.1536908087038
The cost at 88550 iteration is 901.1269603342063
The cost at 88600 iteration is 901.1002376141131
The cost at 88650 iteration is 901.0735226430643
The cost at 88700 iteration is 901.0468154157176
The cost at 88750 iteration is 901.0201159267283
The cost at 88800 iteration is 900.9934241707657
The cost at 88850 iteration is 900.9667401425107
The cost at 88900 iteration is 900.9400638366554
The cost at 88950 iteration is 900.9133952478958
The cost at 89000 iteration is 900.8867343709389
The cost at 89050 iteration is 900.8600812005018
The cost at 89100 iteration is 900.8334357313106
The cost at 89150 iteration is 900.8067979581002
The cost at 89200 iteration is 900.7801678756134
The cost at 89250 iteration is 900.7535454786084
The cost at 89300 iteration is 900.7269307618399
The cost at 89350 iteration is 900.7003237200846
The cost at 89400 iteration is 900.6737243481213
The cost at 89450 iteration is 900.6471326407391
The cost at 89500 iteration is 900.6205485927388
The cost at 89550 iteration is 900.5939721989267
The cost at 89600 iteration is 900.5674034541158
The cost at 89650 iteration is 900.5408423531372
The cost at 89700 iteration is 900.514288890822
The cost at 89750 iteration is 900.487743062013
The cost at 89800 iteration is 900.4612048615644
The cost at 89850 iteration is 900.4346742843361
The cost at 89900 iteration is 900.4081513251981
The cost at 89950 iteration is 900.3816359790272
The cost at 90000 iteration is 900.3551282407135
The cost at 90050 iteration is 900.3286281051505
The cost at 90100 iteration is 900.3021355672444
The cost at 90150 iteration is 900.2756506219089
The cost at 90200 iteration is 900.2491732640669
The cost at 90250 iteration is 900.2227034886472
The cost at 90300 iteration is 900.1962412905906
The cost at 90350 iteration is 900.1697866648468
The cost at 90400 iteration is 900.1433396063691
The cost at 90450 iteration is 900.1169001101268
The cost at 90500 iteration is 900.0904681710915
The cost at 90550 iteration is 900.0640437842442
The cost at 90600 iteration is 900.0376269445802
The cost at 90650 iteration is 900.0112176470963
The cost at 90700 iteration is 899.984815886801
The cost at 90750 iteration is 899.9584216587087
The cost at 90800 iteration is 899.93203495785
The cost at 90850 iteration is 899.9056557792538
The cost at 90900 iteration is 899.8792841179634
The cost at 90950 iteration is 899.8529199690248
The cost at 91000 iteration is 899.8265633275022
The cost at 91050 iteration is 899.8002141884572
The cost at 91100 iteration is 899.7738725469701
The cost at 91150 iteration is 899.7475383981234
The cost at 91200 iteration is 899.7212117370059
The cost at 91250 iteration is 899.6948925587186
The cost at 91300 iteration is 899.6685808583685
The cost at 91350 iteration is 899.6422766310752
The cost at 91400 iteration is 899.6159798719626
The cost at 91450 iteration is 899.5896905761588
The cost at 91500 iteration is 899.5634087388106
The cost at 91550 iteration is 899.5371343550623
The cost at 91600 iteration is 899.510867420078
The cost at 91650 iteration is 899.4846079290149
The cost at 91700 iteration is 899.4583558770476
The cost at 91750 iteration is 899.4321112593611
The cost at 91800 iteration is 899.4058740711432
The cost at 91850 iteration is 899.3796443075917
The cost at 91900 iteration is 899.3534219639089
The cost at 91950 iteration is 899.327207035311
The cost at 92000 iteration is 899.3009995170197
The cost at 92050 iteration is 899.2747994042628
The cost at 92100 iteration is 899.2486066922785
The cost at 92150 iteration is 899.2224213763086
The cost at 92200 iteration is 899.1962434516103
The cost at 92250 iteration is 899.1700729134394
The cost at 92300 iteration is 899.1439097570709
The cost at 92350 iteration is 899.1177539777777
The cost at 92400 iteration is 899.0916055708433
The cost at 92450 iteration is 899.0654645315589
The cost at 92500 iteration is 899.0393308552271
The cost at 92550 iteration is 899.0132045371531

The cost at 92600 iteration is 898.9870855726523
The cost at 92650 iteration is 898.9609739570491
The cost at 92700 iteration is 898.9348696856703
The cost at 92750 iteration is 898.9087727538583
The cost at 92800 iteration is 898.8826831569572
The cost at 92850 iteration is 898.8566008903206
The cost at 92900 iteration is 898.8305259493085
The cost at 92950 iteration is 898.804458329289
The cost at 93000 iteration is 898.7783980256435
The cost at 93050 iteration is 898.7523450337499
The cost at 93100 iteration is 898.7262993490027
The cost at 93150 iteration is 898.7002609667957
The cost at 93200 iteration is 898.6742298825436
The cost at 93250 iteration is 898.6482060916518
The cost at 93300 iteration is 898.6221895895478
The cost at 93350 iteration is 898.5961803716569
The cost at 93400 iteration is 898.5701784334175
The cost at 93450 iteration is 898.5441837702689
The cost at 93500 iteration is 898.5181963776655
The cost at 93550 iteration is 898.4922162510671
The cost at 93600 iteration is 898.4662433859332
The cost at 93650 iteration is 898.4402777777418
The cost at 93700 iteration is 898.4143194219696
The cost at 93750 iteration is 898.3883683141111
The cost at 93800 iteration is 898.3624244496507
The cost at 93850 iteration is 898.3364878240997
The cost at 93900 iteration is 898.310558432961
The cost at 93950 iteration is 898.2846362717544
The cost at 94000 iteration is 898.2587213360032
The cost at 94050 iteration is 898.2328136212386
The cost at 94100 iteration is 898.2069131229973
The cost at 94150 iteration is 898.1810198368261
The cost at 94200 iteration is 898.1551337582744
The cost at 94250 iteration is 898.1292548829068
The cost at 94300 iteration is 898.1033832062848
The cost at 94350 iteration is 898.0775187239835
The cost at 94400 iteration is 898.0516614315869
The cost at 94450 iteration is 898.0258113246792
The cost at 94500 iteration is 897.9999683988548
The cost at 94550 iteration is 897.9741326497206
The cost at 94600 iteration is 897.9483040728796
The cost at 94650 iteration is 897.9224826639484
The cost at 94700 iteration is 897.8966684185508
The cost at 94750 iteration is 897.8708613323199
The cost at 94800 iteration is 897.8450614008891
The cost at 94850 iteration is 897.8192686199014
The cost at 94900 iteration is 897.7934829850091
The cost at 94950 iteration is 897.7677044918681
The cost at 95000 iteration is 897.7419331361436
The cost at 95050 iteration is 897.7161689135056
The cost at 95100 iteration is 897.690411819632
The cost at 95150 iteration is 897.6646618502087
The cost at 95200 iteration is 897.6389190009298
The cost at 95250 iteration is 897.6131832674869
The cost at 95300 iteration is 897.5874546455896
The cost at 95350 iteration is 897.5617331309503
The cost at 95400 iteration is 897.5360187192842
The cost at 95450 iteration is 897.5103114063174
The cost at 95500 iteration is 897.4846111877847
The cost at 95550 iteration is 897.4589180594235
The cost at 95600 iteration is 897.4332320169783
The cost at 95650 iteration is 897.4075530562014
The cost at 95700 iteration is 897.3818811728498
The cost at 95750 iteration is 897.3562163626934
The cost at 95800 iteration is 897.3305586214987
The cost at 95850 iteration is 897.3049079450475
The cost at 95900 iteration is 897.2792643291235
The cost at 95950 iteration is 897.2536277695181
The cost at 96000 iteration is 897.2279982620312
The cost at 96050 iteration is 897.2023758024646
The cost at 96100 iteration is 897.1767603866311
The cost at 96150 iteration is 897.1511520103486
The cost at 96200 iteration is 897.1255506694421
The cost at 96250 iteration is 897.0999563597408
The cost at 96300 iteration is 897.074369077078
The cost at 96350 iteration is 897.0487888173024
The cost at 96400 iteration is 897.0232155762667
The cost at 96450 iteration is 896.9976493498173
The cost at 96500 iteration is 896.9720901338264
The cost at 96550 iteration is 896.946537924158
The cost at 96600 iteration is 896.9209927166881
The cost at 96650 iteration is 896.895454507301
The cost at 96700 iteration is 896.8699232918813
The cost at 96750 iteration is 896.8443990663259
The cost at 96800 iteration is 896.8188818265337
The cost at 96850 iteration is 896.7933715684139
The cost at 96900 iteration is 896.7678682878754
The cost at 96950 iteration is 896.7423719808444
The cost at 97000 iteration is 896.7168826432408
The cost at 97050 iteration is 896.6914002709992
The cost at 97100 iteration is 896.6659248600585
The cost at 97150 iteration is 896.6404564063592
The cost at 97200 iteration is 896.6149949058544
The cost at 97250 iteration is 896.5895403545012
The cost at 97300 iteration is 896.564092748264
The cost at 97350 iteration is 896.5386520831082
The cost at 97400 iteration is 896.5132183550102
The cost at 97450 iteration is 896.4877915599513
The cost at 97500 iteration is 896.4623716939213
The cost at 97550 iteration is 896.4369587529092
The cost at 97600 iteration is 896.4115527329161
The cost at 97650 iteration is 896.3861536299496
The cost at 97700 iteration is 896.3607614400198
The cost at 97750 iteration is 896.3353761591424
The cost at 97800 iteration is 896.309997783343
The cost at 97850 iteration is 896.2846263086501
The cost at 97900 iteration is 896.2592617311007
The cost at 97950 iteration is 896.2339040467364
The cost at 98000 iteration is 896.208553251602
The cost at 98050 iteration is 896.1832093417514
The cost at 98100 iteration is 896.1578723132466
The cost at 98150 iteration is 896.1325421621502
The cost at 98200 iteration is 896.1072188845327
The cost at 98250 iteration is 896.0819024764761
The cost at 98300 iteration is 896.0565929340565
The cost at 98350 iteration is 896.031290253369
The cost at 98400 iteration is 896.0059944305026
The cost at 98450 iteration is 895.9807054615605
The cost at 98500 iteration is 895.955423342647
The cost at 98550 iteration is 895.930148069875
The cost at 98600 iteration is 895.9048796393641
The cost at 98650 iteration is 895.8796180472366
The cost at 98700 iteration is 895.8543632896203
The cost at 98750 iteration is 895.8291153626506
The cost at 98800 iteration is 895.8038742624707
The cost at 98850 iteration is 895.7786399852242
The cost at 98900 iteration is 895.7534125270639
The cost at 98950 iteration is 895.7281918841492
The cost at 99000 iteration is 895.7029780526428
The cost at 99050 iteration is 895.6777710287116
The cost at 99100 iteration is 895.6525708085323
The cost at 99150 iteration is 895.6273773882857
The cost at 99200 iteration is 895.6021907641596
The cost at 99250 iteration is 895.5770109323425
The cost at 99300 iteration is 895.5518378890347
The cost at 99350 iteration is 895.5266716304352
The cost at 99400 iteration is 895.5015121527533
The cost at 99450 iteration is 895.4763594522061
The cost at 99500 iteration is 895.4512135250119
The cost at 99550 iteration is 895.4260743673937
The cost at 99600 iteration is 895.4009419755857
The cost at 99650 iteration is 895.3758163458195
The cost at 99700 iteration is 895.3506974743401
The cost at 99750 iteration is 895.325585357393
The cost at 99800 iteration is 895.3004799912335
The cost at 99850 iteration is 895.2753813721165
The cost at 99900 iteration is 895.2502894963056
The cost at 99950 iteration is 895.2252043600698
The cost at 100000 iteration is 895.2001259596846
The cost at 100050 iteration is 895.1750542914315
The cost at 100100 iteration is 895.1499893515927
The cost at 100150 iteration is 895.1249311364589
The cost at 100200 iteration is 895.0998796423255
The cost at 100250 iteration is 895.0748348654961
The cost at 100300 iteration is 895.0497968022737
The cost at 100350 iteration is 895.0247654489744
The cost at 100400 iteration is 894.9997408019121
The cost at 100450 iteration is 894.9747228574107
The cost at 100500 iteration is 894.9497116117968
The cost at 100550 iteration is 894.9247070614057
The cost at 100600 iteration is 894.8997092025751
The cost at 100650 iteration is 894.8747180316475
The cost at 100700 iteration is 894.8497335449724
The cost at 100750 iteration is 894.8247557389044
The cost at 100800 iteration is 894.7997846098003
The cost at 100850 iteration is 894.7748201540279
The cost at 100900 iteration is 894.7498623679562
The cost at 100950 iteration is 894.7249112479584

The cost at 101000 iteration is 894.6999667904163
The cost at 101050 iteration is 894.6750289917138
The cost at 101100 iteration is 894.6500978482435
The cost at 101150 iteration is 894.625173356398
The cost at 101200 iteration is 894.600255512581
The cost at 101250 iteration is 894.5753443131946
The cost at 101300 iteration is 894.5504397546531
The cost at 101350 iteration is 894.5255418333721
The cost at 101400 iteration is 894.5006505457701
The cost at 101450 iteration is 894.4757658882743
The cost at 101500 iteration is 894.4508878573182
The cost at 101550 iteration is 894.4260164493348
The cost at 101600 iteration is 894.4011516607677
The cost at 101650 iteration is 894.376293488062
The cost at 101700 iteration is 894.3514419276689
The cost at 101750 iteration is 894.326596976046
The cost at 101800 iteration is 894.3017586296522
The cost at 101850 iteration is 894.2769268849556
The cost at 101900 iteration is 894.2521017384264
The cost at 101950 iteration is 894.2272831865426
The cost at 102000 iteration is 894.2024712257838
The cost at 102050 iteration is 894.1776658526367
The cost at 102100 iteration is 894.1528670635911
The cost at 102150 iteration is 894.1280748551425
The cost at 102200 iteration is 894.1032892237939
The cost at 102250 iteration is 894.0785101660524
The cost at 102300 iteration is 894.0537376784231
The cost at 102350 iteration is 894.0289717574252
The cost at 102400 iteration is 894.0042123995773
The cost at 102450 iteration is 893.9794596014061
The cost at 102500 iteration is 893.9547133594397
The cost at 102550 iteration is 893.9299736702135
The cost at 102600 iteration is 893.905240530269
The cost at 102650 iteration is 893.8805139361492
The cost at 102700 iteration is 893.8557938844021
The cost at 102750 iteration is 893.8310803715829
The cost at 102800 iteration is 893.8063733942496
The cost at 102850 iteration is 893.7816729489647
The cost at 102900 iteration is 893.7569790322983
The cost at 102950 iteration is 893.7322916408234
The cost at 103000 iteration is 893.7076107711149
The cost at 103050 iteration is 893.6829364197605
The cost at 103100 iteration is 893.6582685833421
The cost at 103150 iteration is 893.6336072584545
The cost at 103200 iteration is 893.6089524416925
The cost at 103250 iteration is 893.5843041296558
The cost at 103300 iteration is 893.5596623189539
The cost at 103350 iteration is 893.5350270061952
The cost at 103400 iteration is 893.5103981879937
The cost at 103450 iteration is 893.4857758609716
The cost at 103500 iteration is 893.4611600217509
The cost at 103550 iteration is 893.4365506669625
The cost at 103600 iteration is 893.4119477932369
The cost at 103650 iteration is 893.387351397216
The cost at 103700 iteration is 893.3627614755403
The cost at 103750 iteration is 893.3381780248568
The cost at 103800 iteration is 893.3136010418191
The cost at 103850 iteration is 893.2890305230816
The cost at 103900 iteration is 893.2644664653058
The cost at 103950 iteration is 893.2399088651573
The cost at 104000 iteration is 893.2153577193064
The cost at 104050 iteration is 893.1908130244271
The cost at 104100 iteration is 893.1662747771973
The cost at 104150 iteration is 893.141742974304
The cost at 104200 iteration is 893.1172176124304
The cost at 104250 iteration is 893.0926986882705
The cost at 104300 iteration is 893.0681861985202
The cost at 104350 iteration is 893.0436801398886
The cost at 104400 iteration is 893.0191805090686
The cost at 104450 iteration is 892.9946873027806
The cost at 104500 iteration is 892.9702005177335
The cost at 104550 iteration is 892.9457201506472
The cost at 104600 iteration is 892.9212461982486
The cost at 104650 iteration is 892.89677865726
The cost at 104700 iteration is 892.8723175244168
The cost at 104750 iteration is 892.8478627964543
The cost at 104800 iteration is 892.8234144701171
The cost at 104850 iteration is 892.798972542144
The cost at 104900 iteration is 892.7745370092862
The cost at 104950 iteration is 892.7501078683034
The cost at 105000 iteration is 892.7256851159469
The cost at 105050 iteration is 892.7012687489819
The cost at 105100 iteration is 892.676858764176
The cost at 105150 iteration is 892.652455158299
The cost at 105200 iteration is 892.6280579281241
The cost at 105250 iteration is 892.603667070436
The cost at 105300 iteration is 892.5792825820132
The cost at 105350 iteration is 892.5549044596503
The cost at 105400 iteration is 892.5305327001332
The cost at 105450 iteration is 892.506167300264
The cost at 105500 iteration is 892.4818082568389
The cost at 105550 iteration is 892.4574555666652
The cost at 105600 iteration is 892.4331092265508
The cost at 105650 iteration is 892.4087692333139
The cost at 105700 iteration is 892.3844355837631
The cost at 105750 iteration is 892.36010827473
The cost at 105800 iteration is 892.3357873030344
The cost at 105850 iteration is 892.3114726655105
The cost at 105900 iteration is 892.2871643589887
The cost at 105950 iteration is 892.262862380311
The cost at 106000 iteration is 892.2385667263155
The cost at 106050 iteration is 892.2142773938526
The cost at 106100 iteration is 892.189994379772
The cost at 106150 iteration is 892.1657176809293
The cost at 106200 iteration is 892.1414472941834
The cost at 106250 iteration is 892.1171832163949
The cost at 106300 iteration is 892.0929254444382
The cost at 106350 iteration is 892.0686739751765
The cost at 106400 iteration is 892.0444288054875
The cost at 106450 iteration is 892.0201899322527
The cost at 106500 iteration is 891.995957352353
The cost at 106550 iteration is 891.9717310626787
The cost at 106600 iteration is 891.9475110601186
The cost at 106650 iteration is 891.9232973415692
The cost at 106700 iteration is 891.8990899039296
The cost at 106750 iteration is 891.8748887441063
The cost at 106800 iteration is 891.8506938590035
The cost at 106850 iteration is 891.8265052455329
The cost at 106900 iteration is 891.8023229006106
The cost at 106950 iteration is 891.7781468211542
The cost at 107000 iteration is 891.7539770040935
The cost at 107050 iteration is 891.7298134463492
The cost at 107100 iteration is 891.7056561448529
The cost at 107150 iteration is 891.6815050965457
The cost at 107200 iteration is 891.6573602983603
The cost at 107250 iteration is 891.6332217472427
The cost at 107300 iteration is 891.609089440139
The cost at 107350 iteration is 891.5849633740015
The cost at 107400 iteration is 891.5608435457834
The cost at 107450 iteration is 891.5367299524413
The cost at 107500 iteration is 891.5126225909449
The cost at 107550 iteration is 891.4885214582516
The cost at 107600 iteration is 891.4644265513407
The cost at 107650 iteration is 891.4403378671783
The cost at 107700 iteration is 891.4162554027441
The cost at 107750 iteration is 891.3921791550254
The cost at 107800 iteration is 891.3681091210016
The cost at 107850 iteration is 891.3440452976636
The cost at 107900 iteration is 891.3199876820066
The cost at 107950 iteration is 891.2959362710262
The cost at 108000 iteration is 891.2718910617225
The cost at 108050 iteration is 891.2478520510986
The cost at 108100 iteration is 891.2238192361677
The cost at 108150 iteration is 891.1997926139386
The cost at 108200 iteration is 891.175772181427
The cost at 108250 iteration is 891.1517579356536
The cost at 108300 iteration is 891.127749873641
The cost at 108350 iteration is 891.1037479924184
The cost at 108400 iteration is 891.0797522890128
The cost at 108450 iteration is 891.0557627604614
The cost at 108500 iteration is 891.0317794038001
The cost at 108550 iteration is 891.007802216076
The cost at 108600 iteration is 890.9838311943281
The cost at 108650 iteration is 890.9598663356097
The cost at 108700 iteration is 890.9359076369739
The cost at 108750 iteration is 890.9119550954753
The cost at 108800 iteration is 890.8880087081756
The cost at 108850 iteration is 890.864068472139
The cost at 108900 iteration is 890.8401343844322
The cost at 108950 iteration is 890.8162064421263
The cost at 109000 iteration is 890.7922846422987
The cost at 109050 iteration is 890.7683689820253
The cost at 109100 iteration is 890.7444594583881
The cost at 109150 iteration is 890.720556068474
The cost at 109200 iteration is 890.6966588093718

The cost at 109250 iteration is 890.672767678175
The cost at 109300 iteration is 890.6488826719792
The cost at 109350 iteration is 890.6250037878872
The cost at 109400 iteration is 890.6011310229976
The cost at 109450 iteration is 890.5772643744218
The cost at 109500 iteration is 890.5534038392701
The cost at 109550 iteration is 890.5295494146554
The cost at 109600 iteration is 890.5057010976959
The cost at 109650 iteration is 890.4818588855161
The cost at 109700 iteration is 890.4580227752346
The cost at 109750 iteration is 890.4341927639854
The cost at 109800 iteration is 890.4103688488991
The cost at 109850 iteration is 890.3865510271097
The cost at 109900 iteration is 890.3627392957558
The cost at 109950 iteration is 890.3389336519843
The cost at 110000 iteration is 890.3151340929352
The cost at 110050 iteration is 890.2913406157619
The cost at 110100 iteration is 890.2675532176144
The cost at 110150 iteration is 890.243771895651
The cost at 110200 iteration is 890.2199966470343
The cost at 110250 iteration is 890.1962274689205
The cost at 110300 iteration is 890.1724643584818
The cost at 110350 iteration is 890.1487073128851
The cost at 110400 iteration is 890.1249563293094
The cost at 110450 iteration is 890.1012114049214
The cost at 110500 iteration is 890.0774725369116
The cost at 110550 iteration is 890.0537397224593
The cost at 110600 iteration is 890.0300129587506
The cost at 110650 iteration is 890.0062922429772
The cost at 110700 iteration is 889.9825775723356
The cost at 110750 iteration is 889.9588689440207
The cost at 110800 iteration is 889.935166355232
The cost at 110850 iteration is 889.9114698031758
The cost at 110900 iteration is 889.8877792850567
The cost at 110950 iteration is 889.8640947980887
The cost at 111000 iteration is 889.840416339483
The cost at 111050 iteration is 889.8167439064582
The cost at 111100 iteration is 889.7930774962352
The cost at 111150 iteration is 889.7694171060398
The cost at 111200 iteration is 889.7457627330934
The cost at 111250 iteration is 889.7221143746312
The cost at 111300 iteration is 889.6984720278857
The cost at 111350 iteration is 889.6748356900955
The cost at 111400 iteration is 889.6512053585001
The cost at 111450 iteration is 889.6275810303455
The cost at 111500 iteration is 889.6039627028752
The cost at 111550 iteration is 889.5803503733414
The cost at 111600 iteration is 889.556744038995
The cost at 111650 iteration is 889.5331436970972
The cost at 111700 iteration is 889.5095493449072
The cost at 111750 iteration is 889.4859609796831
The cost at 111800 iteration is 889.462378598697
The cost at 111850 iteration is 889.4388021992163
The cost at 111900 iteration is 889.4152317785159
The cost at 111950 iteration is 889.3916673338693
The cost at 112000 iteration is 889.3681088625565
The cost at 112050 iteration is 889.3445563618609
The cost at 112100 iteration is 889.3210098290677
The cost at 112150 iteration is 889.2974692614654
The cost at 112200 iteration is 889.2739346563476
The cost at 112250 iteration is 889.2504060110084
The cost at 112300 iteration is 889.2268833227486
The cost at 112350 iteration is 889.2033665888641
The cost at 112400 iteration is 889.1798558066652
The cost at 112450 iteration is 889.1563509734572
The cost at 112500 iteration is 889.1328520865525
The cost at 112550 iteration is 889.1093591432611
The cost at 112600 iteration is 889.0858721409071
The cost at 112650 iteration is 889.0623910768055
The cost at 112700 iteration is 889.0389159482827
The cost at 112750 iteration is 889.0154467526625
The cost at 112800 iteration is 888.9919834872777
The cost at 112850 iteration is 888.9685261494596
The cost at 112900 iteration is 888.9450747365424
The cost at 112950 iteration is 888.9216292458685
The cost at 113000 iteration is 888.8981896747782
The cost at 113050 iteration is 888.8747560206157
The cost at 113100 iteration is 888.8513282807313
The cost at 113150 iteration is 888.8279064524731
The cost at 113200 iteration is 888.8044905331977
The cost at 113250 iteration is 888.7810805202612
The cost at 113300 iteration is 888.7576764110273
The cost at 113350 iteration is 888.7342782028541
The cost at 113400 iteration is 888.7108858931123
The cost at 113450 iteration is 888.6874994791688
The cost at 113500 iteration is 888.6641189583956
The cost at 113550 iteration is 888.6407443281694
The cost at 113600 iteration is 888.6173755858704
The cost at 113650 iteration is 888.594012728877
The cost at 113700 iteration is 888.5706557545743
The cost at 113750 iteration is 888.5473046603497
The cost at 113800 iteration is 888.5239594435959
The cost at 113850 iteration is 888.5006201017027
The cost at 113900 iteration is 888.4772866320704
The cost at 113950 iteration is 888.4539590320907
The cost at 114000 iteration is 888.4306372991744
The cost at 114050 iteration is 888.4073214307236
The cost at 114100 iteration is 888.384011424145
The cost at 114150 iteration is 888.3607072768499
The cost at 114200 iteration is 888.3374089862524
The cost at 114250 iteration is 888.3141165497702
The cost at 114300 iteration is 888.2908299648237
The cost at 114350 iteration is 888.2675492288353
The cost at 114400 iteration is 888.2442743392276
The cost at 114450 iteration is 888.2210052934319
The cost at 114500 iteration is 888.1977420888785
The cost at 114550 iteration is 888.1744847230043
The cost at 114600 iteration is 888.1512331932407
The cost at 114650 iteration is 888.1279874970356
The cost at 114700 iteration is 888.1047476318251
The cost at 114750 iteration is 888.0815135950576
The cost at 114800 iteration is 888.058285384183
The cost at 114850 iteration is 888.0350629966495
The cost at 114900 iteration is 888.011846429914
The cost at 114950 iteration is 887.9886356814325
The cost at 115000 iteration is 887.9654307486668
The cost at 115050 iteration is 887.9422316290758
The cost at 115100 iteration is 887.9190383201274
The cost at 115150 iteration is 887.8958508192932
The cost at 115200 iteration is 887.8726691240414
The cost at 115250 iteration is 887.8494932318426
The cost at 115300 iteration is 887.8263231401811
The cost at 115350 iteration is 887.8031588465302
The cost at 115400 iteration is 887.7800003483743
The cost at 115450 iteration is 887.7568476432024
The cost at 115500 iteration is 887.7337007284981
The cost at 115550 iteration is 887.7105596017524
The cost at 115600 iteration is 887.6874242604599
The cost at 115650 iteration is 887.664294702117
The cost at 115700 iteration is 887.641170924223
The cost at 115750 iteration is 887.618052924279
The cost at 115800 iteration is 887.5949406997925
The cost at 115850 iteration is 887.5718342482656
The cost at 115900 iteration is 887.5487335672118
The cost at 115950 iteration is 887.5256386541424
The cost at 116000 iteration is 887.5025495065742
The cost at 116050 iteration is 887.4794661220251
The cost at 116100 iteration is 887.4563884980146
The cost at 116150 iteration is 887.4333166320675
The cost at 116200 iteration is 887.410250521713
The cost at 116250 iteration is 887.3871901644758
The cost at 116300 iteration is 887.3641355578876
The cost at 116350 iteration is 887.3410866994874
The cost at 116400 iteration is 887.318043586806
The cost at 116450 iteration is 887.2950062173879
The cost at 116500 iteration is 887.2719745887729
The cost at 116550 iteration is 887.2489486985103
The cost at 116600 iteration is 887.225928544143
The cost at 116650 iteration is 887.2029141232227
The cost at 116700 iteration is 887.1799054333038
The cost at 116750 iteration is 887.1569024719425
The cost at 116800 iteration is 887.1339052366939
The cost at 116850 iteration is 887.110913725121
The cost at 116900 iteration is 887.0879279347902
The cost at 116950 iteration is 887.0649478632635
The cost at 117000 iteration is 887.0419735081131
The cost at 117050 iteration is 887.0190048669059
The cost at 117100 iteration is 886.996041937221
The cost at 117150 iteration is 886.9730847166306
The cost at 117200 iteration is 886.9501332027186
The cost at 117250 iteration is 886.9271873930642
The cost at 117300 iteration is 886.9042472852539
The cost at 117350 iteration is 886.88131287687
The cost at 117400 iteration is 886.858384165507
The cost at 117450 iteration is 886.8354611487567

The cost at 117500 iteration is 886.8125438242075
The cost at 117550 iteration is 886.7896321894676
The cost at 117600 iteration is 886.7667262421286
The cost at 117650 iteration is 886.7438259797989
The cost at 117700 iteration is 886.7209314000763
The cost at 117750 iteration is 886.6980425005746
The cost at 117800 iteration is 886.6751592788997
The cost at 117850 iteration is 886.6522817326679
The cost at 117900 iteration is 886.6294098594918
The cost at 117950 iteration is 886.6065436569879
The cost at 118000 iteration is 886.5836831227799
The cost at 118050 iteration is 886.5608282544903
The cost at 118100 iteration is 886.5379790497419
The cost at 118150 iteration is 886.5151355061619
The cost at 118200 iteration is 886.4922976213849
The cost at 118250 iteration is 886.4694653930388
The cost at 118300 iteration is 886.4466388187619
The cost at 118350 iteration is 886.4238178961909
The cost at 118400 iteration is 886.4010026229653
The cost at 118450 iteration is 886.3781929967275
The cost at 118500 iteration is 886.3553890151246
The cost at 118550 iteration is 886.3325906758045
The cost at 118600 iteration is 886.3097979764128
The cost at 118650 iteration is 886.2870109146064
The cost at 118700 iteration is 886.264229488038
The cost at 118750 iteration is 886.2414536943679
The cost at 118800 iteration is 886.2186835312523
The cost at 118850 iteration is 886.1959189963592
The cost at 118900 iteration is 886.1731600873437
The cost at 118950 iteration is 886.150406801881
The cost at 119000 iteration is 886.1276591376385
The cost at 119050 iteration is 886.1049170922861
The cost at 119100 iteration is 886.0821806635017
The cost at 119150 iteration is 886.0594498489605
The cost at 119200 iteration is 886.0367246463416
The cost at 119250 iteration is 886.0140050533256
The cost at 119300 iteration is 885.991291067599
The cost at 119350 iteration is 885.9685826868465
The cost at 119400 iteration is 885.9458799087575
The cost at 119450 iteration is 885.9231827310206
The cost at 119500 iteration is 885.9004911513339
The cost at 119550 iteration is 885.877805167392
The cost at 119600 iteration is 885.8551247768894
The cost at 119650 iteration is 885.8324499775316
The cost at 119700 iteration is 885.8097807670196
The cost at 119750 iteration is 885.7871171430579
The cost at 119800 iteration is 885.7644591033571
The cost at 119850 iteration is 885.7418066456244
The cost at 119900 iteration is 885.7191597675742
The cost at 119950 iteration is 885.6965184669186
The cost at 120000 iteration is 885.6738827413783
The cost at 120050 iteration is 885.6512525886682
The cost at 120100 iteration is 885.6286280065169
The cost at 120150 iteration is 885.6060089926399
The cost at 120200 iteration is 885.5833955447715
The cost at 120250 iteration is 885.560787660635
The cost at 120300 iteration is 885.5381853379643
The cost at 120350 iteration is 885.5155885744915
The cost at 120400 iteration is 885.4929973679504
The cost at 120450 iteration is 885.470411716084
The cost at 120500 iteration is 885.447831616629
The cost at 120550 iteration is 885.4252570673273
The cost at 120600 iteration is 885.4026880659237
The cost at 120650 iteration is 885.3801246101676
The cost at 120700 iteration is 885.3575666978066
The cost at 120750 iteration is 885.3350143265935
The cost at 120800 iteration is 885.312467494278
The cost at 120850 iteration is 885.2899261986224
The cost at 120900 iteration is 885.2673904373837
The cost at 120950 iteration is 885.2448602083157
The cost at 121000 iteration is 885.2223355091908
The cost at 121050 iteration is 885.1998163377702
The cost at 121100 iteration is 885.17730269182
The cost at 121150 iteration is 885.1547945691076
The cost at 121200 iteration is 885.1322919674116
The cost at 121250 iteration is 885.1097948845004
The cost at 121300 iteration is 885.0873033181532
The cost at 121350 iteration is 885.0648172661463
The cost at 121400 iteration is 885.0423367262644
The cost at 121450 iteration is 885.0198616962831
The cost at 121500 iteration is 884.9973921739943
The cost at 121550 iteration is 884.9749281571825
The cost at 121600 iteration is 884.9524696436395
The cost at 121650 iteration is 884.9300166311523
The cost at 121700 iteration is 884.9075691175173
The cost at 121750 iteration is 884.8851271005328
The cost at 121800 iteration is 884.8626905779952
The cost at 121850 iteration is 884.8402595477065
The cost at 121900 iteration is 884.8178340074617
The cost at 121950 iteration is 884.7954139550773
The cost at 122000 iteration is 884.7729993883545
The cost at 122050 iteration is 884.7505903051007
The cost at 122100 iteration is 884.7281867031272
The cost at 122150 iteration is 884.7057885802506
The cost at 122200 iteration is 884.6833959342857
The cost at 122250 iteration is 884.6610087630484
The cost at 122300 iteration is 884.6386270643611
The cost at 122350 iteration is 884.6162508360432
The cost at 122400 iteration is 884.5938800759192
The cost at 122450 iteration is 884.5715147818172
The cost at 122500 iteration is 884.5491549515629
The cost at 122550 iteration is 884.5268005829898
The cost at 122600 iteration is 884.5044516739295
The cost at 122650 iteration is 884.482108222216
The cost at 122700 iteration is 884.4597702256851
The cost at 122750 iteration is 884.437437682179
The cost at 122800 iteration is 884.4151105895356
The cost at 122850 iteration is 884.3927889456004
The cost at 122900 iteration is 884.3704727482149
The cost at 122950 iteration is 884.3481619952316
The cost at 123000 iteration is 884.3258566844971
The cost at 123050 iteration is 884.3035568138648
The cost at 123100 iteration is 884.2812623811824
The cost at 123150 iteration is 884.2589733843147
The cost at 123200 iteration is 884.2366898211118
The cost at 123250 iteration is 884.2144116894367
The cost at 123300 iteration is 884.192138987149
The cost at 123350 iteration is 884.1698717121185
The cost at 123400 iteration is 884.1476098622047
The cost at 123450 iteration is 884.1253534352778
The cost at 123500 iteration is 884.103102429208
The cost at 123550 iteration is 884.0808568418696
The cost at 123600 iteration is 884.0586166711355
The cost at 123650 iteration is 884.0363819148782
The cost at 123700 iteration is 884.0141525709804
The cost at 123750 iteration is 883.9919286373216
The cost at 123800 iteration is 883.9697101117829
The cost at 123850 iteration is 883.947496992247
The cost at 123900 iteration is 883.9252892766071
The cost at 123950 iteration is 883.903086962744
The cost at 124000 iteration is 883.8808900485499
The cost at 124050 iteration is 883.8586985319197
The cost at 124100 iteration is 883.836512410748
The cost at 124150 iteration is 883.8143316829281
The cost at 124200 iteration is 883.7921563463594
The cost at 124250 iteration is 883.7699863989436
The cost at 124300 iteration is 883.7478218385802
The cost at 124350 iteration is 883.7256626631778
The cost at 124400 iteration is 883.7035088706419
The cost at 124450 iteration is 883.681360458879
The cost at 124500 iteration is 883.6592174257971
The cost at 124550 iteration is 883.6370797693143
The cost at 124600 iteration is 883.6149474873401
The cost at 124650 iteration is 883.5928205777932
The cost at 124700 iteration is 883.570699038591
The cost at 124750 iteration is 883.5485828676535
The cost at 124800 iteration is 883.5264720629026
The cost at 124850 iteration is 883.5043666222637
The cost at 124900 iteration is 883.4822665436602
The cost at 124950 iteration is 883.4601718250221
The cost at 125000 iteration is 883.4380824642803
The cost at 125050 iteration is 883.415998459364
The cost at 125100 iteration is 883.3939198082109
The cost at 125150 iteration is 883.3718465087519
The cost at 125200 iteration is 883.3497785589257
The cost at 125250 iteration is 883.3277159566745
The cost at 125300 iteration is 883.3056586999373
The cost at 125350 iteration is 883.2836067866598
The cost at 125400 iteration is 883.2615602147819
The cost at 125450 iteration is 883.2395189822599
The cost at 125500 iteration is 883.217483087032
The cost at 125550 iteration is 883.1954525270581
The cost at 125600 iteration is 883.1734273002872
The cost at 125650 iteration is 883.1514074046748
The cost at 125700 iteration is 883.1293928381789

The cost at 125750 iteration is 883.1073835987567
The cost at 125800 iteration is 883.0853796843672
The cost at 125850 iteration is 883.0633810929747
The cost at 125900 iteration is 883.0413878225442
The cost at 125950 iteration is 883.0193998710411
The cost at 126000 iteration is 882.9974172364311
The cost at 126050 iteration is 882.9754399166881
The cost at 126100 iteration is 882.9534679097796
The cost at 126150 iteration is 882.9315012136833
The cost at 126200 iteration is 882.9095398263722
The cost at 126250 iteration is 882.8875837458245
The cost at 126300 iteration is 882.8656329700198
The cost at 126350 iteration is 882.8436874969366
The cost at 126400 iteration is 882.8217473245617
The cost at 126450 iteration is 882.7998124508766
The cost at 126500 iteration is 882.7778828738665
The cost at 126550 iteration is 882.7559585915235
The cost at 126600 iteration is 882.7340396018408
The cost at 126650 iteration is 882.7121259028027
The cost at 126700 iteration is 882.6902174924071
The cost at 126750 iteration is 882.6683143686502
The cost at 126800 iteration is 882.6464165295276
The cost at 126850 iteration is 882.6245239730412
The cost at 126900 iteration is 882.6026366971884
The cost at 126950 iteration is 882.5807546999738
The cost at 127000 iteration is 882.5588779794072
The cost at 127050 iteration is 882.537006533488
The cost at 127100 iteration is 882.5151403602277
The cost at 127150 iteration is 882.4932794576353
The cost at 127200 iteration is 882.4714238237246
The cost at 127250 iteration is 882.4495734565093
The cost at 127300 iteration is 882.4277283540061
The cost at 127350 iteration is 882.4058885142299
The cost at 127400 iteration is 882.3840539351992
The cost at 127450 iteration is 882.362224614936
The cost at 127500 iteration is 882.3404005514634
The cost at 127550 iteration is 882.3185817428057
The cost at 127600 iteration is 882.2967681869887
The cost at 127650 iteration is 882.2749598820434
The cost at 127700 iteration is 882.2531568259953
The cost at 127750 iteration is 882.231359016879
The cost at 127800 iteration is 882.2095664527255
The cost at 127850 iteration is 882.1877791315725
The cost at 127900 iteration is 882.1659970514554
The cost at 127950 iteration is 882.1442202104122
The cost at 128000 iteration is 882.1224486064826
The cost at 128050 iteration is 882.1006822377117
The cost at 128100 iteration is 882.078921102142
The cost at 128150 iteration is 882.0571651978181
The cost at 128200 iteration is 882.0354145227868
The cost at 128250 iteration is 882.0136690750996
The cost at 128300 iteration is 881.9919288528062
The cost at 128350 iteration is 881.9701938539571
The cost at 128400 iteration is 881.9484640766102
The cost at 128450 iteration is 881.9267395188184
The cost at 128500 iteration is 881.9050201786404
The cost at 128550 iteration is 881.8833060541338
The cost at 128600 iteration is 881.8615971433663
The cost at 128650 iteration is 881.8398934443885
The cost at 128700 iteration is 881.8181949552784
The cost at 128750 iteration is 881.7965016740919
The cost at 128800 iteration is 881.7748135989044
The cost at 128850 iteration is 881.7531307277819
The cost at 128900 iteration is 881.7314530587923
The cost at 128950 iteration is 881.7097805900149
The cost at 129000 iteration is 881.6881133195182
The cost at 129050 iteration is 881.6664512453862
The cost at 129100 iteration is 881.6447943656916
The cost at 129150 iteration is 881.6231426785153
The cost at 129200 iteration is 881.6014961819366
The cost at 129250 iteration is 881.5798548740436
The cost at 129300 iteration is 881.5582187529154
The cost at 129350 iteration is 881.536587816643
The cost at 129400 iteration is 881.5149620633105
The cost at 129450 iteration is 881.4933414910104
The cost at 129500 iteration is 881.471726097833
The cost at 129550 iteration is 881.4501158818725
The cost at 129600 iteration is 881.4285108412237
The cost at 129650 iteration is 881.4069109739813
The cost at 129700 iteration is 881.3853162782441
The cost at 129750 iteration is 881.3637267521091
The cost at 129800 iteration is 881.3421423936846
The cost at 129850 iteration is 881.3205632010682
The cost at 129900 iteration is 881.2989891723636
The cost at 129950 iteration is 881.2774203056811
The cost at 130000 iteration is 881.2558565991262
The cost at 130050 iteration is 881.2342980508059
The cost at 130100 iteration is 881.212744658838
The cost at 130150 iteration is 881.1911964213291
The cost at 130200 iteration is 881.1696533363952
The cost at 130250 iteration is 881.1481154021526
The cost at 130300 iteration is 881.1265826167212
The cost at 130350 iteration is 881.1050549782171
The cost at 130400 iteration is 881.0835324847611
The cost at 130450 iteration is 881.0620151344749
The cost at 130500 iteration is 881.0405029254874
The cost at 130550 iteration is 881.0189958559206
The cost at 130600 iteration is 880.997493923902
The cost at 130650 iteration is 880.9759971275608
The cost at 130700 iteration is 880.9545054650255
The cost at 130750 iteration is 880.9330189344307
The cost at 130800 iteration is 880.9115375339102
The cost at 130850 iteration is 880.8900612615982
The cost at 130900 iteration is 880.8685901156314
The cost at 130950 iteration is 880.8471240941471
The cost at 131000 iteration is 880.8256631952867
The cost at 131050 iteration is 880.804207417192
The cost at 131100 iteration is 880.7827567580055
The cost at 131150 iteration is 880.7613112158708
The cost at 131200 iteration is 880.7398707889351
The cost at 131250 iteration is 880.718435475348
The cost at 131300 iteration is 880.6970052732578
The cost at 131350 iteration is 880.6755801808105
The cost at 131400 iteration is 880.6541601961654
The cost at 131450 iteration is 880.6327453174722
The cost at 131500 iteration is 880.6113355428914
The cost at 131550 iteration is 880.589930870576
The cost at 131600 iteration is 880.5685312986828
The cost at 131650 iteration is 880.5471368253774
The cost at 131700 iteration is 880.5257474488186
The cost at 131750 iteration is 880.5043631671713
The cost at 131800 iteration is 880.4829839785975
The cost at 131850 iteration is 880.4616098812636
The cost at 131900 iteration is 880.4402408733433
The cost at 131950 iteration is 880.4188769529992
The cost at 132000 iteration is 880.3975181184065
The cost at 132050 iteration is 880.3761643677352
The cost at 132100 iteration is 880.3548156991621
The cost at 132150 iteration is 880.333472110861
The cost at 132200 iteration is 880.3121336010038
The cost at 132250 iteration is 880.2908001677778
The cost at 132300 iteration is 880.2694718093614
The cost at 132350 iteration is 880.2481485239352
The cost at 132400 iteration is 880.2268303096777
The cost at 132450 iteration is 880.2055171647766
The cost at 132500 iteration is 880.1842090874214
The cost at 132550 iteration is 880.1629060757978
The cost at 132600 iteration is 880.1416081280913
The cost at 132650 iteration is 880.1203152424958
The cost at 132700 iteration is 880.0990274172036
The cost at 132750 iteration is 880.0777446504069
The cost at 132800 iteration is 880.0564669403019
The cost at 132850 iteration is 880.0351942850838
The cost at 132900 iteration is 880.0139266829545
The cost at 132950 iteration is 879.9926641321075
The cost at 133000 iteration is 879.9714066307494
The cost at 133050 iteration is 879.9501541770773
The cost at 133100 iteration is 879.9289067693
The cost at 133150 iteration is 879.9076644056198
The cost at 133200 iteration is 879.8864270842477
The cost at 133250 iteration is 879.8651948033854
The cost at 133300 iteration is 879.8439675612494
The cost at 133350 iteration is 879.8227453560457
The cost at 133400 iteration is 879.8015281859906
The cost at 133450 iteration is 879.7803160492969
The cost at 133500 iteration is 879.7591089441814
The cost at 133550 iteration is 879.7379068688603
The cost at 133600 iteration is 879.7167098215505
The cost at 133650 iteration is 879.6955178004741
The cost at 133700 iteration is 879.6743308038548
The cost at 133750 iteration is 879.65314882991
The cost at 133800 iteration is 879.6319718768672
The cost at 133850 iteration is 879.6107999429526
The cost at 133900 iteration is 879.5896330263917
The cost at 133950 iteration is 879.5684711254166

The cost at 134000 iteration is 879.547314238252
The cost at 134050 iteration is 879.5261623631343
The cost at 134100 iteration is 879.5050154982938
The cost at 134150 iteration is 879.4838736419648
The cost at 134200 iteration is 879.4627367923855
The cost at 134250 iteration is 879.4416049477908
The cost at 134300 iteration is 879.4204781064209
The cost at 134350 iteration is 879.3993562665128
The cost at 134400 iteration is 879.3782394263117
The cost at 134450 iteration is 879.357127584057
The cost at 134500 iteration is 879.3360207379969
The cost at 134550 iteration is 879.3149188863736
The cost at 134600 iteration is 879.2938220274369
The cost at 134650 iteration is 879.2727301594336
The cost at 134700 iteration is 879.2516432806123
The cost at 134750 iteration is 879.2305613892269
The cost at 134800 iteration is 879.2094844835303
The cost at 134850 iteration is 879.1884125617757
The cost at 134900 iteration is 879.1673456222154
The cost at 134950 iteration is 879.1462836631124
The cost at 135000 iteration is 879.1252266827205
The cost at 135050 iteration is 879.1041746792987
The cost at 135100 iteration is 879.08312765111
The cost at 135150 iteration is 879.0620855964195
The cost at 135200 iteration is 879.0410485134865
The cost at 135250 iteration is 879.0200164005763
The cost at 135300 iteration is 878.998989255959
The cost at 135350 iteration is 878.9779670778986
The cost at 135400 iteration is 878.9569498646665
The cost at 135450 iteration is 878.9359376145329
The cost at 135500 iteration is 878.9149303257697
The cost at 135550 iteration is 878.8939279966512
The cost at 135600 iteration is 878.8729306254489
The cost at 135650 iteration is 878.8519382104452
The cost at 135700 iteration is 878.83095074991
The cost at 135750 iteration is 878.8099682421275
The cost at 135800 iteration is 878.7889906853756
The cost at 135850 iteration is 878.7680180779362
The cost at 135900 iteration is 878.7470504180912
The cost at 135950 iteration is 878.7260877041247
The cost at 136000 iteration is 878.7051299343248
The cost at 136050 iteration is 878.6841771069763
The cost at 136100 iteration is 878.6632292203692
The cost at 136150 iteration is 878.64228627279
The cost at 136200 iteration is 878.6213482625327
The cost at 136250 iteration is 878.6004151878857
The cost at 136300 iteration is 878.5794870471432
The cost at 136350 iteration is 878.5585638386059
The cost at 136400 iteration is 878.5376455605651
The cost at 136450 iteration is 878.5167322113197
The cost at 136500 iteration is 878.4958237891668
The cost at 136550 iteration is 878.4749202924079
The cost at 136600 iteration is 878.4540217193422
The cost at 136650 iteration is 878.4331280682776
The cost at 136700 iteration is 878.412239337513
The cost at 136750 iteration is 878.3913555253567
The cost at 136800 iteration is 878.3704766301141
The cost at 136850 iteration is 878.349602650095
The cost at 136900 iteration is 878.328733583608
The cost at 136950 iteration is 878.3078694289617
The cost at 137000 iteration is 878.2870101844702
The cost at 137050 iteration is 878.266155848448
The cost at 137100 iteration is 878.2453064192073
The cost at 137150 iteration is 878.2244618950625
The cost at 137200 iteration is 878.2036222743342
The cost at 137250 iteration is 878.1827875553402
The cost at 137300 iteration is 878.1619577363982
The cost at 137350 iteration is 878.1411328158317
The cost at 137400 iteration is 878.1203127919608
The cost at 137450 iteration is 878.0994976631113
The cost at 137500 iteration is 878.0786874276048
The cost at 137550 iteration is 878.0578820837711
The cost at 137600 iteration is 878.0370816299375
The cost at 137650 iteration is 878.0162860644292
The cost at 137700 iteration is 877.9954953855788
The cost at 137750 iteration is 877.9747095917184
The cost at 137800 iteration is 877.9539286811781
The cost at 137850 iteration is 877.9331526522926
The cost at 137900 iteration is 877.9123815033977
The cost at 137950 iteration is 877.8916152328286
The cost at 138000 iteration is 877.8708538389235
The cost at 138050 iteration is 877.8500973200205
The cost at 138100 iteration is 877.8293456744616
The cost at 138150 iteration is 877.8085989005897
The cost at 138200 iteration is 877.7878569967398
The cost at 138250 iteration is 877.7671199612641
The cost at 138300 iteration is 877.7463877925029
The cost at 138350 iteration is 877.7256604888048
The cost at 138400 iteration is 877.7049380485164
The cost at 138450 iteration is 877.6842204699861
The cost at 138500 iteration is 877.6635077515664
The cost at 138550 iteration is 877.6427998916055
The cost at 138600 iteration is 877.6220968884577
The cost at 138650 iteration is 877.6013987404797
The cost at 138700 iteration is 877.5807054460197
The cost at 138750 iteration is 877.5600170034382
The cost at 138800 iteration is 877.5393334110931
The cost at 138850 iteration is 877.5186546673433
The cost at 138900 iteration is 877.4979807705471
The cost at 138950 iteration is 877.4773117190678
The cost at 139000 iteration is 877.4566475112681
The cost at 139050 iteration is 877.4359881455073
The cost at 139100 iteration is 877.4153336201533
The cost at 139150 iteration is 877.394683933573
The cost at 139200 iteration is 877.3740390841338
The cost at 139250 iteration is 877.3533990702026
The cost at 139300 iteration is 877.3327638901508
The cost at 139350 iteration is 877.3121335423454
The cost at 139400 iteration is 877.291508025164
The cost at 139450 iteration is 877.2708873369792
The cost at 139500 iteration is 877.2502714761612
The cost at 139550 iteration is 877.2296604410908
The cost at 139600 iteration is 877.2090542301413
The cost at 139650 iteration is 877.188452841695
The cost at 139700 iteration is 877.1678562741289
The cost at 139750 iteration is 877.1472645258216
The cost at 139800 iteration is 877.1266775951584
The cost at 139850 iteration is 877.1060954805187
The cost at 139900 iteration is 877.0855181802917
The cost at 139950 iteration is 877.0649456928575
The cost at 140000 iteration is 877.0443780166081
The cost at 140050 iteration is 877.0238151499256
The cost at 140100 iteration is 877.0032570912016
The cost at 140150 iteration is 876.982703838828
The cost at 140200 iteration is 876.962155391194
The cost at 140250 iteration is 876.9416117466945
The cost at 140300 iteration is 876.9210729037167
The cost at 140350 iteration is 876.9005388606644
The cost at 140400 iteration is 876.8800096159268
The cost at 140450 iteration is 876.859485167903
The cost at 140500 iteration is 876.838965514993
The cost at 140550 iteration is 876.8184506555967
The cost at 140600 iteration is 876.797940588109
The cost at 140650 iteration is 876.7774353109403
The cost at 140700 iteration is 876.7569348224864
The cost at 140750 iteration is 876.7364391211555
The cost at 140800 iteration is 876.7159482053539
The cost at 140850 iteration is 876.6954620734862
The cost at 140900 iteration is 876.6749807239586
The cost at 140950 iteration is 876.6545041551828
The cost at 141000 iteration is 876.634032365566
The cost at 141050 iteration is 876.6135653535213
The cost at 141100 iteration is 876.5931031174621
The cost at 141150 iteration is 876.5726456557965
The cost at 141200 iteration is 876.5521929669487
The cost at 141250 iteration is 876.5317450493237
The cost at 141300 iteration is 876.5113019013452
The cost at 141350 iteration is 876.4908635214291
The cost at 141400 iteration is 876.4704299079935
The cost at 141450 iteration is 876.4500010594617
The cost at 141500 iteration is 876.4295769742542
The cost at 141550 iteration is 876.409157650793
The cost at 141600 iteration is 876.3887430875003
The cost at 141650 iteration is 876.3683332828025
The cost at 141700 iteration is 876.3479282351259
The cost at 141750 iteration is 876.3275279428984
The cost at 141800 iteration is 876.3071324045452
The cost at 141850 iteration is 876.2867416184981
The cost at 141900 iteration is 876.2663555831874
The cost at 141950 iteration is 876.2459742970423
The cost at 142000 iteration is 876.2255977584998
The cost at 142050 iteration is 876.2052259659897
The cost at 142100 iteration is 876.1848589179509
The cost at 142150 iteration is 876.1644966128168
The cost at 142200 iteration is 876.1441390490241

The cost at 142250 iteration is 876.1237862250133
The cost at 142300 iteration is 876.103438139222
The cost at 142350 iteration is 876.083094790091
The cost at 142400 iteration is 876.0627561760633
The cost at 142450 iteration is 876.0424222955785
The cost at 142500 iteration is 876.0220931470855
The cost at 142550 iteration is 876.001768729026
The cost at 142600 iteration is 875.9814490398444
The cost at 142650 iteration is 875.9611340779923
The cost at 142700 iteration is 875.9408238419135
The cost at 142750 iteration is 875.9205183300613
The cost at 142800 iteration is 875.9002175408837
The cost at 142850 iteration is 875.8799214728331
The cost at 142900 iteration is 875.8596301243616
The cost at 142950 iteration is 875.8393434939236
The cost at 143000 iteration is 875.8190615799724
The cost at 143050 iteration is 875.7987843809664
The cost at 143100 iteration is 875.7785118953602
The cost at 143150 iteration is 875.7582441216151
The cost at 143200 iteration is 875.7379810581846
The cost at 143250 iteration is 875.7177227035356
The cost at 143300 iteration is 875.6974690561245
The cost at 143350 iteration is 875.6772201144192
The cost at 143400 iteration is 875.6569758768738
The cost at 143450 iteration is 875.6367363419625
The cost at 143500 iteration is 875.6165015081455
The cost at 143550 iteration is 875.5962713738918
The cost at 143600 iteration is 875.5760459376675
The cost at 143650 iteration is 875.5558251979415
The cost at 143700 iteration is 875.5356091531853
The cost at 143750 iteration is 875.5153978018692
The cost at 143800 iteration is 875.4951911424648
The cost at 143850 iteration is 875.474989173446
The cost at 143900 iteration is 875.4547918932848
The cost at 143950 iteration is 875.4345993004606
The cost at 144000 iteration is 875.4144113934467
The cost at 144050 iteration is 875.3942281707177
The cost at 144100 iteration is 875.3740496307586
The cost at 144150 iteration is 875.353875772045
The cost at 144200 iteration is 875.3337065930566
The cost at 144250 iteration is 875.3135420922752
The cost at 144300 iteration is 875.2933822681863
The cost at 144350 iteration is 875.2732271192709
The cost at 144400 iteration is 875.2530766440137
The cost at 144450 iteration is 875.232930840903
The cost at 144500 iteration is 875.2127897084232
The cost at 144550 iteration is 875.1926532450601
The cost at 144600 iteration is 875.1725214493098
The cost at 144650 iteration is 875.1523943196545
The cost at 144700 iteration is 875.1322718545877
The cost at 144750 iteration is 875.1121540526026
The cost at 144800 iteration is 875.092040912192
The cost at 144850 iteration is 875.0719324318471
The cost at 144900 iteration is 875.0518286100688
The cost at 144950 iteration is 875.0317294453488
The cost at 145000 iteration is 875.0116349361839
The cost at 145050 iteration is 874.9915450810737
The cost at 145100 iteration is 874.9714598785167
The cost at 145150 iteration is 874.9513793270128
The cost at 145200 iteration is 874.9313034250688
The cost at 145250 iteration is 874.9112321711771
The cost at 145300 iteration is 874.8911655638481
The cost at 145350 iteration is 874.8711036015836
The cost at 145400 iteration is 874.8510462828888
The cost at 145450 iteration is 874.8309936062725
The cost at 145500 iteration is 874.8109455702382
The cost at 145550 iteration is 874.7909021732984
The cost at 145600 iteration is 874.7708634139592
The cost at 145650 iteration is 874.7508292907336
The cost at 145700 iteration is 874.7307998021297
The cost at 145750 iteration is 874.7107749466619
The cost at 145800 iteration is 874.6907547228428
The cost at 145850 iteration is 874.6707391291876
The cost at 145900 iteration is 874.6507281642138
The cost at 145950 iteration is 874.630721826434
The cost at 146000 iteration is 874.6107201143667
The cost at 146050 iteration is 874.5907230265311
The cost at 146100 iteration is 874.5707305614459
The cost at 146150 iteration is 874.5507427176344
The cost at 146200 iteration is 874.5307594936133
The cost at 146250 iteration is 874.5107808879083
The cost at 146300 iteration is 874.4908068990406
The cost at 146350 iteration is 874.4708375255369
The cost at 146400 iteration is 874.4508727659198
The cost at 146450 iteration is 874.4309126187192
The cost at 146500 iteration is 874.4109570824604
The cost at 146550 iteration is 874.3910061556721
The cost at 146600 iteration is 874.3710598368822
The cost at 146650 iteration is 874.3511181246237
The cost at 146700 iteration is 874.3311810174241
The cost at 146750 iteration is 874.3112485138221
The cost at 146800 iteration is 874.291320612344
The cost at 146850 iteration is 874.2713973115259
The cost at 146900 iteration is 874.2514786099061
The cost at 146950 iteration is 874.231564506017
The cost at 147000 iteration is 874.2116549983978
The cost at 147050 iteration is 874.1917500855874
The cost at 147100 iteration is 874.171849766123
The cost at 147150 iteration is 874.1519540385433
The cost at 147200 iteration is 874.1320629013946
The cost at 147250 iteration is 874.1121763532145
The cost at 147300 iteration is 874.0922943925491
The cost at 147350 iteration is 874.0724170179366
The cost at 147400 iteration is 874.0525442279284
The cost at 147450 iteration is 874.0326760210659
The cost at 147500 iteration is 874.0128123958982
The cost at 147550 iteration is 873.9929533509734
The cost at 147600 iteration is 873.9730988848397
The cost at 147650 iteration is 873.9532489960447
The cost at 147700 iteration is 873.9334036831402
The cost at 147750 iteration is 873.9135629446811
The cost at 147800 iteration is 873.8937267792156
The cost at 147850 iteration is 873.8738951852996
The cost at 147900 iteration is 873.8540681614847
The cost at 147950 iteration is 873.8342457063311
The cost at 148000 iteration is 873.814427818391
The cost at 148050 iteration is 873.7946144962234
The cost at 148100 iteration is 873.7748057383859
The cost at 148150 iteration is 873.7550015434391
The cost at 148200 iteration is 873.7352019099415
The cost at 148250 iteration is 873.7154068364533
The cost at 148300 iteration is 873.6956163215414
The cost at 148350 iteration is 873.6758303637599
The cost at 148400 iteration is 873.6560489616822
The cost at 148450 iteration is 873.6362721138677
The cost at 148500 iteration is 873.6164998188847
The cost at 148550 iteration is 873.5967320752978
The cost at 148600 iteration is 873.576968881674
The cost at 148650 iteration is 873.5572102365833
The cost at 148700 iteration is 873.5374561385967
The cost at 148750 iteration is 873.5177065862824
The cost at 148800 iteration is 873.4979615782127
The cost at 148850 iteration is 873.4782211129599
The cost at 148900 iteration is 873.4584851890967
The cost at 148950 iteration is 873.4387538051957
The cost at 149000 iteration is 873.4190269598346
The cost at 149050 iteration is 873.3993046515885
The cost at 149100 iteration is 873.3795868790327
The cost at 149150 iteration is 873.3598736407481
The cost at 149200 iteration is 873.3401649353116
The cost at 149250 iteration is 873.3204607613021
The cost at 149300 iteration is 873.3007611173008
The cost at 149350 iteration is 873.2810660018891
The cost at 149400 iteration is 873.2613754136511
The cost at 149450 iteration is 873.2416893511653
The cost at 149500 iteration is 873.222007813023
The cost at 149550 iteration is 873.2023307978035
The cost at 149600 iteration is 873.1826583040945
The cost at 149650 iteration is 873.1629903304831
The cost at 149700 iteration is 873.1433268755566
The cost at 149750 iteration is 873.1236679379058
The cost at 149800 iteration is 873.104013516119
The cost at 149850 iteration is 873.0843636087835
The cost at 149900 iteration is 873.0647182144977
The cost at 149950 iteration is 873.0450773318461
The cost at 150000 iteration is 873.0254409594265
The cost at 150050 iteration is 873.0058090958328
The cost at 150100 iteration is 872.9861817396618
The cost at 150150 iteration is 872.9665588895058
The cost at 150200 iteration is 872.9469405439603
The cost at 150250 iteration is 872.9273267016268
The cost at 150300 iteration is 872.9077173611054
The cost at 150350 iteration is 872.88811252099
The cost at 150400 iteration is 872.8685121798824
The cost at 150450 iteration is 872.8489163363905

The cost at 150500 iteration is 872.8293249891077
The cost at 150550 iteration is 872.8097381366376
The cost at 150600 iteration is 872.790155777591
The cost at 150650 iteration is 872.7705779105679
The cost at 150700 iteration is 872.7510045341758
The cost at 150750 iteration is 872.7314356470198
The cost at 150800 iteration is 872.7118712477064
The cost at 150850 iteration is 872.6923113348437
The cost at 150900 iteration is 872.672755907046
The cost at 150950 iteration is 872.6532049629183
The cost at 151000 iteration is 872.6336585010732
The cost at 151050 iteration is 872.614116520121
The cost at 151100 iteration is 872.5945790186786
The cost at 151150 iteration is 872.5750459953548
The cost at 151200 iteration is 872.5555174487668
The cost at 151250 iteration is 872.535993377527
The cost at 151300 iteration is 872.516473780256
The cost at 151350 iteration is 872.4969586555673
The cost at 151400 iteration is 872.4774480020808
The cost at 151450 iteration is 872.457941818413
The cost at 151500 iteration is 872.4384401031859
The cost at 151550 iteration is 872.41894285502
The cost at 151600 iteration is 872.3994500725323
The cost at 151650 iteration is 872.37996175435
The cost at 151700 iteration is 872.3604778990945
The cost at 151750 iteration is 872.3409985053902
The cost at 151800 iteration is 872.3215235718606
The cost at 151850 iteration is 872.3020530971331
The cost at 151900 iteration is 872.2825870798321
The cost at 151950 iteration is 872.2631255185881
The cost at 152000 iteration is 872.2436684120254
The cost at 152050 iteration is 872.2242157587756
The cost at 152100 iteration is 872.2047675574677
The cost at 152150 iteration is 872.1853238067334
The cost at 152200 iteration is 872.1658845052027
The cost at 152250 iteration is 872.146449651509
The cost at 152300 iteration is 872.1270192442857
The cost at 152350 iteration is 872.1075932821661
The cost at 152400 iteration is 872.0881717637865
The cost at 152450 iteration is 872.068754687784
The cost at 152500 iteration is 872.0493420527899
The cost at 152550 iteration is 872.0299338574457
The cost at 152600 iteration is 872.0105301003913
The cost at 152650 iteration is 871.991130780261
The cost at 152700 iteration is 871.9717358956999
The cost at 152750 iteration is 871.9523454453447
The cost at 152800 iteration is 871.9329594278407
The cost at 152850 iteration is 871.9135778418274
The cost at 152900 iteration is 871.89420068595
The cost at 152950 iteration is 871.8748279588511
The cost at 153000 iteration is 871.8554596591765
The cost at 153050 iteration is 871.8360957855743
The cost at 153100 iteration is 871.8167363366889
The cost at 153150 iteration is 871.7973813111657
The cost at 153200 iteration is 871.7780307076591
The cost at 153250 iteration is 871.7586845248097
The cost at 153300 iteration is 871.7393427612745
The cost at 153350 iteration is 871.7200054157018
The cost at 153400 iteration is 871.7006724867434
The cost at 153450 iteration is 871.6813439730546
The cost at 153500 iteration is 871.6620198732837
The cost at 153550 iteration is 871.6427001860858
The cost at 153600 iteration is 871.6233849101204
The cost at 153650 iteration is 871.604074044036
The cost at 153700 iteration is 871.5847675864964
The cost at 153750 iteration is 871.5654655361559
The cost at 153800 iteration is 871.5461678916679
The cost at 153850 iteration is 871.526874651702
The cost at 153900 iteration is 871.5075858149083
The cost at 153950 iteration is 871.4883013799493
The cost at 154000 iteration is 871.4690213454904
The cost at 154050 iteration is 871.4497457101926
The cost at 154100 iteration is 871.4304744727156
The cost at 154150 iteration is 871.4112076317275
The cost at 154200 iteration is 871.3919451858901
The cost at 154250 iteration is 871.3726871338695
The cost at 154300 iteration is 871.353433474332
The cost at 154350 iteration is 871.3341842059449
The cost at 154400 iteration is 871.314939327377
The cost at 154450 iteration is 871.2956988372945
The cost at 154500 iteration is 871.2764627343671
The cost at 154550 iteration is 871.2572310172704
The cost at 154600 iteration is 871.2380036846694
The cost at 154650 iteration is 871.2187807352374
The cost at 154700 iteration is 871.1995621676465
The cost at 154750 iteration is 871.1803479805719
The cost at 154800 iteration is 871.1611381726889
The cost at 154850 iteration is 871.1419327426688
The cost at 154900 iteration is 871.1227316891905
The cost at 154950 iteration is 871.1035350109283
The cost at 155000 iteration is 871.0843427065636
The cost at 155050 iteration is 871.0651547747703
The cost at 155100 iteration is 871.0459712142291
The cost at 155150 iteration is 871.0267920236174
The cost at 155200 iteration is 871.0076172016227
The cost at 155250 iteration is 870.9884467469176
The cost at 155300 iteration is 870.9692806581893
The cost at 155350 iteration is 870.9501189341184
The cost at 155400 iteration is 870.9309615733928
The cost at 155450 iteration is 870.9118085746917
The cost at 155500 iteration is 870.8926599367053
The cost at 155550 iteration is 870.8735156581142
The cost at 155600 iteration is 870.8543757376101
The cost at 155650 iteration is 870.8352401738786
The cost at 155700 iteration is 870.816108965607
The cost at 155750 iteration is 870.796982111486
The cost at 155800 iteration is 870.7778596102046
The cost at 155850 iteration is 870.7587414604527
The cost at 155900 iteration is 870.7396276609252
The cost at 155950 iteration is 870.7205182103121
The cost at 156000 iteration is 870.7014131073071
The cost at 156050 iteration is 870.682312350601
The cost at 156100 iteration is 870.6632159388926
The cost at 156150 iteration is 870.6441238708743
The cost at 156200 iteration is 870.625036145241
The cost at 156250 iteration is 870.6059527606958
The cost at 156300 iteration is 870.5868737159303
The cost at 156350 iteration is 870.567799009644
The cost at 156400 iteration is 870.5487286405356
The cost at 156450 iteration is 870.5296626073109
The cost at 156500 iteration is 870.5106009086642
The cost at 156550 iteration is 870.4915435432955
The cost at 156600 iteration is 870.4724905099131
The cost at 156650 iteration is 870.4534418072164
The cost at 156700 iteration is 870.4343974339101
The cost at 156750 iteration is 870.4153573886981
The cost at 156800 iteration is 870.396321670284
The cost at 156850 iteration is 870.3772902773774
The cost at 156900 iteration is 870.3582632086828
The cost at 156950 iteration is 870.3392404629084
The cost at 157000 iteration is 870.3202220387608
The cost at 157050 iteration is 870.3012079349534
The cost at 157100 iteration is 870.282198150189
The cost at 157150 iteration is 870.2631926831815
The cost at 157200 iteration is 870.2441915326465
The cost at 157250 iteration is 870.2251946972899
The cost at 157300 iteration is 870.2062021758245
The cost at 157350 iteration is 870.187213966971
The cost at 157400 iteration is 870.1682300694338
The cost at 157450 iteration is 870.1492504819327
The cost at 157500 iteration is 870.130275203184
The cost at 157550 iteration is 870.1113042319053
The cost at 157600 iteration is 870.092337566808
The cost at 157650 iteration is 870.0733752066177
The cost at 157700 iteration is 870.0544171500462
The cost at 157750 iteration is 870.0354633958208
The cost at 157800 iteration is 870.0165139426512
The cost at 157850 iteration is 869.9975687892656
The cost at 157900 iteration is 869.9786279343833
The cost at 157950 iteration is 869.9596913767291
The cost at 158000 iteration is 869.9407591150218
The cost at 158050 iteration is 869.9218311479873
The cost at 158100 iteration is 869.9029074743528
The cost at 158150 iteration is 869.883988092839
The cost at 158200 iteration is 869.8650730021757
The cost at 158250 iteration is 869.8461622010864
The cost at 158300 iteration is 869.8272556883046
The cost at 158350 iteration is 869.8083534625505
The cost at 158400 iteration is 869.789455522557
The cost at 158450 iteration is 869.7705618670537
The cost at 158500 iteration is 869.7516724947699
The cost at 158550 iteration is 869.7327874044394
The cost at 158600 iteration is 869.7139065947928
The cost at 158650 iteration is 869.6950300645605
The cost at 158700 iteration is 869.6761578124747

The cost at 158750 iteration is 869.6572898372763
The cost at 158800 iteration is 869.6384261376936
The cost at 158850 iteration is 869.6195667124642
The cost at 158900 iteration is 869.6007115603232
The cost at 158950 iteration is 869.5818606800118
The cost at 159000 iteration is 869.5630140702614
The cost at 159050 iteration is 869.5441717298143
The cost at 159100 iteration is 869.5253336574079
The cost at 159150 iteration is 869.5064998517796
The cost at 159200 iteration is 869.4876703116778
The cost at 159250 iteration is 869.4688450358364
The cost at 159300 iteration is 869.4500240229982
The cost at 159350 iteration is 869.4312072719079
The cost at 159400 iteration is 869.41239478131
The cost at 159450 iteration is 869.3935865499442
The cost at 159500 iteration is 869.3747825765571
The cost at 159550 iteration is 869.355982859895
The cost at 159600 iteration is 869.3371873987022
The cost at 159650 iteration is 869.3183961917281
The cost at 159700 iteration is 869.2996092377184
The cost at 159750 iteration is 869.2808265354232
The cost at 159800 iteration is 869.262048083588
The cost at 159850 iteration is 869.2432738809663
The cost at 159900 iteration is 869.2245039263059
The cost at 159950 iteration is 869.2057382183596
The cost at 160000 iteration is 869.1869767558755
The cost at 160050 iteration is 869.1682195376118
The cost at 160100 iteration is 869.1494665623162
The cost at 160150 iteration is 869.1307178287491
The cost at 160200 iteration is 869.111973335656
The cost at 160250 iteration is 869.0932330817991
The cost at 160300 iteration is 869.0744970659327
The cost at 160350 iteration is 869.055765286811
The cost at 160400 iteration is 869.0370377431962
The cost at 160450 iteration is 869.0183144338404
The cost at 160500 iteration is 868.9995953575088
The cost at 160550 iteration is 868.9808805129535
The cost at 160600 iteration is 868.9621698989406
The cost at 160650 iteration is 868.9434635142301
The cost at 160700 iteration is 868.9247613575809
The cost at 160750 iteration is 868.9060634277539
The cost at 160800 iteration is 868.8873697235173
The cost at 160850 iteration is 868.8686802436307
The cost at 160900 iteration is 868.8499949868597
The cost at 160950 iteration is 868.8313139519696
The cost at 161000 iteration is 868.812637137724
The cost at 161050 iteration is 868.7939645428924
The cost at 161100 iteration is 868.7752961662378
The cost at 161150 iteration is 868.7566320065298
The cost at 161200 iteration is 868.7379720625364
The cost at 161250 iteration is 868.719316333028
The cost at 161300 iteration is 868.7006648167728
The cost at 161350 iteration is 868.682017512542
The cost at 161400 iteration is 868.6633744191062
The cost at 161450 iteration is 868.6447355352352
The cost at 161500 iteration is 868.626100859704
The cost at 161550 iteration is 868.6074703912863
The cost at 161600 iteration is 868.5888441287545
The cost at 161650 iteration is 868.5702220708815
The cost at 161700 iteration is 868.5516042164445
The cost at 161750 iteration is 868.5329905642195
The cost at 161800 iteration is 868.5143811129818
The cost at 161850 iteration is 868.4957758615084
The cost at 161900 iteration is 868.4771748085741
The cost at 161950 iteration is 868.4585779529639
The cost at 162000 iteration is 868.4399852934536
The cost at 162050 iteration is 868.4213968288238
The cost at 162100 iteration is 868.4028125578524
The cost at 162150 iteration is 868.3842324793244
The cost at 162200 iteration is 868.365656592015
The cost at 162250 iteration is 868.3470848947155
The cost at 162300 iteration is 868.3285173862033
The cost at 162350 iteration is 868.3099540652653
The cost at 162400 iteration is 868.2913949306799
The cost at 162450 iteration is 868.27283998124
The cost at 162500 iteration is 868.2542892157248
The cost at 162550 iteration is 868.2357426329246
The cost at 162600 iteration is 868.2172002316263
The cost at 162650 iteration is 868.1986620106153
The cost at 162700 iteration is 868.1801279686825
The cost at 162750 iteration is 868.161598104615
The cost at 162800 iteration is 868.1430724172045
The cost at 162850 iteration is 868.1245509052405
The cost at 162900 iteration is 868.1060335675138
The cost at 162950 iteration is 868.0875204028149
The cost at 163000 iteration is 868.0690114099374
The cost at 163050 iteration is 868.050506587674
The cost at 163100 iteration is 868.0320059348187
The cost at 163150 iteration is 868.0135094501663
The cost at 163200 iteration is 867.9950171325119
The cost at 163250 iteration is 867.9765289806496
The cost at 163300 iteration is 867.958044993373
The cost at 163350 iteration is 867.9395651694857
The cost at 163400 iteration is 867.9210895077782
The cost at 163450 iteration is 867.9026180070555
The cost at 163500 iteration is 867.8841506661097
The cost at 163550 iteration is 867.8656874837454
The cost at 163600 iteration is 867.8472284587591
The cost at 163650 iteration is 867.8287735899577
The cost at 163700 iteration is 867.8103228761349
The cost at 163750 iteration is 867.7918763160958
The cost at 163800 iteration is 867.7734339086451
The cost at 163850 iteration is 867.7549956525828
The cost at 163900 iteration is 867.7365615467146
The cost at 163950 iteration is 867.7181315898451
The cost at 164000 iteration is 867.6997057807794
The cost at 164050 iteration is 867.6812841183223
The cost at 164100 iteration is 867.6628666012822
The cost at 164150 iteration is 867.6444532284651
The cost at 164200 iteration is 867.6260439986793
The cost at 164250 iteration is 867.6076389107326
The cost at 164300 iteration is 867.5892379634331
The cost at 164350 iteration is 867.5708411555938
The cost at 164400 iteration is 867.5524484860215
The cost at 164450 iteration is 867.5340599535309
The cost at 164500 iteration is 867.5156755569286
The cost at 164550 iteration is 867.4972952950313
The cost at 164600 iteration is 867.4789191666481
The cost at 164650 iteration is 867.460547170596
The cost at 164700 iteration is 867.4421793056872
The cost at 164750 iteration is 867.4238155707371
The cost at 164800 iteration is 867.4054559645589
The cost at 164850 iteration is 867.3871004859704
The cost at 164900 iteration is 867.3687491337915
The cost at 164950 iteration is 867.350401906833
The cost at 165000 iteration is 867.332058803917
The cost at 165050 iteration is 867.3137198238609
The cost at 165100 iteration is 867.2953849654833
The cost at 165150 iteration is 867.2770542276035
The cost at 165200 iteration is 867.2587276090453
The cost at 165250 iteration is 867.2404051086271
The cost at 165300 iteration is 867.2220867251683
The cost at 165350 iteration is 867.203772457496
The cost at 165400 iteration is 867.1854623044273
The cost at 165450 iteration is 867.1671562647908
The cost at 165500 iteration is 867.1488543374073
The cost at 165550 iteration is 867.1305565211044
The cost at 165600 iteration is 867.112262814704
The cost at 165650 iteration is 867.0939732170339
The cost at 165700 iteration is 867.0756877269208
The cost at 165750 iteration is 867.0574063431937
The cost at 165800 iteration is 867.0391290646772
The cost at 165850 iteration is 867.0208558901985
The cost at 165900 iteration is 867.0025868185895
The cost at 165950 iteration is 866.9843218486803
The cost at 166000 iteration is 866.9660609792985
The cost at 166050 iteration is 866.9478042092783
The cost at 166100 iteration is 866.9295515374466
The cost at 166150 iteration is 866.9113029626403
The cost at 166200 iteration is 866.8930584836879
The cost at 166250 iteration is 866.8748180994259
The cost at 166300 iteration is 866.8565818086869
The cost at 166350 iteration is 866.8383496103041
The cost at 166400 iteration is 866.8201215031161
The cost at 166450 iteration is 866.8018974859539
The cost at 166500 iteration is 866.7836775576568
The cost at 166550 iteration is 866.7654617170617
The cost at 166600 iteration is 866.7472499630034
The cost at 166650 iteration is 866.7290422943221
The cost at 166700 iteration is 866.7108387098589
The cost at 166750 iteration is 866.6926392084507
The cost at 166800 iteration is 866.6744437889369
The cost at 166850 iteration is 866.6562524501552
The cost at 166900 iteration is 866.6380651909527
The cost at 166950 iteration is 866.61988201017

The cost at 167000 iteration is 866.6017029066446
The cost at 167050 iteration is 866.5835278792227
The cost at 167100 iteration is 866.5653569267481
The cost at 167150 iteration is 866.5471900480646
The cost at 167200 iteration is 866.5290272420181
The cost at 167250 iteration is 866.510868507451
The cost at 167300 iteration is 866.4927138432116
The cost at 167350 iteration is 866.4745632481437
The cost at 167400 iteration is 866.4564167210975
The cost at 167450 iteration is 866.4382742609193
The cost at 167500 iteration is 866.4201358664577
The cost at 167550 iteration is 866.4020015365597
The cost at 167600 iteration is 866.3838712700793
The cost at 167650 iteration is 866.365745065861
The cost at 167700 iteration is 866.3476229227576
The cost at 167750 iteration is 866.3295048396193
The cost at 167800 iteration is 866.311390815302
The cost at 167850 iteration is 866.2932808486536
The cost at 167900 iteration is 866.2751749385271
The cost at 167950 iteration is 866.2570730837799
The cost at 168000 iteration is 866.2389752832636
The cost at 168050 iteration is 866.220881535832
The cost at 168100 iteration is 866.2027918403431
The cost at 168150 iteration is 866.1847061956486
The cost at 168200 iteration is 866.1666246006097
The cost at 168250 iteration is 866.1485470540803
The cost at 168300 iteration is 866.1304735549198
The cost at 168350 iteration is 866.1124041019874
The cost at 168400 iteration is 866.0943386941376
The cost at 168450 iteration is 866.0762773302315
The cost at 168500 iteration is 866.0582200091305
The cost at 168550 iteration is 866.0401667296951
The cost at 168600 iteration is 866.0221174907864
The cost at 168650 iteration is 866.0040722912646
The cost at 168700 iteration is 865.986031129993
The cost at 168750 iteration is 865.9679940058319
The cost at 168800 iteration is 865.9499609176506
The cost at 168850 iteration is 865.9319318643066
The cost at 168900 iteration is 865.9139068446708
The cost at 168950 iteration is 865.8958858576029
The cost at 169000 iteration is 865.8778689019704
The cost at 169050 iteration is 865.8598559766397
The cost at 169100 iteration is 865.8418470804793
The cost at 169150 iteration is 865.8238422123534
The cost at 169200 iteration is 865.805841371132
The cost at 169250 iteration is 865.7878445556843
The cost at 169300 iteration is 865.7698517648763
The cost at 169350 iteration is 865.7518629975818
The cost at 169400 iteration is 865.7338782526688
The cost at 169450 iteration is 865.7158975290073
The cost at 169500 iteration is 865.6979208254727
The cost at 169550 iteration is 865.6799481409304
The cost at 169600 iteration is 865.6619794742585
The cost at 169650 iteration is 865.6440148243283
The cost at 169700 iteration is 865.6260541900144
The cost at 169750 iteration is 865.6080975701884
The cost at 169800 iteration is 865.5901449637278
The cost at 169850 iteration is 865.5721963695063
The cost at 169900 iteration is 865.5542517864001
The cost at 169950 iteration is 865.5363112132884
The cost at 170000 iteration is 865.5183746490434
The cost at 170050 iteration is 865.5004420925462
The cost at 170100 iteration is 865.4825135426731
The cost at 170150 iteration is 865.4645889983045
The cost at 170200 iteration is 865.4466684583194
The cost at 170250 iteration is 865.4287519215936
The cost at 170300 iteration is 865.4108393870142
The cost at 170350 iteration is 865.3929308534578
The cost at 170400 iteration is 865.3750263198078
The cost at 170450 iteration is 865.357125784946
The cost at 170500 iteration is 865.339229247753
The cost at 170550 iteration is 865.3213367071136
The cost at 170600 iteration is 865.3034481619111
The cost at 170650 iteration is 865.2855636110298
The cost at 170700 iteration is 865.2676830533561
The cost at 170750 iteration is 865.2498064877726
The cost at 170800 iteration is 865.2319339131677
The cost at 170850 iteration is 865.2140653284278
The cost at 170900 iteration is 865.196200732438
The cost at 170950 iteration is 865.1783401240862
The cost at 171000 iteration is 865.160483502263
The cost at 171050 iteration is 865.1426308658552
The cost at 171100 iteration is 865.1247822137506
The cost at 171150 iteration is 865.1069375448429
The cost at 171200 iteration is 865.0890968580168
The cost at 171250 iteration is 865.0712601521684
The cost at 171300 iteration is 865.0534274261892
The cost at 171350 iteration is 865.0355986789651
The cost at 171400 iteration is 865.0177739093945
The cost at 171450 iteration is 864.9999531163714
The cost at 171500 iteration is 864.9821362987831
The cost at 171550 iteration is 864.9643234555286
The cost at 171600 iteration is 864.946514585501
The cost at 171650 iteration is 864.9287096875968
The cost at 171700 iteration is 864.9109087607104
The cost at 171750 iteration is 864.8931118037381
The cost at 171800 iteration is 864.8753188155761
The cost at 171850 iteration is 864.8575297951252
The cost at 171900 iteration is 864.8397447412817
The cost at 171950 iteration is 864.8219636529413
The cost at 172000 iteration is 864.8041865290045
The cost at 172050 iteration is 864.7864133683736
The cost at 172100 iteration is 864.768644169946
The cost at 172150 iteration is 864.750878932621
The cost at 172200 iteration is 864.7331176553045
The cost at 172250 iteration is 864.7153603368952
The cost at 172300 iteration is 864.6976069762927
The cost at 172350 iteration is 864.6798575724039
The cost at 172400 iteration is 864.662112124132
The cost at 172450 iteration is 864.6443706303775
The cost at 172500 iteration is 864.6266330900477
The cost at 172550 iteration is 864.6088995020469
The cost at 172600 iteration is 864.5911698652811
The cost at 172650 iteration is 864.5734441786527
The cost at 172700 iteration is 864.5557224410737
The cost at 172750 iteration is 864.5380046514471
The cost at 172800 iteration is 864.5202908086819
The cost at 172850 iteration is 864.5025809116863
The cost at 172900 iteration is 864.4848749593694
The cost at 172950 iteration is 864.4671729506377
The cost at 173000 iteration is 864.4494748844053
The cost at 173050 iteration is 864.4317807595767
The cost at 173100 iteration is 864.4140905750664
The cost at 173150 iteration is 864.3964043297865
The cost at 173200 iteration is 864.3787220226455
The cost at 173250 iteration is 864.3610436525593
The cost at 173300 iteration is 864.3433692184358
The cost at 173350 iteration is 864.3256987191953
The cost at 173400 iteration is 864.3080321537448
The cost at 173450 iteration is 864.2903695210039
The cost at 173500 iteration is 864.2727108198816
The cost at 173550 iteration is 864.2550560493006
The cost at 173600 iteration is 864.2374052081723
The cost at 173650 iteration is 864.2197582954118
The cost at 173700 iteration is 864.2021153099408
The cost at 173750 iteration is 864.1844762506744
The cost at 173800 iteration is 864.1668411165305
The cost at 173850 iteration is 864.1492099064269
The cost at 173900 iteration is 864.1315826192845
The cost at 173950 iteration is 864.1139592540216
The cost at 174000 iteration is 864.096339809556
The cost at 174050 iteration is 864.0787242848148
The cost at 174100 iteration is 864.0611126787146
The cost at 174150 iteration is 864.0435049901769
The cost at 174200 iteration is 864.0259012181256
The cost at 174250 iteration is 864.0083013614837
The cost at 174300 iteration is 863.9907054191698
The cost at 174350 iteration is 863.9731133901126
The cost at 174400 iteration is 863.9555252732355
The cost at 174450 iteration is 863.9379410674625
The cost at 174500 iteration is 863.9203607717186
The cost at 174550 iteration is 863.9027843849298
The cost at 174600 iteration is 863.8852119060203
The cost at 174650 iteration is 863.8676433339206
The cost at 174700 iteration is 863.8500786675571
The cost at 174750 iteration is 863.8325179058552
The cost at 174800 iteration is 863.8149610477464
The cost at 174850 iteration is 863.797408092157
The cost at 174900 iteration is 863.7798590380168
The cost at 174950 iteration is 863.7623138842561
The cost at 175000 iteration is 863.7447726298059
The cost at 175050 iteration is 863.7272352735979
The cost at 175100 iteration is 863.7097018145583
The cost at 175150 iteration is 863.6921722516265
The cost at 175200 iteration is 863.6746465837285

The cost at 175250 iteration is 863.6571248097982
The cost at 175300 iteration is 863.6396069287729
The cost at 175350 iteration is 863.6220929395848
The cost at 175400 iteration is 863.6045828411649
The cost at 175450 iteration is 863.587076632453
The cost at 175500 iteration is 863.5695743123784
The cost at 175550 iteration is 863.5520758798841
The cost at 175600 iteration is 863.5345813338997
The cost at 175650 iteration is 863.517090673369
The cost at 175700 iteration is 863.4996038972233
The cost at 175750 iteration is 863.4821210044043
The cost at 175800 iteration is 863.464641993849
The cost at 175850 iteration is 863.4471668644953
The cost at 175900 iteration is 863.4296956152855
The cost at 175950 iteration is 863.4122282451558
The cost at 176000 iteration is 863.3947647530493
The cost at 176050 iteration is 863.377305137905
The cost at 176100 iteration is 863.3598493986651
The cost at 176150 iteration is 863.342397534272
The cost at 176200 iteration is 863.3249495436677
The cost at 176250 iteration is 863.3075054257955
The cost at 176300 iteration is 863.2900651795941
The cost at 176350 iteration is 863.2726288040178
The cost at 176400 iteration is 863.2551962980003
The cost at 176450 iteration is 863.2377676604913
The cost at 176500 iteration is 863.2203428904372
The cost at 176550 iteration is 863.2029219867776
The cost at 176600 iteration is 863.1855049484672
The cost at 176650 iteration is 863.1680917744471
The cost at 176700 iteration is 863.150682463667
The cost at 176750 iteration is 863.1332770150739
The cost at 176800 iteration is 863.1158754276163
The cost at 176850 iteration is 863.0984777002444
The cost at 176900 iteration is 863.0810838319024
The cost at 176950 iteration is 863.0636938215448
The cost at 177000 iteration is 863.0463076681216
The cost at 177050 iteration is 863.0289253705797
The cost at 177100 iteration is 863.011546927875
The cost at 177150 iteration is 862.9941723389559
The cost at 177200 iteration is 862.9768016027745
The cost at 177250 iteration is 862.9594347182866
The cost at 177300 iteration is 862.9420716844451
The cost at 177350 iteration is 862.9247125001979
The cost at 177400 iteration is 862.9073571645055
The cost at 177450 iteration is 862.8900056763183
The cost at 177500 iteration is 862.8726580345942
The cost at 177550 iteration is 862.8553142382889
The cost at 177600 iteration is 862.8379742863543
The cost at 177650 iteration is 862.8206381777519
The cost at 177700 iteration is 862.8033059114358
The cost at 177750 iteration is 862.7859774863629
The cost at 177800 iteration is 862.768652901493
The cost at 177850 iteration is 862.7513321557836
The cost at 177900 iteration is 862.7340152481971
The cost at 177950 iteration is 862.716702177686
The cost at 178000 iteration is 862.6993929432144
The cost at 178050 iteration is 862.6820875437412
The cost at 178100 iteration is 862.6647859782321
The cost at 178150 iteration is 862.6474882456417
The cost at 178200 iteration is 862.6301943449325
The cost at 178250 iteration is 862.6129042750712
The cost at 178300 iteration is 862.5956180350171
The cost at 178350 iteration is 862.5783356237326
The cost at 178400 iteration is 862.5610570401884
The cost at 178450 iteration is 862.5437822833383
The cost at 178500 iteration is 862.526511352155
The cost at 178550 iteration is 862.509244245598
The cost at 178600 iteration is 862.4919809626334
The cost at 178650 iteration is 862.4747215022337
The cost at 178700 iteration is 862.4574658633588
The cost at 178750 iteration is 862.4402140449776
The cost at 178800 iteration is 862.4229660460549
The cost at 178850 iteration is 862.4057218655666
The cost at 178900 iteration is 862.3884815024738
The cost at 178950 iteration is 862.3712449557452
The cost at 179000 iteration is 862.3540122243568
The cost at 179050 iteration is 862.3367833072681
The cost at 179100 iteration is 862.3195582034587
The cost at 179150 iteration is 862.3023369118946
The cost at 179200 iteration is 862.2851194315467
The cost at 179250 iteration is 862.267905761391
The cost at 179300 iteration is 862.250695900398
The cost at 179350 iteration is 862.2334898475366
The cost at 179400 iteration is 862.2162876017807
The cost at 179450 iteration is 862.1990891621076
The cost at 179500 iteration is 862.1818945274885
The cost at 179550 iteration is 862.1647036968976
The cost at 179600 iteration is 862.1475166693114
The cost at 179650 iteration is 862.1303334437058
The cost at 179700 iteration is 862.1131540190539
The cost at 179750 iteration is 862.095978394333
The cost at 179800 iteration is 862.0788065685232
The cost at 179850 iteration is 862.0616385405954
The cost at 179900 iteration is 862.0444743095308
The cost at 179950 iteration is 862.0273138743103
The cost at 180000 iteration is 862.0101572339081
The cost at 180050 iteration is 861.993004387303
The cost at 180100 iteration is 861.9758553334792
The cost at 180150 iteration is 861.9587100714126
The cost at 180200 iteration is 861.9415686000848
The cost at 180250 iteration is 861.9244309184752
The cost at 180300 iteration is 861.9072970255696
The cost at 180350 iteration is 861.8901669203451
The cost at 180400 iteration is 861.8730406017879
The cost at 180450 iteration is 861.8559180688776
The cost at 180500 iteration is 861.8387993205971
The cost at 180550 iteration is 861.8216843559343
The cost at 180600 iteration is 861.80457317387
The cost at 180650 iteration is 861.7874657733859
The cost at 180700 iteration is 861.770362153473
The cost at 180750 iteration is 861.7532623131137
The cost at 180800 iteration is 861.7361662512913
The cost at 180850 iteration is 861.7190739669988
The cost at 180900 iteration is 861.7019854592194
The cost at 180950 iteration is 861.6849007269384
The cost at 181000 iteration is 861.6678197691454
The cost at 181050 iteration is 861.6507425848273
The cost at 181100 iteration is 861.6336691729786
The cost at 181150 iteration is 861.61659953258
The cost at 181200 iteration is 861.5995336626247
The cost at 181250 iteration is 861.5824715621042
The cost at 181300 iteration is 861.5654132300072
The cost at 181350 iteration is 861.5483586653244
The cost at 181400 iteration is 861.5313078670463
The cost at 181450 iteration is 861.5142608341689
The cost at 181500 iteration is 861.4972175656814
The cost at 181550 iteration is 861.4801780605761
The cost at 181600 iteration is 861.463142317844
The cost at 181650 iteration is 861.4461103364845
The cost at 181700 iteration is 861.4290821154858
The cost at 181750 iteration is 861.4120576538438
The cost at 181800 iteration is 861.3950369505576
The cost at 181850 iteration is 861.3780200046184
The cost at 181900 iteration is 861.3610068150213
The cost at 181950 iteration is 861.3439973807663
The cost at 182000 iteration is 861.3269917008483
The cost at 182050 iteration is 861.3099897742616
The cost at 182100 iteration is 861.2929916000089
The cost at 182150 iteration is 861.2759971770829
The cost at 182200 iteration is 861.2590065044856
The cost at 182250 iteration is 861.2420195812158
The cost at 182300 iteration is 861.2250364062727
The cost at 182350 iteration is 861.2080569786534
The cost at 182400 iteration is 861.1910812973601
The cost at 182450 iteration is 861.174109361395
The cost at 182500 iteration is 861.1571411697546
The cost at 182550 iteration is 861.1401767214476
The cost at 182600 iteration is 861.1232160154682
The cost at 182650 iteration is 861.1062590508225
The cost at 182700 iteration is 861.0893058265162
The cost at 182750 iteration is 861.0723563415454
The cost at 182800 iteration is 861.0554105949223
The cost at 182850 iteration is 861.0384685856436
The cost at 182900 iteration is 861.0215303127165
The cost at 182950 iteration is 861.0045957751489
The cost at 183000 iteration is 860.9876649719431
The cost at 183050 iteration is 860.9707379021062
The cost at 183100 iteration is 860.9538145646432
The cost at 183150 iteration is 860.9368949585604
The cost at 183200 iteration is 860.9199790828671
The cost at 183250 iteration is 860.9030669365709
The cost at 183300 iteration is 860.886158518679
The cost at 183350 iteration is 860.8692538282005
The cost at 183400 iteration is 860.8523528641429
The cost at 183450 iteration is 860.8354556255159

The cost at 183500 iteration is 860.8185621113317
The cost at 183550 iteration is 860.8016723205982
The cost at 183600 iteration is 860.7847862523246
The cost at 183650 iteration is 860.7679039055242
The cost at 183700 iteration is 860.7510252792102
The cost at 183750 iteration is 860.7341503723909
The cost at 183800 iteration is 860.7172791840796
The cost at 183850 iteration is 860.7004117132938
The cost at 183900 iteration is 860.6835479590394
The cost at 183950 iteration is 860.6666879203339
The cost at 184000 iteration is 860.6498315961915
The cost at 184050 iteration is 860.6329789856243
The cost at 184100 iteration is 860.6161300876513
The cost at 184150 iteration is 860.5992849012822
The cost at 184200 iteration is 860.5824434255394
The cost at 184250 iteration is 860.5656056594348
The cost at 184300 iteration is 860.5487716019859
The cost at 184350 iteration is 860.5319412522102
The cost at 184400 iteration is 860.5151146091249
The cost at 184450 iteration is 860.4982916717485
The cost at 184500 iteration is 860.4814724390967
The cost at 184550 iteration is 860.464656910192
The cost at 184600 iteration is 860.4478450840519
The cost at 184650 iteration is 860.4310369596965
The cost at 184700 iteration is 860.4142325361437
The cost at 184750 iteration is 860.3974318124184
The cost at 184800 iteration is 860.3806347875349
The cost at 184850 iteration is 860.3638414605223
The cost at 184900 iteration is 860.3470518303957
The cost at 184950 iteration is 860.3302658961805
The cost at 185000 iteration is 860.3134836568998
The cost at 185050 iteration is 860.2967051115718
The cost at 185100 iteration is 860.2799302592264
The cost at 185150 iteration is 860.2631590988852
The cost at 185200 iteration is 860.2463916295702
The cost at 185250 iteration is 860.2296278503069
The cost at 185300 iteration is 860.2128677601216
The cost at 185350 iteration is 860.1961113580383
The cost at 185400 iteration is 860.1793586430857
The cost at 185450 iteration is 860.1626096142879
The cost at 185500 iteration is 860.1458642706714
The cost at 185550 iteration is 860.1291226112621
The cost at 185600 iteration is 860.112384635092
The cost at 185650 iteration is 860.0956503411868
The cost at 185700 iteration is 860.0789197285715
The cost at 185750 iteration is 860.0621927962785
The cost at 185800 iteration is 860.045469543337
The cost at 185850 iteration is 860.0287499687767
The cost at 185900 iteration is 860.0120340716287
The cost at 185950 iteration is 859.9953218509205
The cost at 186000 iteration is 859.9786133056828
The cost at 186050 iteration is 859.9619084349498
The cost at 186100 iteration is 859.9452072377501
The cost at 186150 iteration is 859.9285097131198
The cost at 186200 iteration is 859.9118158600885
The cost at 186250 iteration is 859.8951256776891
The cost at 186300 iteration is 859.8784391649557
The cost at 186350 iteration is 859.8617563209216
The cost at 186400 iteration is 859.8450771446217
The cost at 186450 iteration is 859.8284016350898
The cost at 186500 iteration is 859.8117297913616
The cost at 186550 iteration is 859.7950616124729
The cost at 186600 iteration is 859.7783970974565
The cost at 186650 iteration is 859.7617362453541
The cost at 186700 iteration is 859.7450790551962
The cost at 186750 iteration is 859.7284255260234
The cost at 186800 iteration is 859.7117756568746
The cost at 186850 iteration is 859.6951294467837
The cost at 186900 iteration is 859.6784868947913
The cost at 186950 iteration is 859.6618479999349
The cost at 187000 iteration is 859.6452127612527
The cost at 187050 iteration is 859.6285811777881
The cost at 187100 iteration is 859.6119532485766
The cost at 187150 iteration is 859.5953289726622
The cost at 187200 iteration is 859.5787083490827
The cost at 187250 iteration is 859.5620913768798
The cost at 187300 iteration is 859.5454780550954
The cost at 187350 iteration is 859.5288683827707
The cost at 187400 iteration is 859.5122623589496
The cost at 187450 iteration is 859.495659982675
The cost at 187500 iteration is 859.4790612529868
The cost at 187550 iteration is 859.4624661689319
The cost at 187600 iteration is 859.4458747295515
The cost at 187650 iteration is 859.4292869338924
The cost at 187700 iteration is 859.4127027809959
The cost at 187750 iteration is 859.3961222699111
The cost at 187800 iteration is 859.3795453996815
The cost at 187850 iteration is 859.3629721693538
The cost at 187900 iteration is 859.3464025779723
The cost at 187950 iteration is 859.3298366245866
The cost at 188000 iteration is 859.3132743082401
The cost at 188050 iteration is 859.296715627985
The cost at 188100 iteration is 859.2801605828658
The cost at 188150 iteration is 859.2636091719305
The cost at 188200 iteration is 859.2470613942293
The cost at 188250 iteration is 859.2305172488124
The cost at 188300 iteration is 859.2139767347245
The cost at 188350 iteration is 859.1974398510214
The cost at 188400 iteration is 859.1809065967497
The cost at 188450 iteration is 859.1643769709609
The cost at 188500 iteration is 859.1478509727074
The cost at 188550 iteration is 859.1313286010368
The cost at 188600 iteration is 859.1148098550048
The cost at 188650 iteration is 859.0982947336647
The cost at 188700 iteration is 859.0817832360649
The cost at 188750 iteration is 859.0652753612579
The cost at 188800 iteration is 859.0487711083053
The cost at 188850 iteration is 859.0322704762524
The cost at 188900 iteration is 859.0157734641555
The cost at 188950 iteration is 858.9992800710727
The cost at 189000 iteration is 858.9827902960527
The cost at 189050 iteration is 858.9663041381547
The cost at 189100 iteration is 858.9498215964373
The cost at 189150 iteration is 858.9333426699518
The cost at 189200 iteration is 858.9168673577543
The cost at 189250 iteration is 858.9003956589085
The cost at 189300 iteration is 858.8839275724652
The cost at 189350 iteration is 858.8674630974838
The cost at 189400 iteration is 858.8510022330205
The cost at 189450 iteration is 858.834544978139
The cost at 189500 iteration is 858.8180913318948
The cost at 189550 iteration is 858.8016412933488
The cost at 189600 iteration is 858.7851948615552
The cost at 189650 iteration is 858.7687520355846
The cost at 189700 iteration is 858.7523128144877
The cost at 189750 iteration is 858.7358771973277
The cost at 189800 iteration is 858.7194451831682
The cost at 189850 iteration is 858.7030167710692
The cost at 189900 iteration is 858.6865919600939
The cost at 189950 iteration is 858.6701707493031
The cost at 190000 iteration is 858.6537531377613
The cost at 190050 iteration is 858.6373391245295
The cost at 190100 iteration is 858.6209287086718
The cost at 190150 iteration is 858.6045218892544
The cost at 190200 iteration is 858.5881186653373
The cost at 190250 iteration is 858.5717190359893
The cost at 190300 iteration is 858.5553230002755
The cost at 190350 iteration is 858.5389305572564
The cost at 190400 iteration is 858.5225417060044
The cost at 190450 iteration is 858.5061564455805
The cost at 190500 iteration is 858.4897747750533
The cost at 190550 iteration is 858.4733966934892
The cost at 190600 iteration is 858.4570221999584
The cost at 190650 iteration is 858.440651293524
The cost at 190700 iteration is 858.424283973257
The cost at 190750 iteration is 858.4079202382268
The cost at 190800 iteration is 858.3915600875001
The cost at 190850 iteration is 858.3752035201453
The cost at 190900 iteration is 858.358850535234
The cost at 190950 iteration is 858.342501131836
The cost at 191000 iteration is 858.3261553090224
The cost at 191050 iteration is 858.3098130658616
The cost at 191100 iteration is 858.2934744014286
The cost at 191150 iteration is 858.2771393147915
The cost at 191200 iteration is 858.2608078050223
The cost at 191250 iteration is 858.2444798711938
The cost at 191300 iteration is 858.2281555123802
The cost at 191350 iteration is 858.2118347276545
The cost at 191400 iteration is 858.1955175160882
The cost at 191450 iteration is 858.1792038767559
The cost at 191500 iteration is 858.1628938087313
The cost at 191550 iteration is 858.1465873110886
The cost at 191600 iteration is 858.1302843829059
The cost at 191650 iteration is 858.1139850232538
The cost at 191700 iteration is 858.0976892312115

The cost at 191750 iteration is 858.0813970058534
The cost at 191800 iteration is 858.0651083462586
The cost at 191850 iteration is 858.0488232514981
The cost at 191900 iteration is 858.0325417206557
The cost at 191950 iteration is 858.0162637528027
The cost at 192000 iteration is 857.9999893470238
The cost at 192050 iteration is 857.9837185023912
The cost at 192100 iteration is 857.9674512179864
The cost at 192150 iteration is 857.9511874928885
The cost at 192200 iteration is 857.9349273261753
The cost at 192250 iteration is 857.9186707169291
The cost at 192300 iteration is 857.9024176642268
The cost at 192350 iteration is 857.8861681671523
The cost at 192400 iteration is 857.8699222247841
The cost at 192450 iteration is 857.8536798362037
The cost at 192500 iteration is 857.8374410004942
The cost at 192550 iteration is 857.8212057167367
The cost at 192600 iteration is 857.8049739840112
The cost at 192650 iteration is 857.7887458014054
The cost at 192700 iteration is 857.7725211679988
The cost at 192750 iteration is 857.7563000828756
The cost at 192800 iteration is 857.7400825451192
The cost at 192850 iteration is 857.7238685538135
The cost at 192900 iteration is 857.7076581080463
The cost at 192950 iteration is 857.6914512068998
The cost at 193000 iteration is 857.6752478494577
The cost at 193050 iteration is 857.6590480348087
The cost at 193100 iteration is 857.6428517620352
The cost at 193150 iteration is 857.6266590302312
The cost at 193200 iteration is 857.6104698384743
The cost at 193250 iteration is 857.5942841858576
The cost at 193300 iteration is 857.5781020714638
The cost at 193350 iteration is 857.5619234943849
The cost at 193400 iteration is 857.5457484537092
The cost at 193450 iteration is 857.5295769485222
The cost at 193500 iteration is 857.5134089779156
The cost at 193550 iteration is 857.4972445409754
The cost at 193600 iteration is 857.481083636797
The cost at 193650 iteration is 857.464926264465
The cost at 193700 iteration is 857.4487724230701
The cost at 193750 iteration is 857.4326221117086
The cost at 193800 iteration is 857.4164753294638
The cost at 193850 iteration is 857.4003320754321
The cost at 193900 iteration is 857.3841923487048
The cost at 193950 iteration is 857.3680561483725
The cost at 194000 iteration is 857.3519234735312
The cost at 194050 iteration is 857.3357943232672
The cost at 194100 iteration is 857.3196686966811
The cost at 194150 iteration is 857.3035465928631
The cost at 194200 iteration is 857.287428010907
The cost at 194250 iteration is 857.2713129499059
The cost at 194300 iteration is 857.255201408958
The cost at 194350 iteration is 857.2390933871577
The cost at 194400 iteration is 857.222988883598
The cost at 194450 iteration is 857.2068878973778
The cost at 194500 iteration is 857.1907904275886
The cost at 194550 iteration is 857.174696473331
The cost at 194600 iteration is 857.1586060337002
The cost at 194650 iteration is 857.1425191077947
The cost at 194700 iteration is 857.126435694712
The cost at 194750 iteration is 857.110355793547
The cost at 194800 iteration is 857.0942794034021
The cost at 194850 iteration is 857.0782065233733
The cost at 194900 iteration is 857.0621371525607
The cost at 194950 iteration is 857.0460712900649
The cost at 195000 iteration is 857.0300089349806
The cost at 195050 iteration is 857.0139500864149
The cost at 195100 iteration is 856.9978947434622
The cost at 195150 iteration is 856.9818429052267
The cost at 195200 iteration is 856.9657945708074
The cost at 195250 iteration is 856.9497497393097
The cost at 195300 iteration is 856.9337084098308
The cost at 195350 iteration is 856.9176705814738
The cost at 195400 iteration is 856.9016362533418
The cost at 195450 iteration is 856.8856054245393
The cost at 195500 iteration is 856.8695780941672
The cost at 195550 iteration is 856.8535542613308
The cost at 195600 iteration is 856.8375339251359
The cost at 195650 iteration is 856.8215170846817
The cost at 195700 iteration is 856.8055037390743
The cost at 195750 iteration is 856.789493887423
The cost at 195800 iteration is 856.7734875288288
The cost at 195850 iteration is 856.7574846623959
The cost at 195900 iteration is 856.7414852872369
The cost at 195950 iteration is 856.7254894024513
The cost at 196000 iteration is 856.7094970071537
The cost at 196050 iteration is 856.6935081004397
The cost at 196100 iteration is 856.6775226814245
The cost at 196150 iteration is 856.661540749221
The cost at 196200 iteration is 856.6455623029254
The cost at 196250 iteration is 856.6295873416525
The cost at 196300 iteration is 856.6136158645131
The cost at 196350 iteration is 856.5976478706102
The cost at 196400 iteration is 856.5816833590609
The cost at 196450 iteration is 856.5657223289685
The cost at 196500 iteration is 856.5497647794452
The cost at 196550 iteration is 856.5338107096037
The cost at 196600 iteration is 856.517860118552
The cost at 196650 iteration is 856.5019130054046
The cost at 196700 iteration is 856.4859693692702
The cost at 196750 iteration is 856.4700292092623
The cost at 196800 iteration is 856.4540925244919
The cost at 196850 iteration is 856.4381593140735
The cost at 196900 iteration is 856.4222295771169
The cost at 196950 iteration is 856.4063033127393
The cost at 197000 iteration is 856.3903805200518
The cost at 197050 iteration is 856.3744611981696
The cost at 197100 iteration is 856.3585453462064
The cost at 197150 iteration is 856.342632963278
The cost at 197200 iteration is 856.3267240484976
The cost at 197250 iteration is 856.3108186009788
The cost at 197300 iteration is 856.2949166198449
The cost at 197350 iteration is 856.2790181042058
The cost at 197400 iteration is 856.2631230531779
The cost at 197450 iteration is 856.2472314658796
The cost at 197500 iteration is 856.2313433414319
The cost at 197550 iteration is 856.2154586789416
The cost at 197600 iteration is 856.1995774775362
The cost at 197650 iteration is 856.1836997363303
The cost at 197700 iteration is 856.1678254544429
The cost at 197750 iteration is 856.1519546309912
The cost at 197800 iteration is 856.1360872650957
The cost at 197850 iteration is 856.120223355877
The cost at 197900 iteration is 856.1043629024529
The cost at 197950 iteration is 856.0885059039437
The cost at 198000 iteration is 856.072652359471
The cost at 198050 iteration is 856.0568022681547
The cost at 198100 iteration is 856.0409556291178
The cost at 198150 iteration is 856.0251124414801
The cost at 198200 iteration is 856.0092727043611
The cost at 198250 iteration is 855.9934364168897
The cost at 198300 iteration is 855.9776035781804
The cost at 198350 iteration is 855.9617741873611
The cost at 198400 iteration is 855.9459482435535
The cost at 198450 iteration is 855.9301257458834
The cost at 198500 iteration is 855.9143066934707
The cost at 198550 iteration is 855.8984910854417
The cost at 198600 iteration is 855.8826789209228
The cost at 198650 iteration is 855.8668701990345
The cost at 198700 iteration is 855.8510649189069
The cost at 198750 iteration is 855.8352630796597
The cost at 198800 iteration is 855.8194646804244
The cost at 198850 iteration is 855.8036697203238
The cost at 198900 iteration is 855.7878781984866
The cost at 198950 iteration is 855.7720901140375
The cost at 199000 iteration is 855.7563054661036
The cost at 199050 iteration is 855.7405242538147
The cost at 199100 iteration is 855.7247464762974
The cost at 199150 iteration is 855.7089721326807
The cost at 199200 iteration is 855.6932012220907
The cost at 199250 iteration is 855.6774337436597
The cost at 199300 iteration is 855.6616696965148
The cost at 199350 iteration is 855.6459090797863
The cost at 199400 iteration is 855.6301518926011
The cost at 199450 iteration is 855.614398134094
The cost at 199500 iteration is 855.5986478033955
The cost at 199550 iteration is 855.582900899632
The cost at 199600 iteration is 855.5671574219349
The cost at 199650 iteration is 855.5514173694435
The cost at 199700 iteration is 855.5356807412787
The cost at 199750 iteration is 855.5199475365802
The cost at 199800 iteration is 855.5042177544796
The cost at 199850 iteration is 855.4884913941042
The cost at 199900 iteration is 855.4727684545941
The cost at 199950 iteration is 855.4570489350797

The cost at 200000 iteration is 855.4413328346939
The cost at 200050 iteration is 855.4256201525747
The cost at 200100 iteration is 855.4099108878518
The cost at 200150 iteration is 855.3942050396643
The cost at 200200 iteration is 855.3785026071407
The cost at 200250 iteration is 855.3628035894232
The cost at 200300 iteration is 855.3471079856456
The cost at 200350 iteration is 855.3314157949444
The cost at 200400 iteration is 855.315727016455
The cost at 200450 iteration is 855.3000416493124
The cost at 200500 iteration is 855.2843596926565
The cost at 200550 iteration is 855.2686811456235
The cost at 200600 iteration is 855.2530060073531
The cost at 200650 iteration is 855.2373342769807
The cost at 200700 iteration is 855.2216659536459
The cost at 200750 iteration is 855.2060010364884
The cost at 200800 iteration is 855.190339524643
The cost at 200850 iteration is 855.1746814172539
The cost at 200900 iteration is 855.1590267134592
The cost at 200950 iteration is 855.143375412398
The cost at 201000 iteration is 855.1277275132107
The cost at 201050 iteration is 855.1120830150389
The cost at 201100 iteration is 855.0964419170227
The cost at 201150 iteration is 855.0808042183047
The cost at 201200 iteration is 855.0651699180252
The cost at 201250 iteration is 855.049539015327
The cost at 201300 iteration is 855.0339115093509
The cost at 201350 iteration is 855.0182873992404
The cost at 201400 iteration is 855.0026666841406
The cost at 201450 iteration is 854.9870493631896
The cost at 201500 iteration is 854.9714354355356
The cost at 201550 iteration is 854.9558249003186
The cost at 201600 iteration is 854.9402177566893
The cost at 201650 iteration is 854.9246140037836
The cost at 201700 iteration is 854.909013640753
The cost at 201750 iteration is 854.8934166667381
The cost at 201800 iteration is 854.8778230808866
The cost at 201850 iteration is 854.8622328823463
The cost at 201900 iteration is 854.8466460702577
The cost at 201950 iteration is 854.8310626437732
The cost at 202000 iteration is 854.8154826020361
The cost at 202050 iteration is 854.7999059441942
The cost at 202100 iteration is 854.7843326693928
The cost at 202150 iteration is 854.7687627767835
The cost at 202200 iteration is 854.7531962655136
The cost at 202250 iteration is 854.7376331347285
The cost at 202300 iteration is 854.7220733835795
The cost at 202350 iteration is 854.706517011216
The cost at 202400 iteration is 854.6909640167833
The cost at 202450 iteration is 854.6754143994358
The cost at 202500 iteration is 854.6598681583199
The cost at 202550 iteration is 854.6443252925856
The cost at 202600 iteration is 854.6287858013887
The cost at 202650 iteration is 854.6132496838753
The cost at 202700 iteration is 854.5977169391963
The cost at 202750 iteration is 854.5821875665043
The cost at 202800 iteration is 854.5666615649491
The cost at 202850 iteration is 854.5511389336891
The cost at 202900 iteration is 854.5356196718702
The cost at 202950 iteration is 854.5201037786493
The cost at 203000 iteration is 854.5045912531743
The cost at 203050 iteration is 854.489082094604
The cost at 203100 iteration is 854.4735763020898
The cost at 203150 iteration is 854.4580738747854
The cost at 203200 iteration is 854.4425748118447
The cost at 203250 iteration is 854.4270791124261
The cost at 203300 iteration is 854.4115867756775
The cost at 203350 iteration is 854.3960978007622
The cost at 203400 iteration is 854.3806121868294
The cost at 203450 iteration is 854.3651299330367
The cost at 203500 iteration is 854.3496510385421
The cost at 203550 iteration is 854.3341755025001
The cost at 203600 iteration is 854.3187033240649
The cost at 203650 iteration is 854.3032345024031
The cost at 203700 iteration is 854.2877690366608
The cost at 203750 iteration is 854.2723069260037
The cost at 203800 iteration is 854.2568481695869
The cost at 203850 iteration is 854.2413927665671
The cost at 203900 iteration is 854.225940716105
The cost at 203950 iteration is 854.2104920173599
The cost at 204000 iteration is 854.1950466694902
The cost at 204050 iteration is 854.1796046716561
The cost at 204100 iteration is 854.164166023016
The cost at 204150 iteration is 854.1487307227317
The cost at 204200 iteration is 854.1332987699633
The cost at 204250 iteration is 854.1178701638711
The cost at 204300 iteration is 854.1024449036152
The cost at 204350 iteration is 854.0870229883599
The cost at 204400 iteration is 854.0716044172652
The cost at 204450 iteration is 854.0561891894929
The cost at 204500 iteration is 854.040777304205
The cost at 204550 iteration is 854.0253687605642
The cost at 204600 iteration is 854.0099635577387
The cost at 204650 iteration is 853.9945616948817
The cost at 204700 iteration is 853.9791631711638
The cost at 204750 iteration is 853.9637679857492
The cost at 204800 iteration is 853.9483761377994
The cost at 204850 iteration is 853.9329876264802
The cost at 204900 iteration is 853.9176024509554
The cost at 204950 iteration is 853.9022206103896
The cost at 205000 iteration is 853.8868421039484
The cost at 205050 iteration is 853.8714669308024
The cost at 205100 iteration is 853.8560950901094
The cost at 205150 iteration is 853.8407265810423
The cost at 205200 iteration is 853.8253614027655
The cost at 205250 iteration is 853.8099995544441
The cost at 205300 iteration is 853.7946410352483
The cost at 205350 iteration is 853.7792858443432
The cost at 205400 iteration is 853.7639339808965
The cost at 205450 iteration is 853.7485854440782
The cost at 205500 iteration is 853.7332402330566
The cost at 205550 iteration is 853.7178983469988
The cost at 205600 iteration is 853.7025597850763
The cost at 205650 iteration is 853.6872245464557
The cost at 205700 iteration is 853.6718926303087
The cost at 205750 iteration is 853.6565640358045
The cost at 205800 iteration is 853.6412387621134
The cost at 205850 iteration is 853.6259168084064
The cost at 205900 iteration is 853.6105981738522
The cost at 205950 iteration is 853.5952828576251
The cost at 206000 iteration is 853.5799708588942
The cost at 206050 iteration is 853.5646621768318
The cost at 206100 iteration is 853.5493568106108
The cost at 206150 iteration is 853.5340547594014
The cost at 206200 iteration is 853.5187560223795
The cost at 206250 iteration is 853.5034605987157
The cost at 206300 iteration is 853.4881684875845
The cost at 206350 iteration is 853.4728796881586
The cost at 206400 iteration is 853.4575941996106
The cost at 206450 iteration is 853.4423120211185
The cost at 206500 iteration is 853.4270331518534
The cost at 206550 iteration is 853.4117575909905
The cost at 206600 iteration is 853.3964853377053
The cost at 206650 iteration is 853.3812163911733
The cost at 206700 iteration is 853.3659507505686
The cost at 206750 iteration is 853.3506884150709
The cost at 206800 iteration is 853.3354293838529
The cost at 206850 iteration is 853.320173656092
The cost at 206900 iteration is 853.3049212309654
The cost at 206950 iteration is 853.2896721076482
The cost at 207000 iteration is 853.2744262853213
The cost at 207050 iteration is 853.2591837631614
The cost at 207100 iteration is 853.2439445403427
The cost at 207150 iteration is 853.228708616051
The cost at 207200 iteration is 853.2134759894584
The cost at 207250 iteration is 853.1982466597449
The cost at 207300 iteration is 853.1830206260914
The cost at 207350 iteration is 853.1677978876763
The cost at 207400 iteration is 853.1525784436791
The cost at 207450 iteration is 853.1373622932812
The cost at 207500 iteration is 853.1221494356633
The cost at 207550 iteration is 853.1069398700026
The cost at 207600 iteration is 853.0917335954833
The cost at 207650 iteration is 853.0765306112851
The cost at 207700 iteration is 853.06133091659
The cost at 207750 iteration is 853.0461345105826
The cost at 207800 iteration is 853.0309413924392
The cost at 207850 iteration is 853.0157515613465
The cost at 207900 iteration is 853.0005650164866
The cost at 207950 iteration is 852.985381757041
The cost at 208000 iteration is 852.9702017821936
The cost at 208050 iteration is 852.9550250911296
The cost at 208100 iteration is 852.93985168303
The cost at 208150 iteration is 852.9246815570818
The cost at 208200 iteration is 852.9095147124665

The cost at 208250 iteration is 852.894351148371
The cost at 208300 iteration is 852.879190863979
The cost at 208350 iteration is 852.8640338584779
The cost at 208400 iteration is 852.8488801310518
The cost at 208450 iteration is 852.8337296808878
The cost at 208500 iteration is 852.8185825071708
The cost at 208550 iteration is 852.8034386090861
The cost at 208600 iteration is 852.7882979858201
The cost at 208650 iteration is 852.7731606365645
The cost at 208700 iteration is 852.758026560502
The cost at 208750 iteration is 852.7428957568233
The cost at 208800 iteration is 852.7277682247147
The cost at 208850 iteration is 852.7126439633633
The cost at 208900 iteration is 852.6975229719609
The cost at 208950 iteration is 852.6824052496956
The cost at 209000 iteration is 852.6672907957525
The cost at 209050 iteration is 852.652179609323
The cost at 209100 iteration is 852.637071689602
The cost at 209150 iteration is 852.6219670357724
The cost at 209200 iteration is 852.6068656470239
The cost at 209250 iteration is 852.5917675225543
The cost at 209300 iteration is 852.5766726615483
The cost at 209350 iteration is 852.5615810631999
The cost at 209400 iteration is 852.5464927266981
The cost at 209450 iteration is 852.5314076512362
The cost at 209500 iteration is 852.516325836006
The cost at 209550 iteration is 852.5012472801988
The cost at 209600 iteration is 852.4861719830071
The cost at 209650 iteration is 852.4710999436255
The cost at 209700 iteration is 852.4560311612462
The cost at 209750 iteration is 852.4409656350614
The cost at 209800 iteration is 852.4259033642668
The cost at 209850 iteration is 852.4108443480542
The cost at 209900 iteration is 852.3957885856175
The cost at 209950 iteration is 852.3807360761557
The cost at 210000 iteration is 852.3656868188588
The cost at 210050 iteration is 852.3506408129215
The cost at 210100 iteration is 852.3355980575437
The cost at 210150 iteration is 852.3205585519187
The cost at 210200 iteration is 852.305522295239
The cost at 210250 iteration is 852.2904892867072
The cost at 210300 iteration is 852.2754595255137
The cost at 210350 iteration is 852.2604330108621
The cost at 210400 iteration is 852.2454097419406
The cost at 210450 iteration is 852.2303897179538
The cost at 210500 iteration is 852.2153729380963
The cost at 210550 iteration is 852.2003594015669
The cost at 210600 iteration is 852.1853491075633
The cost at 210650 iteration is 852.170342055283
The cost at 210700 iteration is 852.1553382439274
The cost at 210750 iteration is 852.1403376726932
The cost at 210800 iteration is 852.1253403407816
The cost at 210850 iteration is 852.1103462473857
The cost at 210900 iteration is 852.0953553917176
The cost at 210950 iteration is 852.080367772968
The cost at 211000 iteration is 852.0653833903398
The cost at 211050 iteration is 852.0504022430306
The cost at 211100 iteration is 852.0354243302469
The cost at 211150 iteration is 852.0204496511889
The cost at 211200 iteration is 852.005478205055
The cost at 211250 iteration is 851.9905099910487
The cost at 211300 iteration is 851.9755450083721
The cost at 211350 iteration is 851.9605832562279
The cost at 211400 iteration is 851.9456247338185
The cost at 211450 iteration is 851.9306694403467
The cost at 211500 iteration is 851.915717375015
The cost at 211550 iteration is 851.9007685370293
The cost at 211600 iteration is 851.8858229255919
The cost at 211650 iteration is 851.8708805399037
The cost at 211700 iteration is 851.8559413791725
The cost at 211750 iteration is 851.8410054426072
The cost at 211800 iteration is 851.8260727294028
The cost at 211850 iteration is 851.8111432387716
The cost at 211900 iteration is 851.7962169699146
The cost at 211950 iteration is 851.7812939220407
The cost at 212000 iteration is 851.7663740943556
The cost at 212050 iteration is 851.751457486066
The cost at 212100 iteration is 851.736544096376
The cost at 212150 iteration is 851.7216339244912
The cost at 212200 iteration is 851.7067269696256
The cost at 212250 iteration is 851.6918232309793
The cost at 212300 iteration is 851.6769227077642
The cost at 212350 iteration is 851.6620253991864
The cost at 212400 iteration is 851.6471313044539
The cost at 212450 iteration is 851.6322404227761
The cost at 212500 iteration is 851.6173527533617
The cost at 212550 iteration is 851.6024682954179
The cost at 212600 iteration is 851.5875870481566
The cost at 212650 iteration is 851.572709010785
The cost at 212700 iteration is 851.5578341825146
The cost at 212750 iteration is 851.5429625625545
The cost at 212800 iteration is 851.5280941501181
The cost at 212850 iteration is 851.5132289444107
The cost at 212900 iteration is 851.498366944646
The cost at 212950 iteration is 851.4835081500353
The cost at 213000 iteration is 851.4686525597916
The cost at 213050 iteration is 851.4538001731225
The cost at 213100 iteration is 851.4389509892421
The cost at 213150 iteration is 851.4241050073646
The cost at 213200 iteration is 851.4092622267016
The cost at 213250 iteration is 851.3944226464637
The cost at 213300 iteration is 851.3795862658657
The cost at 213350 iteration is 851.364753084121
The cost at 213400 iteration is 851.349923100442
The cost at 213450 iteration is 851.3350963140458
The cost at 213500 iteration is 851.3202727241428
The cost at 213550 iteration is 851.3054523299485
The cost at 213600 iteration is 851.2906351306794
The cost at 213650 iteration is 851.2758211255488
The cost at 213700 iteration is 851.2610103137706
The cost at 213750 iteration is 851.2462026945632
The cost at 213800 iteration is 851.2313982671424
The cost at 213850 iteration is 851.2165970307199
The cost at 213900 iteration is 851.201798984519
The cost at 213950 iteration is 851.1870041277505
The cost at 214000 iteration is 851.1722124596332
The cost at 214050 iteration is 851.1574239793862
The cost at 214100 iteration is 851.1426386862225
The cost at 214150 iteration is 851.1278565793646
The cost at 214200 iteration is 851.1130776580262
The cost at 214250 iteration is 851.098301921428
The cost at 214300 iteration is 851.0835293687884
The cost at 214350 iteration is 851.0687599993256
The cost at 214400 iteration is 851.0539938122561
The cost at 214450 iteration is 851.0392308068033
The cost at 214500 iteration is 851.0244709821862
The cost at 214550 iteration is 851.0097143376245
The cost at 214600 iteration is 850.9949608723324
The cost at 214650 iteration is 850.9802105855382
The cost at 214700 iteration is 850.9654634764612
The cost at 214750 iteration is 850.9507195443184
The cost at 214800 iteration is 850.9359787883322
The cost at 214850 iteration is 850.921241207728
The cost at 214900 iteration is 850.9065068017221
The cost at 214950 iteration is 850.8917755695395
Optimum parameters are [-1.11295245e+02 -7.85456966e+00 -5.00208795e+01  2.26583992e-01
 -2.03319736e+00 -1.58173761e+00 -1.41772084e+01 -2.60097774e+00
 -5.25579881e+00 -4.24054074e+00 -3.23835673e+00  3.01362670e+01
 -1.37755921e+00 -4.03595545e+00 -5.55060476e+00  1.05676420e+00
  3.16624343e+01  3.32539477e+00  2.04328985e+02  1.28591610e+02
 -6.03500873e-01 -2.34119294e-01  8.16002036e+00  1.21137192e+01
  3.30123398e+00  4.30942672e+01 -2.15016101e+01 -2.75968399e+00
  5.94881412e+00 -2.53402039e+01 -1.48242987e+00 -2.00941847e+01
 -8.01393287e+00  1.78470514e+01 -3.18809754e+00 -1.92313359e+00
  4.53160825e+00  2.81377417e+01 -5.03045819e+00 -3.53312359e+01
 -2.62051445e+00  1.50988336e+00  2.46196691e+01  3.21824636e+01
 -2.55164081e+01  3.63504603e+01 -2.06290517e+00 -4.15482913e+00
 -1.38855938e+00 -1.50961128e+00 -1.50438490e+01 -7.56918123e+00
 -2.57522778e+01 -3.72973960e+00  5.40624060e+00  3.26501691e+00
 -2.50949849e+01 -1.61059937e+01  4.75357017e+01 -1.59718274e+01
  1.68294629e+00  6.89570009e+01 -3.65874844e+00 -1.03976125e+00
 -2.88441235e+00  4.70405463e+01  3.55443188e+01 -2.58561243e+01
  3.32965158e+01  5.80258988e+01 -5.97686147e+01 -6.01578162e+00
  6.67952812e-01 -3.78964126e+00 -1.07529030e+00 -3.69989473e+00
 -2.97403621e+02 -4.55755154e+00  9.50643206e+00] -144.87384432331535

In [111]:
y_pred_train = predict(W, b, X_Train)

In [112]:
for i in range(50):
    print(y_pred_train[i], ",", Y_Train[i])

208.496540707996 , 208.5
183.42602625240457 , 181.5
214.3039354746792 , 223.5
165.97153730252896 , 140.0
284.5060302973636 , 250.0
178.71659074031717 , 143.0
260.314645390358 , 307.0
238.70373385305552 , 200.0
164.5281906532368 , 129.9
98.55988635691753 , 118.0
138.36720914124825 , 129.5
286.696305811916 , 345.0
137.94312896583526 , 144.0
237.10149968219687 , 279.5
163.97488215452367 , 157.0
123.20218280658932 , 132.0
145.77906254955136 , 149.0
109.67628296844819 , 90.0
174.49332598263854 , 159.0
141.50392118862467 , 139.0
297.3921650961945 , 325.3
91.45751102616046 , 139.4
246.06012249718012 , 230.0
153.02665991589194 , 129.9
145.19292678538582 , 154.0
256.8286597935306 , 256.3
140.42159630052524 , 134.8
256.50297573791227 , 306.0
215.14605744798362 , 207.5
53.77423482588111 , 68.5
104.73949244845059 , 40.0
143.3976675972693 , 149.35
167.71163373432145 , 179.9
194.32175532681677 , 165.5
228.58487841894785 , 277.5
268.329556801948 , 309.0
180.75045256842512 , 145.0
201.70219086138607 , 153.0
130.9043885755061 , 109.0
60.65385196008302 , 82.0
166.18965964238836 , 160.0
162.79457066512256 , 170.0
138.85783729071423 , 144.0
122.69396502605318 , 130.25
127.47361899598886 , 141.0
245.77887807803782 , 319.9
282.81443741421606 , 239.686
235.66488982244553 , 249.7
95.68701268043145 , 113.0
128.83103283482401 , 127.0

In [113]:
y_pred_test = predict(W, b, X_Test)

In [114]:
for i in range(50):
    print(y_pred_test[i])

152.4065885766066
168.5541030023962
199.91154702497377
202.01732010224956
170.89828475268516
180.7856016330641
188.18424860839602
159.6175823773403
186.93614185733676
143.2436739219281
193.50358624578766
122.96820127196767
124.6896999643665
156.74638774916812
95.33836397796588
283.50536044309763
234.94623773107142
265.6087692312916
250.10131255570977
420.27830332772805
292.4289418425881
184.31211114250286
173.4081823150689
152.7043671571993
148.45640661554975
190.45646497518837
315.9224820040789
243.57902953904122
183.10947467731577
225.61805484084366
195.18588721813657
108.77818022739027
190.11183849789435
277.06819304072474
276.6659238142498
208.29245002606578
182.04935214442978
147.0822941149651
143.03537981776665
155.2380793712404
208.26860790915973
125.82247659291207
254.9487958812921
228.57556452225404
225.00144803929547
225.20578574404843
282.98894191790635
223.16990778442712
165.30714935623624
175.01926716123612